//! Spec B — Session search summarization pipeline.
//!
//! ## Audit findings (Task 1, 2026-05-01)
//!
//! - `WorkingMemoryAssembler::assemble` lives in `src/memory/assembler/mod.rs`
//!   and `HybridAssembler::assemble` in `src/memory/assembler/hybrid.rs`.
//!   Signature: `async fn assemble(&self, query: &str, agent_id: &str, session_id: Option<&str>, budget: AssemblyBudget) -> Result<MemoryEnvelope, AlephError>`.
//!   Adding a `filter: FactSourceFilter` parameter is the chosen extension.
//!
//! - `FactSource` enum at `src/memory/context/enums.rs:180`. Variants:
//!   - `Extracted` (default, LLM-extracted from conversation)
//!   - `Summary` (L1 Overview generated by CompressionDaemon)
//!   - `Document` (User-uploaded long document, Markdown-first)
//!   - `Manual` (User-created manually)
//!   - `SessionCompressed` (Compressed summary from SessionCompactor during active session)
//!   - `Synthesis` (Synthesized from cross-session pattern extraction during weekly dream cycles)
//!   `SessionCompressed` is the primary variant Spec B targets for filtering.
//!
//! - `SessionStore::search_messages` at `src/gateway/session_store/mod.rs:37`.
//!   Signature: `async fn search_messages(&self, query: &str, max_results: usize) -> Result<Vec<SearchHit>, SessionStoreError>`.
//!   Does NOT accept a session_id filter; search is global across all sessions.
//!
//! - Memory-fact write entry-point: `NoteStore::index_note` at `src/memory/notes/store.rs:2`.
//!   Signature: `async fn index_note(&self, note: &KnowledgeNote, agent_id: &str, category: &str) -> Result<(), AlephError>`.
//!   No explicit INSERT OR IGNORE flag in the trait; implementation detail is in SQLite backend.
//!
//! - Spec A's `register_session_end_mcp` pattern at `src/thinker/memory_context_provider.rs:663`.
//!   Uses `tokio::sync::OnceCell<Arc<MemoryContextProvider>>` for single registration (idempotent, subsequent calls are no-op).
//!   Functions: `register_session_end_mcp(mcp: Arc<MemoryContextProvider>)` and `session_end_mcp() -> Option<Arc<MemoryContextProvider>>`.
//!
//! - `PostCompressionHook` trait at `src/memory/compression/service.rs:28`.
//!   Signature: `async fn on_compression_complete<'a>(&'a self, agent_id: &'a str) -> BoxFuture<'a, ()>`.
//!   Spec B does NOT implement this hook; the trait is left for future compression-time extensions.

pub mod dedup;
pub mod end_hook;
pub mod filter;
pub mod lookup;
pub mod synthesizer;
