//! The registered-RPC-method → role-classification census (round-5 ⑥).
//!
//! `method_admin.rs`'s module doc described the audit as "re-run the
//! mechanical sweep and diff it against the two constant tables" — but the
//! sweep was PROSE: nobody re-ran it, and a runtime census is structurally
//! blind to the ~60% of methods registered via `register_handler!` after
//! `HandlerRegistry::new()`. The four times an ungated server-global verb
//! was found by hand (`dreaming.run_now`, `memory.compress`,
//! `memory.reembed`, `memory.reembed.cancel` — round-4 ⑥) were instances of
//! that blindness. This module is the sweep, made executable: it scrapes the
//! three registration patterns out of the production half of every source
//! file, classifies each receiver, and pins every method's current ruling.
//!
//! The rules that keep the scraper honest (each earned, not imagined):
//! - comment lines and the `#[cfg(test)]` half are dropped BEFORE scraping
//!   (`utils::source_scan::production_text` + `strip_comment_lines`), so a
//!   doc comment naming a method can neither satisfy nor break the census,
//!   and a CRLF checkout scans identically to LF. `production_text`, not
//!   `production_prefix`: a WHOLE-FILE test module carries no `#[cfg(test)]`
//!   of its own — its parent applies one — so the per-file cut hands the
//!   scraper 100% of it. This used to be handled by skipping
//!   `rel.ends_with("/tests.rs")`, which sees 77 of the 107 whole-file test
//!   modules under `src/` and misses the other 30 (判据 §5) — the count and
//!   its predicate live with the guard, in
//!   `utils::source_scan::production_text_empties_whole_file_test_modules_and_only_those`;
//! - a `.register(` call is an RPC registration iff its receiver is
//!   `handlers_mut()` or a `registry: &mut HandlerRegistry` — every other
//!   receiver must be named in [`KNOWN_NON_RPC_REGISTRIES`] with its reason,
//!   and an UNRECOGNISED receiver fails the census rather than being
//!   skipped (a scanner that skips what it doesn't recognise reports "all
//!   classified" over a shrinking sample);
//! - dynamic first arguments (`registry.register(method, …)`) are legal only
//!   as the `for method in […]` loops of the phase-1 registry, whose array
//!   literals ARE scraped; the same shape anywhere else fails the census.

#[cfg(test)]
mod tests {
    use super::super::method_admin;

    use std::collections::{BTreeMap, BTreeSet};

    /// The ruling a method currently holds: admin-gated or member-open.
    /// Pinned per method so that flipping a table entry — or registering a
    /// new method — fails here until a human records the ruling.
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    enum Class {
        Admin,
        Open,
    }

    /// Non-RPC `.register(` receivers the sweep may meet and must skip —
    /// registries that share the method name but not the JSON-RPC table.
    /// A file landing here without a reason is how a second JSON-RPC
    /// registration site would hide, so each entry names the registry.
    const KNOWN_NON_RPC_REGISTRIES: &[(&str, &str)] = &[
        (
            "src/cluster/node_runtime.rs",
            "cluster node-command registry (bash/file.read/file.write node verbs, not gateway RPC)",
        ),
        (
            "src/thinker/mod.rs",
            "LLM provider registry (`anthropic` et al.), not gateway RPC",
        ),
    ];

    /// Every RPC method registered anywhere in `src/`, with its ruling at
    /// the time of the census. Generated by running the sweep below by hand;
    /// the test asserts the sweep and this list never drift apart.
    const RPC_METHOD_CENSUS: &[(&str, Class)] = &[
        ("acp.create", Class::Admin),
        ("acp.delete", Class::Admin),
        ("acp.get", Class::Admin),
        ("acp.list", Class::Admin),
        ("acp.presets", Class::Admin),
        ("acp.presets_meta", Class::Admin),
        ("acp.sessions.cancel", Class::Admin),
        ("acp.sessions.list", Class::Admin),
        ("acp.sessions.shutdown", Class::Admin),
        ("acp.set_enabled", Class::Admin),
        ("acp.test", Class::Admin),
        ("acp.update", Class::Admin),
        ("activity.stats", Class::Open),
        ("agent.cancel", Class::Open),
        ("agent.list", Class::Open),
        ("agent.resume", Class::Open),
        ("agent.run", Class::Open),
        ("agent.status", Class::Open),
        ("agents.bindings", Class::Admin),
        ("agents.create", Class::Admin),
        ("agents.delete", Class::Admin),
        ("agents.files.delete", Class::Admin),
        ("agents.files.get", Class::Admin),
        ("agents.files.list", Class::Admin),
        ("agents.files.set", Class::Admin),
        ("agents.get", Class::Open),
        ("agents.list", Class::Open),
        ("agents.set_default", Class::Admin),
        ("agents.teams", Class::Admin),
        ("agents.tools_schema", Class::Admin),
        ("agents.update", Class::Admin),
        ("artifacts.list", Class::Open),
        ("artifacts.read_text", Class::Open),
        ("behavior_config.get", Class::Admin),
        ("behavior_config.update", Class::Admin),
        ("browser_config.get", Class::Admin),
        ("browser_config.update", Class::Admin),
        ("bundled.sync", Class::Admin),
        ("canvas.apply", Class::Open),
        ("canvas.asset.get", Class::Open),
        ("canvas.asset.put", Class::Open),
        ("canvas.create", Class::Open),
        ("canvas.delete", Class::Open),
        ("canvas.get", Class::Open),
        ("canvas.list", Class::Open),
        ("canvas.selection.set", Class::Open),
        ("channel.create", Class::Admin),
        ("channel.delete", Class::Admin),
        ("channel.pairing.approve", Class::Admin),
        ("channel.pairing.approved", Class::Admin),
        ("channel.pairing.list", Class::Admin),
        ("channel.pairing.reject", Class::Admin),
        ("channel.pairing.revoke", Class::Admin),
        ("channel.pairing_data", Class::Admin),
        ("channel.send", Class::Admin),
        ("channel.start", Class::Admin),
        ("channel.stop", Class::Admin),
        ("channels.list", Class::Admin),
        ("channels.set_agent", Class::Admin),
        ("channels.status", Class::Admin),
        ("chat.abort", Class::Open),
        ("chat.clear", Class::Open),
        ("chat.context_estimate", Class::Open),
        ("chat.history", Class::Open),
        ("chat.rewind", Class::Open),
        ("chat.send", Class::Open),
        ("clarification.pending", Class::Open),
        ("clarification.resolve", Class::Open),
        ("cluster.deregister", Class::Admin),
        ("cluster.enroll", Class::Admin),
        ("command.execute", Class::Open),
        ("commands.list", Class::Open),
        ("config.get", Class::Admin),
        ("config.get_tool_permissions", Class::Open),
        ("config.patch", Class::Admin),
        ("config.path", Class::Admin),
        ("config.reload", Class::Admin),
        ("config.schema", Class::Admin),
        ("config.update_tool_permissions", Class::Admin),
        ("config.validate", Class::Admin),
        ("connect", Class::Open),
        ("cron.create", Class::Admin),
        ("cron.delete", Class::Admin),
        ("cron.get", Class::Admin),
        ("cron.list", Class::Admin),
        ("cron.run", Class::Admin),
        ("cron.runs", Class::Admin),
        ("cron.status", Class::Admin),
        ("cron.toggle", Class::Admin),
        ("cron.update", Class::Admin),
        ("daemon.logs", Class::Admin),
        ("daemon.shutdown", Class::Admin),
        ("daemon.status", Class::Admin),
        ("diagnostics.run", Class::Admin),
        ("discord.audit_permissions", Class::Admin),
        ("discord.list_channels", Class::Admin),
        ("discord.list_guilds", Class::Admin),
        ("discord.validate_token", Class::Admin),
        ("dreaming.list_insights", Class::Open),
        ("dreaming.run_now", Class::Admin),
        ("echo", Class::Open),
        ("embedding_providers.add", Class::Admin),
        ("embedding_providers.get", Class::Admin),
        ("embedding_providers.list", Class::Admin),
        ("embedding_providers.presets", Class::Admin),
        ("embedding_providers.remove", Class::Admin),
        ("embedding_providers.setActive", Class::Admin),
        ("embedding_providers.test", Class::Admin),
        ("embedding_providers.update", Class::Admin),
        ("environments.list", Class::Admin),
        ("exec.approval.resolve", Class::Open),
        ("exec.approvals.pending", Class::Open),
        ("exec.grant.revoke", Class::Open),
        ("exec.grants.list", Class::Open),
        ("execution_config.get", Class::Admin),
        ("execution_config.update", Class::Admin),
        ("extensions.catalog", Class::Admin),
        ("extensions.disclosure", Class::Admin),
        ("extensions.install", Class::Admin),
        ("extensions.installed", Class::Admin),
        ("extensions.toggle", Class::Admin),
        ("extensions.uninstall", Class::Admin),
        ("fetch_config.get", Class::Admin),
        ("fetch_config.test", Class::Admin),
        ("fetch_config.update", Class::Admin),
        ("fs.allowed_roots", Class::Open),
        ("fs.create_dir", Class::Open),
        ("fs.home_dir", Class::Open),
        ("fs.list_dir", Class::Open),
        ("fs.read_file", Class::Open),
        ("gateway.credentials", Class::Admin),
        ("gateway.devices.list", Class::Admin),
        ("gateway.devices.revoke", Class::Admin),
        ("gateway.flow.reload", Class::Admin),
        ("gateway.identity.get", Class::Admin),
        ("gateway.metrics.lanes", Class::Admin),
        ("gateway.metrics.run_concurrency", Class::Open),
        ("gateway.metrics.subagent_concurrency", Class::Admin),
        ("gateway.ticket.create", Class::Admin),
        ("gateway.ticket.list", Class::Admin),
        ("gateway.ticket.revoke", Class::Admin),
        ("gateway.token.current", Class::Admin),
        ("gateway.token.rotate", Class::Admin),
        ("general_config.get", Class::Admin),
        ("general_config.update", Class::Admin),
        ("generation_config.get", Class::Admin),
        ("generation_config.update", Class::Admin),
        ("generation_providers.create", Class::Admin),
        ("generation_providers.delete", Class::Admin),
        ("generation_providers.get", Class::Admin),
        ("generation_providers.list", Class::Admin),
        ("generation_providers.list_presets", Class::Admin),
        ("generation_providers.setDefault", Class::Admin),
        ("generation_providers.test", Class::Admin),
        ("generation_providers.update", Class::Admin),
        ("generation_providers.voices", Class::Admin),
        ("goal.list", Class::Open),
        ("graph.delete_note", Class::Open),
        ("graph.node_detail", Class::Open),
        ("graph.query", Class::Open),
        ("graph.rename_note", Class::Open),
        ("graph.search", Class::Open),
        ("graph.update_note", Class::Open),
        ("group_chat.continue", Class::Open),
        ("group_chat.end", Class::Open),
        ("group_chat.history", Class::Open),
        ("group_chat.list", Class::Open),
        ("group_chat.mention", Class::Open),
        ("group_chat.start", Class::Open),
        ("health", Class::Open),
        ("heartbeat.create", Class::Admin),
        ("heartbeat.delete", Class::Admin),
        ("heartbeat.get", Class::Open),
        ("heartbeat.list", Class::Open),
        ("heartbeat.runs", Class::Open),
        ("heartbeat.toggle", Class::Admin),
        ("heartbeat.update", Class::Admin),
        ("heartbeat.wake", Class::Admin),
        ("hooks.add", Class::Admin),
        ("hooks.events", Class::Admin),
        ("hooks.list", Class::Admin),
        ("hooks.registry", Class::Admin),
        ("hooks.reload", Class::Admin),
        ("hooks.remove", Class::Admin),
        ("identity.clear", Class::Admin),
        ("identity.get", Class::Admin),
        ("identity.list", Class::Admin),
        ("identity.set", Class::Admin),
        ("insights.tools", Class::Open),
        ("logs.getDirectory", Class::Admin),
        ("logs.getLevel", Class::Admin),
        ("logs.setLevel", Class::Admin),
        ("loop.list", Class::Open),
        ("mcp.add", Class::Admin),
        ("mcp.cancel_approval", Class::Admin),
        ("mcp.delete", Class::Admin),
        ("mcp.list", Class::Admin),
        ("mcp.list_pending_approvals", Class::Admin),
        ("mcp.logs", Class::Admin),
        ("mcp.prompts", Class::Admin),
        ("mcp.resources", Class::Admin),
        ("mcp.respond_approval", Class::Admin),
        ("mcp.restart", Class::Admin),
        ("mcp.start", Class::Admin),
        ("mcp.status", Class::Admin),
        ("mcp.stop", Class::Admin),
        ("mcp.tools", Class::Admin),
        ("mcp.update", Class::Admin),
        ("mcp_config.create", Class::Admin),
        ("mcp_config.delete", Class::Admin),
        ("mcp_config.get", Class::Admin),
        ("mcp_config.list", Class::Admin),
        ("mcp_config.update", Class::Admin),
        ("memory.compress", Class::Admin),
        // Curated hot tier: per-caller partition, so member-reachable like the
        // other `memory.*` reads. The mutations edit the caller's OWN MEMORY.md
        // (the resolver composes their scope), never a shared one.
        ("memory.curated.list", Class::Open),
        ("memory.curated.remove", Class::Open),
        ("memory.curated.replace", Class::Open),
        ("memory.delete", Class::Open),
        ("memory.listFacts", Class::Open),
        ("memory.list_corrections", Class::Open),
        ("memory.reembed", Class::Admin),
        ("memory.reembed.cancel", Class::Admin),
        ("memory.retrieve_with_trace", Class::Open),
        ("memory.search", Class::Open),
        ("memory.stats", Class::Open),
        ("memory.trace", Class::Open),
        ("memory_config.get", Class::Admin),
        ("memory_config.update", Class::Admin),
        ("moa.deletePreset", Class::Admin),
        ("moa.listPresets", Class::Admin),
        ("moa.savePreset", Class::Admin),
        ("moa.setDefault", Class::Admin),
        ("moa.setSaveTraces", Class::Admin),
        ("plugin.config.get", Class::Admin),
        ("plugin.config.set", Class::Admin),
        ("plugin.disable", Class::Admin),
        ("plugin.enable", Class::Admin),
        ("plugin.install", Class::Admin),
        ("plugin.installFromZip", Class::Admin),
        ("plugin.list", Class::Admin),
        ("plugin.marketplace.add", Class::Admin),
        ("plugin.marketplace.browse", Class::Admin),
        ("plugin.marketplace.install", Class::Admin),
        ("plugin.marketplace.list", Class::Admin),
        ("plugin.marketplace.remove", Class::Admin),
        ("plugin.marketplace.update", Class::Admin),
        ("plugin.reload", Class::Admin),
        ("plugin.uninstall", Class::Admin),
        ("plugin.update", Class::Admin),
        ("plugins.callTool", Class::Admin),
        ("plugins.disable", Class::Admin),
        ("plugins.enable", Class::Admin),
        ("plugins.executeCommand", Class::Admin),
        ("plugins.install", Class::Admin),
        ("plugins.installFromZip", Class::Admin),
        ("plugins.list", Class::Admin),
        ("plugins.load", Class::Admin),
        ("plugins.uninstall", Class::Admin),
        ("plugins.unload", Class::Admin),
        ("projects.add", Class::Open),
        ("projects.archive", Class::Open),
        ("projects.bind_workspace", Class::Open),
        ("projects.channel.bind", Class::Admin),
        ("projects.channel.list", Class::Open),
        ("projects.channel.unbind", Class::Admin),
        ("projects.create", Class::Open),
        ("projects.create_blank", Class::Open),
        ("projects.get", Class::Open),
        ("projects.list", Class::Open),
        ("projects.member.add", Class::Open),
        ("projects.member.list", Class::Open),
        ("projects.member.remove", Class::Open),
        ("projects.remove", Class::Open),
        ("projects.rename", Class::Open),
        ("projects.room_session", Class::Open),
        ("projects.touch", Class::Open),
        ("projects.workspace.list", Class::Open),
        ("projects.workspace.read", Class::Open),
        ("providers.catalog", Class::Admin),
        ("providers.create", Class::Admin),
        ("providers.delete", Class::Admin),
        ("providers.get", Class::Admin),
        ("providers.healthcheck", Class::Admin),
        ("providers.list", Class::Admin),
        ("providers.modelsRefresh", Class::Admin),
        ("providers.oauthLogin", Class::Admin),
        ("providers.oauthLogout", Class::Admin),
        ("providers.oauthStatus", Class::Admin),
        ("providers.setDefault", Class::Admin),
        ("providers.test", Class::Admin),
        ("providers.update", Class::Admin),
        ("pty.attach", Class::Admin),
        ("pty.close", Class::Admin),
        ("pty.input", Class::Admin),
        ("pty.list", Class::Admin),
        ("pty.resize", Class::Admin),
        ("pty.spawn", Class::Admin),
        ("request.state", Class::Open),
        ("rerank_config.get", Class::Admin),
        ("rerank_config.test", Class::Admin),
        ("rerank_config.update", Class::Admin),
        ("route_config.get", Class::Admin),
        ("route_config.update", Class::Admin),
        ("routing_rules.create", Class::Admin),
        ("routing_rules.delete", Class::Admin),
        ("routing_rules.get", Class::Admin),
        ("routing_rules.list", Class::Admin),
        ("routing_rules.move", Class::Admin),
        ("routing_rules.update", Class::Admin),
        ("runtime.agents.list", Class::Admin),
        ("runtimes.install", Class::Admin),
        ("runtimes.list", Class::Admin),
        ("runtimes.refresh", Class::Admin),
        ("search_config.deleteBackend", Class::Admin),
        ("search_config.get", Class::Admin),
        ("search_config.test", Class::Admin),
        ("search_config.update", Class::Admin),
        ("secrets.delete", Class::Admin),
        ("secrets.list", Class::Admin),
        ("secrets.providers", Class::Admin),
        ("secrets.set", Class::Admin),
        ("secrets.verify", Class::Admin),
        ("security.audit.query", Class::Admin),
        ("security_config.get", Class::Admin),
        ("security_config.update", Class::Admin),
        ("services.list", Class::Admin),
        ("services.start", Class::Admin),
        ("services.status", Class::Admin),
        ("services.stop", Class::Admin),
        ("session.compact", Class::Open),
        ("session.create", Class::Open),
        ("session.export_html", Class::Open),
        ("session.truncate", Class::Open),
        ("session.usage", Class::Open),
        ("sessions.compaction.branch", Class::Open),
        ("sessions.compaction.list", Class::Open),
        ("sessions.compaction.restore", Class::Open),
        ("sessions.delete", Class::Open),
        ("sessions.history", Class::Open),
        ("sessions.list", Class::Open),
        ("sessions.new", Class::Open),
        ("sessions.patch", Class::Open),
        ("sessions.preview", Class::Open),
        ("sessions.reset", Class::Open),
        ("sessions.set_project_root", Class::Open),
        ("sessions.set_topic", Class::Open),
        ("skills.install", Class::Admin),
        ("skills.install_dep", Class::Admin),
        ("skills.remove", Class::Admin),
        ("skills.status", Class::Admin),
        ("skills.update", Class::Admin),
        ("spend.query", Class::Admin),
        ("subagent.tree", Class::Open),
        ("system.info", Class::Open),
        ("teams.acp_member.add", Class::Open),
        ("teams.acp_member.list", Class::Open),
        ("teams.acp_member.remove", Class::Open),
        ("teams.add_task_comment", Class::Open),
        ("teams.chat.cancel", Class::Open),
        ("teams.chat.history", Class::Open),
        ("teams.chat.send", Class::Open),
        ("teams.chat.thread", Class::Open),
        ("teams.create", Class::Open),
        ("teams.create_task", Class::Open),
        ("teams.delete", Class::Open),
        ("teams.disband", Class::Open),
        ("teams.get", Class::Open),
        ("teams.list", Class::Open),
        ("teams.list_task_comments", Class::Open),
        ("teams.list_task_events", Class::Open),
        ("teams.list_task_runs", Class::Open),
        ("teams.list_tasks", Class::Open),
        ("teams.list_templates", Class::Open),
        ("teams.rename", Class::Open),
        ("teams.snapshot.create", Class::Open),
        ("teams.snapshot.delete", Class::Open),
        ("teams.snapshot.get", Class::Open),
        ("teams.snapshot.list", Class::Open),
        ("teams.snapshot.restore", Class::Open),
        ("teams.task.journal.get", Class::Open),
        ("teams.task.journal.list", Class::Open),
        ("teams.task.pause", Class::Open),
        ("teams.task.resume", Class::Open),
        ("teams.task.retry", Class::Open),
        ("teams.task.skip", Class::Open),
        ("teams.task.trace", Class::Open),
        ("teams.update_task", Class::Open),
        ("teams.usage", Class::Open),
        ("teams.workflow.approve_step", Class::Open),
        ("teams.workflow.reject_step", Class::Open),
        ("tools.cancel_call", Class::Admin),
        ("tools.catalog", Class::Admin),
        ("tools.effective", Class::Admin),
        ("tools.in_flight", Class::Admin),
        ("tools.invoke", Class::Open),
        ("trace.by_runs", Class::Open),
        ("trace.get", Class::Admin),
        ("trace.list", Class::Admin),
        ("users.create", Class::Admin),
        // A dossier over ANOTHER principal's holdings. Admin, and
        // deliberately not a `MEMBER_CARVE_OUTS` entry beside `users.me` /
        // `users.list`: those two are "my own record" and "who exists", this
        // one is somebody else's devices, spend and background work.
        ("users.get", Class::Admin),
        ("users.list", Class::Open),
        ("users.me", Class::Open),
        ("users.update", Class::Admin),
        ("version", Class::Open),
        ("voice.format", Class::Open),
        ("voice.record_start", Class::Open),
        ("voice.record_stop", Class::Open),
        ("voice.stream.audio", Class::Open),
        ("voice.stream.start", Class::Open),
        ("voice.stream.stop", Class::Open),
        ("voice.synthesize", Class::Open),
        ("voice.transcribe", Class::Open),
        ("wizard.answer", Class::Admin),
        ("wizard.cancel", Class::Admin),
        ("wizard.next", Class::Admin),
        ("wizard.start", Class::Admin),
        ("wizard.status", Class::Admin),
        ("workspace.archive", Class::Admin),
        ("workspace.create", Class::Admin),
        ("workspace.get", Class::Admin),
        ("workspace.list", Class::Admin),
        ("workspace.unarchive", Class::Admin),
        ("workspace.update", Class::Admin),
    ];

    /// Scrape every RPC method registration out of the production halves of
    /// `src/**/*.rs`. Returns the swept methods (with the file that
    /// registers them) and any registration-shaped call the receiver rules
    /// could not classify.
    fn sweep_rpc_methods() -> (BTreeMap<String, String>, Vec<String>) {
        fn walk(dir: &std::path::Path, out: &mut Vec<std::path::PathBuf>) {
            let Ok(entries) = std::fs::read_dir(dir) else {
                return;
            };
            for entry in entries.flatten() {
                let path = entry.path();
                if path.is_dir() {
                    walk(&path, out);
                } else if path.extension().is_some_and(|e| e == "rs") {
                    out.push(path);
                }
            }
        }

        let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("src");
        let mut files = Vec::new();
        walk(&root, &mut files);

        let mut swept: BTreeMap<String, String> = BTreeMap::new();
        let mut unknown: Vec<String> = Vec::new();
        for file in files {
            let rel = file
                .strip_prefix(env!("CARGO_MANIFEST_DIR"))
                .unwrap_or(&file)
                .to_string_lossy()
                .replace('\\', "/");
            let Ok(text) = std::fs::read_to_string(&file) else {
                continue;
            };
            // Test-only files register freely; they are not producers. This
            // used to be `rel.ends_with("/tests.rs")`, which at `f84ad424a`
            // recognised 85 of the 104 file-backed `#[cfg(test)] mod X;`
            // declarations in the repo and missed `guard_tests.rs`,
            // `drift_tests.rs`, `dispatchable.rs` and 16 more (判据 §5).
            // `production_text` asks the parent instead, which is the fact.
            let prod = crate::utils::source_scan::strip_comment_lines(
                &crate::utils::source_scan::production_text(&file, &text),
            );
            let is_handler_registry_file =
                prod.contains("&mut HandlerRegistry") || rel == "src/gateway/handlers/mod.rs";

            // `register_handler!(server, "method"` and `reg!("method"` — both
            // macro forms always land in the gateway registry; `reg!` exists
            // only inside `builder/handlers/mcp.rs`.
            for seg in prod.split("register_handler!(").skip(1) {
                if let Some(m) = literal_after_paren(seg) {
                    swept.entry(m).or_insert(rel.clone());
                }
            }
            for seg in prod.split("reg!(").skip(1) {
                // Exclude `register_handler!(` which also contains `reg!(` —
                // the split above already owns it.
                let Some(m) = literal_after_paren(seg) else {
                    continue;
                };
                if rel != "src/bin/aleph-server/commands/start/builder/handlers/mcp.rs" {
                    unknown.push(format!(
                        "{rel}: reg!(\"{m}\") outside builder/handlers/mcp.rs"
                    ));
                } else {
                    swept.entry(m).or_insert(rel.clone());
                }
            }

            // `.register(` — literal and dynamic first arguments.
            let mut offset = 0;
            while let Some(rel_pos) = prod[offset..].find(".register(") {
                let pos = offset + rel_pos;
                let seg = &prod[pos + ".register(".len()..];
                offset = pos + 1;
                let before = &prod[..pos];
                let tail: String = before
                    .chars()
                    .rev()
                    .take(90)
                    .collect::<String>()
                    .chars()
                    .rev()
                    .collect();
                let receiver_is_handlers_mut = tail.trim_end().ends_with("handlers_mut()");
                let receiver_is_registry = tail.trim_end().ends_with("registry");
                // Macro-definition lines register nothing at runtime — the
                // `$` metavariable sits in the receiver OR the argument.
                if tail.contains('$') || seg.trim_start().starts_with('$') {
                    continue;
                }
                match literal_after_paren(seg) {
                    Some(m) => {
                        if receiver_is_handlers_mut
                            || (receiver_is_registry && is_handler_registry_file)
                        {
                            swept.entry(m).or_insert(rel.clone());
                        } else if KNOWN_NON_RPC_REGISTRIES.iter().any(|(f, _)| *f == rel) {
                            // Named non-RPC registry — skipped with a reason.
                        } else {
                            unknown.push(format!(
                                "{rel}: .register(\"{m}\") with an unrecognised receiver"
                            ));
                        }
                    }
                    None => {
                        // Dynamic first argument: legal only as the phase-1
                        // `for method in […]` loops, whose arrays are scraped
                        // separately below.
                        let dynamic_rpc = receiver_is_handlers_mut
                            || (receiver_is_registry && is_handler_registry_file);
                        if dynamic_rpc && rel != "src/gateway/handlers/mod.rs" {
                            unknown.push(format!(
                                "{rel}: dynamic .register( into an RPC registry — only the \
                                 phase-1 `for method in […]` loops may do that"
                            ));
                        }
                    }
                }
            }

            // The phase-1 placeholder loops register whole method arrays
            // (`canvas.*`, `wizard.*`) via a dynamic call — scrape the array
            // literals so those methods join the census too.
            if rel == "src/gateway/handlers/mod.rs" {
                let mut arr_rest = prod.as_str();
                while let Some(pos) = arr_rest.find("for method in [") {
                    let seg = &arr_rest[pos + "for method in [".len()..];
                    arr_rest = &seg[1..];
                    let Some(close) = seg.find(']') else { continue };
                    let body = &seg[..close];
                    let mut b = body;
                    while let Some(q) = b.find('"') {
                        let after = &b[q + 1..];
                        let Some(end) = after.find('"') else { break };
                        let lit = &after[..end];
                        if lit.contains('.') {
                            swept.entry(lit.to_string()).or_insert(rel.clone());
                        }
                        b = &after[end + 1..];
                    }
                }
            }
        }
        (swept, unknown)
    }

    /// The string literal immediately after the opening paren, if the first
    /// argument is a literal — `None` for composed/dynamic arguments.
    fn literal_after_paren(seg: &str) -> Option<String> {
        let trimmed = seg.trim_start();
        // `register_handler!(server, "…"` carries a receiver ident first.
        let after_receiver = if let Some(comma) = trimmed.find(',') {
            // Only strip a receiver when one is there: `register(` starts
            // with the literal directly.
            let (head, tail) = trimmed.split_at(comma);
            if head.chars().all(|c| c.is_alphanumeric() || c == '_') && !head.is_empty() {
                tail[1..].trim_start()
            } else {
                trimmed
            }
        } else {
            trimmed
        };
        let rest = after_receiver.strip_prefix('"')?;
        let close = rest.find('"')?;
        Some(rest[..close].to_string())
    }

    #[test]
    fn the_scanner_classifies_every_receiver_it_meets() {
        let (_swept, unknown) = sweep_rpc_methods();
        assert!(
            unknown.is_empty(),
            "registration-shaped calls the census cannot classify — a scanner \
             that skips these reports 'all classified' over a shrinking sample. \
             Name the receiver in KNOWN_NON_RPC_REGISTRIES (with its reason) or \
             fix the call:
  {}",
            unknown.join(
                "
  "
            )
        );
    }

    #[test]
    fn every_registered_rpc_method_has_a_recorded_ruling() {
        let (swept, _unknown) = sweep_rpc_methods();
        let swept_names: BTreeSet<&str> = swept.keys().map(String::as_str).collect();
        let census_names: BTreeSet<&str> = RPC_METHOD_CENSUS.iter().map(|(m, _)| *m).collect();

        let missing: Vec<&str> = swept_names.difference(&census_names).copied().collect();
        let stale: Vec<&str> = census_names.difference(&swept_names).copied().collect();

        assert!(
            missing.is_empty(),
            "newly registered RPC methods with no recorded ruling. Register the \
             ruling in RPC_METHOD_CENSUS — Admin or Open is a DECISION, not a \
             default:
  {missing:?}"
        );
        assert!(
            stale.is_empty(),
            "RPC_METHOD_CENSUS names methods no longer registered anywhere — a \
             census that lists things that stopped existing stops being read:
  {stale:?}"
        );

        for (method, expected) in RPC_METHOD_CENSUS {
            let actual = method_admin::method_requires_admin(method);
            let actual_class = if actual { Class::Admin } else { Class::Open };
            assert_eq!(
                *expected, actual_class,
                "{method}: the census says {expected:?} but the role tables say {actual_class:?} — \
                 one of them was changed without the other"
            );
        }
    }

    /// A registered method with no `.` in its name skips
    /// `Lane::for_method`'s suffix heuristic entirely and lands on the
    /// `Mutate` default — which `needs_idempotency()`. Under
    /// `[gateway] require_idempotency_key = true` that is a refusal issued
    /// before dispatch, and no first-party client sends such a key.
    ///
    /// `connect` was in exactly that position: the handshake was refused
    /// before `resolve_connect_auth` ran, the login wall then refused
    /// everything else, and the daemon stayed up and healthy while nothing —
    /// desktop Panel on loopback included — could reach it. The lane table's
    /// own tests could not see it (none of them mention `connect`) and no test
    /// anywhere sets the flag: both in-process harnesses hardcode it `false`.
    ///
    /// Derived from the sweep, not from a list restated here, so a newly
    /// registered dotless method fails until a human rules on its lane.
    #[test]
    fn every_dotless_registered_method_is_explicitly_lane_classified() {
        use crate::gateway::lane::Lane;

        let (swept, _unknown) = sweep_rpc_methods();
        let dotless: Vec<&str> = swept
            .keys()
            .map(String::as_str)
            .filter(|m| !m.contains('.'))
            .collect();
        assert!(
            !dotless.is_empty(),
            "this guard proved nothing: the sweep found no dotless method at \
             all, so the filter below never reached an assertion"
        );

        let unruled: Vec<&str> = dotless
            .iter()
            .copied()
            .filter(|m| !Lane::is_explicitly_classified(m))
            .collect();
        assert!(
            unruled.is_empty(),
            "dotless RPC methods with no lane ruling. They fall through to \
             Lane::Mutate, which needs an idempotency key, so under \
             `require_idempotency_key = true` they are refused before \
             dispatch. Name each one in `Lane::override_for` — Query or \
             Mutate is a DECISION, not a default:
  {unruled:?}"
        );
    }

    #[test]
    fn the_role_tables_have_no_ghost_entries() {
        let (swept, _unknown) = sweep_rpc_methods();
        let names: Vec<&str> = swept.keys().map(String::as_str).collect();
        let mut ghosts: Vec<String> = Vec::new();
        for (table, entries) in method_admin::GHOST_CHECK_TABLES {
            for entry in *entries {
                let matched = names.iter().any(|m| {
                    if entry.ends_with('.') {
                        m.starts_with(entry)
                    } else {
                        *m == *entry
                    }
                });
                if !matched {
                    ghosts.push(format!("{table}: {entry}"));
                }
            }
        }
        assert!(
            ghosts.is_empty(),
            "role-table entries that match no registered method — a gate over \
             nothing reads as a gate over something (the `users.` pre-gate was \
             exactly this):
  {}",
            ghosts.join(
                "
  "
            )
        );
    }
}
