//! Command handlers

pub mod ask;
pub mod chat;
pub mod chat_cmd;
pub mod completion;
pub mod config_cmd;
pub mod connect;
pub mod gateway_cmd;
pub mod daemon;
pub mod guests;
pub mod health;
pub mod identity_cmd;
pub mod logs_cmd;
pub mod info;
pub mod memory_cmd;
pub mod models_cmd;
pub mod plugins_cmd;
pub mod poe_cmd;
pub mod providers_cmd;
pub mod services_cmd;
pub mod session;
pub mod skills_cmd;
pub mod tools;
pub mod vault_cmd;
pub mod workspace_cmd;
