//! Provider preset definitions
//!
//! Shared between the settings form and the setup wizard.

/// Provider preset for quick-setup
pub struct ProviderPreset {
    pub name: &'static str,
    pub protocol: &'static str,
    pub model: &'static str,
    pub base_url: &'static str,
    pub description: &'static str,
    pub api_key_placeholder: &'static str,
    pub icon_color: &'static str,
    pub needs_api_key: bool,
    pub auth_type: &'static str,
}

pub const PRESETS: &[ProviderPreset] = &[
    ProviderPreset {
        name: "anthropic",
        protocol: "anthropic",
        model: "claude-sonnet-4-5-20250514",
        base_url: "https://api.anthropic.com",
        description: "Claude by Anthropic",
        api_key_placeholder: "sk-ant-...",
        icon_color: "#D97757",
        needs_api_key: true,
        auth_type: "api_key",
    },
    ProviderPreset {
        name: "openai",
        protocol: "openai",
        model: "gpt-4o",
        base_url: "https://api.openai.com/v1",
        description: "GPT models by OpenAI",
        api_key_placeholder: "sk-...",
        icon_color: "#10A37F",
        needs_api_key: true,
        auth_type: "api_key",
    },
    ProviderPreset {
        name: "gemini",
        protocol: "gemini",
        model: "gemini-2.5-flash",
        base_url: "https://generativelanguage.googleapis.com",
        description: "Gemini by Google",
        api_key_placeholder: "AIza...",
        icon_color: "#4285F4",
        needs_api_key: true,
        auth_type: "api_key",
    },
    ProviderPreset {
        name: "deepseek",
        protocol: "openai",
        model: "deepseek-chat",
        base_url: "https://api.deepseek.com/v1",
        description: "DeepSeek AI",
        api_key_placeholder: "sk-...",
        icon_color: "#4D6BFE",
        needs_api_key: true,
        auth_type: "api_key",
    },
    ProviderPreset {
        name: "moonshot",
        protocol: "openai",
        model: "moonshot-v1-8k",
        base_url: "https://api.moonshot.cn/v1",
        description: "Kimi by Moonshot AI",
        api_key_placeholder: "sk-...",
        icon_color: "#5B21B6",
        needs_api_key: true,
        auth_type: "api_key",
    },
    ProviderPreset {
        name: "volcengine",
        protocol: "openai",
        model: "doubao-1.5-pro-256k",
        base_url: "https://ark.cn-beijing.volces.com/api/v3",
        description: "Doubao by Volcengine",
        api_key_placeholder: "sk-...",
        icon_color: "#FF6B35",
        needs_api_key: true,
        auth_type: "api_key",
    },
    ProviderPreset {
        name: "siliconflow",
        protocol: "openai",
        model: "deepseek-ai/DeepSeek-V3",
        base_url: "https://api.siliconflow.cn/v1",
        description: "SiliconFlow AI Cloud",
        api_key_placeholder: "sk-...",
        icon_color: "#6C5CE7",
        needs_api_key: true,
        auth_type: "api_key",
    },
    ProviderPreset {
        name: "zhipu",
        protocol: "openai",
        model: "GLM-5",
        base_url: "https://open.bigmodel.cn/api/paas/v4",
        description: "GLM by Zhipu AI",
        api_key_placeholder: "sk-...",
        icon_color: "#3B5998",
        needs_api_key: true,
        auth_type: "api_key",
    },
    ProviderPreset {
        name: "minimax",
        protocol: "openai",
        model: "MiniMax-M2.5",
        base_url: "https://api.minimax.io/v1",
        description: "MiniMax AI",
        api_key_placeholder: "sk-...",
        icon_color: "#E84393",
        needs_api_key: true,
        auth_type: "api_key",
    },
    ProviderPreset {
        name: "ollama",
        protocol: "ollama",
        model: "llama3.3",
        base_url: "http://localhost:11434",
        description: "Local models via Ollama",
        api_key_placeholder: "",
        icon_color: "#1D1D1F",
        needs_api_key: false,
        auth_type: "api_key",
    },
    ProviderPreset {
        name: "groq",
        protocol: "openai",
        model: "llama-3.3-70b-versatile",
        base_url: "https://api.groq.com/openai/v1",
        description: "Fast inference by Groq",
        api_key_placeholder: "gsk_...",
        icon_color: "#F55036",
        needs_api_key: true,
        auth_type: "api_key",
    },
    ProviderPreset {
        name: "openrouter",
        protocol: "openai",
        model: "anthropic/claude-sonnet-4-5",
        base_url: "https://openrouter.ai/api/v1",
        description: "Unified API gateway",
        api_key_placeholder: "sk-or-...",
        icon_color: "#6366F1",
        needs_api_key: true,
        auth_type: "api_key",
    },
];

pub const OAUTH_PRESETS: &[ProviderPreset] = &[
    ProviderPreset {
        name: "codex",
        protocol: "chatgpt",
        model: "gpt-5.3-codex",
        base_url: "https://chatgpt.com",
        description: "OpenAI Codex via ChatGPT subscription",
        api_key_placeholder: "",
        icon_color: "#10A37F",
        needs_api_key: false,
        auth_type: "oauth",
    },
];

pub fn find_preset(name: &str) -> Option<&'static ProviderPreset> {
    PRESETS.iter().chain(OAUTH_PRESETS.iter()).find(|p| p.name == name)
}
