using System.Runtime.InteropServices;

namespace POC.RustFFI;

/// <summary>
/// P/Invoke declarations for aethecore.dll
///
/// In production, this file would be auto-generated by csbindgen.
/// For POC, we manually declare the methods matching ffi_cabi.rs
/// </summary>
internal static unsafe partial class NativeMethods
{
    private const string DllName = "aethecore";

    /// <summary>
    /// Initialize the Aether core library.
    /// </summary>
    /// <param name="configPath">Path to config file (UTF-8, null-terminated)</param>
    /// <returns>0 on success, negative error code on failure</returns>
    [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
    public static extern int aether_init(byte* configPath);

    /// <summary>
    /// Free resources allocated by the Aether core library.
    /// </summary>
    [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
    public static extern int aether_free();

    /// <summary>
    /// Get the version string of the Aether core library.
    /// </summary>
    /// <returns>Pointer to static null-terminated string</returns>
    [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
    public static extern byte* aether_version();

    /// <summary>
    /// Register callback for state changes.
    /// </summary>
    [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void aether_register_state_callback(
        delegate* unmanaged[Cdecl]<int, void> callback);

    /// <summary>
    /// Register callback for streaming text.
    /// </summary>
    [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void aether_register_stream_callback(
        delegate* unmanaged[Cdecl]<byte*, void> callback);

    /// <summary>
    /// Register callback for errors.
    /// </summary>
    [DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void aether_register_error_callback(
        delegate* unmanaged[Cdecl]<byte*, int, void> callback);
}

/// <summary>
/// Callback delegate types (for reference, using function pointers instead)
/// </summary>
public static class CallbackTypes
{
    public delegate void StateChangeCallback(int state);
    public delegate void StreamTextCallback(IntPtr text);
    public delegate void ErrorCallback(IntPtr message, int code);
}
