//! Authentication Handlers
//!
//! Handles device authentication, pairing, and connection management.

mod connect;
mod pairing;
mod devices;

use serde::{Deserialize, Serialize};
use serde_json::json;
use crate::sync_primitives::Arc;

use crate::gateway::device_store::DeviceStore;
use crate::gateway::protocol::JsonRpcRequest;
use crate::gateway::config::AuthMode;
use crate::gateway::security::{PairingManager, SharedTokenManager, TokenManager};
use crate::gateway::security::SecurityStore;

// Re-export all public items at their original paths
pub use connect::handle_connect;
pub use pairing::{handle_pairing_approve, handle_pairing_reject, handle_pairing_list};
pub use devices::{handle_devices_list, handle_devices_revoke};

/// Parameters for the "hello" method (server -> client notification)
#[derive(Debug, Clone, Serialize)]
pub struct HelloParams {
    /// Protocol version
    pub version: String,
    /// Server name
    pub server: String,
    /// Whether authentication is required
    pub auth_required: bool,
}

/// Parameters for the "connect" method
#[derive(Debug, Clone, Deserialize)]
pub struct ConnectParams {
    /// Device token (for returning devices)
    pub token: Option<String>,
    /// Shared token (for web panel / UI access)
    pub shared_token: Option<String>,
    /// Guest invitation token (for guest access)
    pub invitation_token: Option<String>,
    /// Device name (for new devices)
    pub device_name: Option<String>,
    /// Device type (macos, ios, android, cli, web)
    pub device_type: Option<String>,
    /// Unique device identifier (generated by client)
    pub device_id: Option<String>,
}

/// Result of a successful connection
#[derive(Debug, Clone, Serialize)]
pub struct ConnectResult {
    /// Session token for this connection
    pub token: String,
    /// Device ID
    pub device_id: String,
    /// Permissions granted
    pub permissions: Vec<String>,
    /// Token expiry time (ISO 8601)
    pub expires_at: String,
}

/// Pairing required notification
#[derive(Debug, Clone, Serialize)]
pub struct PairingRequiredParams {
    /// 8-character Base32 pairing code
    pub code: String,
    /// Seconds until code expires
    pub expires_in: u64,
    /// Instructions for user
    pub message: String,
}

/// Authentication context for handlers
pub struct AuthContext {
    pub token_manager: Arc<TokenManager>,
    pub pairing_manager: Arc<PairingManager>,
    pub device_store: Arc<DeviceStore>,
    pub security_store: Arc<SecurityStore>,
    pub invitation_manager: Arc<crate::gateway::security::InvitationManager>,
    pub guest_session_manager: Arc<crate::gateway::security::GuestSessionManager>,
    pub event_bus: Arc<crate::gateway::event_bus::GatewayEventBus>,
    pub auth_mode: AuthMode,
    pub shared_token_mgr: Arc<SharedTokenManager>,
}

/// Create a "hello" notification to send to newly connected clients
pub fn create_hello_notification(auth_mode: &AuthMode) -> JsonRpcRequest {
    JsonRpcRequest::notification(
        "hello",
        Some(json!(HelloParams {
            version: "1".to_string(),
            server: format!("aleph-gateway/{}", env!("CARGO_PKG_VERSION")),
            auth_required: auth_mode.is_auth_required(),
        })),
    )
}

#[cfg(test)]
pub(crate) mod tests {
    use super::*;
    use crate::gateway::security::store::DeviceUpsertData;

    pub(crate) fn create_test_context() -> Arc<AuthContext> {
        let store = Arc::new(SecurityStore::in_memory().unwrap());
        // Create a device for token tests
        store
            .upsert_device(&DeviceUpsertData {
                device_id: "test-dev",
                device_name: "Test",
                device_type: None,
                public_key: &[1u8; 32],
                fingerprint: "fp",
                role: "operator",
                scopes: &[],
            })
            .unwrap();

        let invitation_manager = Arc::new(crate::gateway::security::InvitationManager::new());
        let guest_session_manager = Arc::new(crate::gateway::security::GuestSessionManager::new());
        let event_bus = Arc::new(crate::gateway::event_bus::GatewayEventBus::new());
        let shared_token_mgr = Arc::new(SharedTokenManager::new(store.clone(), "/tmp/aleph_test.vault"));

        Arc::new(AuthContext {
            token_manager: Arc::new(TokenManager::new(store.clone())),
            pairing_manager: Arc::new(PairingManager::new(store.clone())),
            device_store: Arc::new(DeviceStore::in_memory().unwrap()),
            security_store: store,
            invitation_manager,
            guest_session_manager,
            event_bus,
            auth_mode: AuthMode::Token,
            shared_token_mgr,
        })
    }
}
