//! Aether Skill Specification
//!
//! Data structures for parsing and representing Markdown-based CLI skills.
//! Compatible with OpenClaw SKILL.md format while adding Aether-specific extensions.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;

/// Aether Skill Specification (parsed from SKILL.md frontmatter)
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AetherSkillSpec {
    /// Tool name (e.g., "github-pr")
    pub name: String,

    /// Short description for LLM
    pub description: String,

    /// OpenClaw + Aether metadata
    pub metadata: SkillMetadata,

    /// Markdown content (injected as context)
    #[serde(skip)]
    pub markdown_content: String,
}

/// Skill metadata (OpenClaw compatible + Aether extensions)
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SkillMetadata {
    /// OpenClaw compatibility: required binaries
    #[serde(default)]
    pub requires: RequiresSpec,

    /// Aether extensions (optional)
    #[serde(default)]
    pub aether: Option<AetherExtensions>,
}

/// Required binaries specification
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct RequiresSpec {
    /// List of required binary names (e.g., ["gh", "jq"])
    #[serde(default)]
    pub bins: Vec<String>,
}

/// Aether-specific extensions
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AetherExtensions {
    /// Security controls
    #[serde(default)]
    pub security: SecuritySpec,

    /// Type hints for input validation
    #[serde(default)]
    pub input_hints: HashMap<String, InputHint>,

    /// Evolution metadata (auto-generated)
    #[serde(default)]
    pub evolution: Option<EvolutionMeta>,

    /// Docker execution configuration
    #[serde(default)]
    pub docker: Option<DockerConfig>,
}

/// Security specification
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SecuritySpec {
    /// Execution sandbox mode
    #[serde(default = "default_sandbox")]
    pub sandbox: SandboxMode,

    /// User confirmation requirement
    #[serde(default = "default_confirmation")]
    pub confirmation: ConfirmationMode,

    /// Network access level
    #[serde(default = "default_network")]
    pub network: NetworkMode,
}

/// Sandbox execution mode
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum SandboxMode {
    /// Run on host with SafetyGate
    Host,
    /// Run in Docker container
    Docker,
    /// Run with virtual filesystem (future)
    VirtualFs,
}

/// Confirmation requirement mode
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum ConfirmationMode {
    /// Always require confirmation
    Always,
    /// Only for write operations
    Write,
    /// Never require confirmation
    Never,
}

/// Network access mode
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum NetworkMode {
    /// Full internet access
    Internet,
    /// Local network only
    Local,
    /// No network access
    None,
}

/// Input parameter type hint
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct InputHint {
    /// Type hint (string, integer, number, boolean, array, object)
    #[serde(rename = "type")]
    pub hint_type: Option<String>,

    /// Regex pattern for validation
    pub pattern: Option<String>,

    /// Enum values (for enum types)
    pub values: Option<Vec<String>>,

    /// Parameter description
    pub description: Option<String>,

    /// Whether this parameter is optional (default: false = required)
    #[serde(default)]
    pub optional: bool,
}

/// Evolution metadata (auto-generated by Evolution Loop)
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EvolutionMeta {
    /// Source: "manual" | "auto-generated"
    pub source: String,

    /// Confidence score (0.0-1.0)
    pub confidence_score: f64,

    /// Trace ID that generated this skill
    pub created_from_trace: Option<String>,
}

/// Docker execution configuration
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DockerConfig {
    /// Docker image to use (REQUIRED for docker sandbox mode)
    pub image: String,

    /// Environment variables to pass from host (allowlist)
    #[serde(default)]
    pub env_vars: Vec<String>,

    /// Additional docker run flags
    #[serde(default)]
    pub extra_flags: Vec<String>,
}

// Default functions
fn default_sandbox() -> SandboxMode {
    SandboxMode::Host
}

fn default_confirmation() -> ConfirmationMode {
    ConfirmationMode::Write
}

fn default_network() -> NetworkMode {
    NetworkMode::Internet
}

impl Default for SecuritySpec {
    fn default() -> Self {
        Self {
            sandbox: default_sandbox(),
            confirmation: default_confirmation(),
            network: default_network(),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_basic_spec() {
        let yaml = r#"
name: test-tool
description: A test tool
metadata:
  requires:
    bins: ["echo"]
"#;

        let spec: AetherSkillSpec = serde_yaml::from_str(yaml).unwrap();
        assert_eq!(spec.name, "test-tool");
        assert_eq!(spec.description, "A test tool");
        assert_eq!(spec.metadata.requires.bins, vec!["echo"]);
        assert!(spec.metadata.aether.is_none());
    }

    #[test]
    fn test_parse_aether_extensions() {
        let yaml = r#"
name: gh-pr
description: GitHub PR operations
metadata:
  requires:
    bins: ["gh"]
  aether:
    security:
      sandbox: docker
      confirmation: always
      network: internet
    docker:
      image: "ghcr.io/cli/cli:latest"
      env_vars: ["GITHUB_TOKEN"]
    input_hints:
      repo:
        type: string
        pattern: "^[^/]+/[^/]+$"
        optional: false
"#;

        let spec: AetherSkillSpec = serde_yaml::from_str(yaml).unwrap();
        let aether = spec.metadata.aether.unwrap();

        assert!(matches!(aether.security.sandbox, SandboxMode::Docker));
        assert!(matches!(
            aether.security.confirmation,
            ConfirmationMode::Always
        ));

        let docker = aether.docker.unwrap();
        assert_eq!(docker.image, "ghcr.io/cli/cli:latest");
        assert_eq!(docker.env_vars, vec!["GITHUB_TOKEN"]);

        let hint = aether.input_hints.get("repo").unwrap();
        assert_eq!(hint.hint_type.as_ref().unwrap(), "string");
        assert_eq!(hint.pattern.as_ref().unwrap(), "^[^/]+/[^/]+$");
        assert!(!hint.optional);
    }

    #[test]
    fn test_default_security_spec() {
        let spec = SecuritySpec::default();
        assert!(matches!(spec.sandbox, SandboxMode::Host));
        assert!(matches!(spec.confirmation, ConfirmationMode::Write));
        assert!(matches!(spec.network, NetworkMode::Internet));
    }
}
