//! Authentication Handlers
//!
//! Handles device authentication, pairing, and connection management.

mod connect;
mod connect_challenge;
mod devices;
mod pairing;

use crate::sync_primitives::Arc;
use serde::{Deserialize, Serialize};
use serde_json::json;

use crate::gateway::config::AuthMode;
use crate::gateway::device_store::DeviceStore;
use crate::gateway::hello_snapshot::{ConnectionLimits, HelloSnapshot};
use crate::gateway::presence::PresenceTracker;
use crate::gateway::protocol::JsonRpcRequest;
use crate::gateway::security::SecurityStore;
use crate::gateway::security::{PairingManager, SharedTokenManager, TokenManager};

/// Capabilities advertised by every aleph-gateway build at handshake time.
///
/// Static so clients can sanity-check protocol compatibility without an
/// extra round-trip. Add new entries only when the relevant subsystem is
/// actually wired in this build.
pub const SERVER_CAPABILITIES: &[&str] = &[
    "memory",
    "tools",
    "mcp",
    "events",
    "streaming",
    "idempotency",
];

// Re-export all public items at their original paths
pub use connect::handle_connect;
pub use connect_challenge::handle_connect_challenge;
pub use devices::{handle_devices_list, handle_devices_revoke};
pub use pairing::{handle_pairing_approve, handle_pairing_list, handle_pairing_reject};

/// Parameters for the "hello" method (server -> client notification)
#[derive(Debug, Clone, Serialize)]
pub struct HelloParams {
    /// Protocol version
    pub version: String,
    /// Server name
    pub server: String,
    /// Whether authentication is required
    pub auth_required: bool,
}

/// Parameters for the "connect" method
#[derive(Debug, Clone, Deserialize)]
pub struct ConnectParams {
    /// Device token (for returning devices)
    pub token: Option<String>,
    /// Shared token (for web panel / UI access)
    pub shared_token: Option<String>,
    /// Guest invitation token (for guest access)
    pub invitation_token: Option<String>,
    /// Device name (for new devices)
    pub device_name: Option<String>,
    /// Device type (macos, ios, android, cli, web)
    pub device_type: Option<String>,
    /// Unique device identifier (generated by client)
    pub device_id: Option<String>,
    /// Optional challenge-response payload. Clients fetch a nonce via
    /// `connect.challenge`, sign it with their bearer (`HMAC-SHA256(token,
    /// nonce + timestamp + device_id)` — see [`crate::gateway::challenge`]),
    /// and echo `{nonce, signature}` here. When `require_challenge=true`
    /// the server rejects token/shared_token connects that omit this
    /// payload, hardening LAN/Tailnet bind modes against replay attacks.
    #[serde(default)]
    pub challenge: Option<ChallengeResponseParams>,
}

/// Client-supplied challenge response. Both fields originate from a prior
/// `connect.challenge` round-trip.
#[derive(Debug, Clone, Deserialize)]
pub struct ChallengeResponseParams {
    /// The 64-char hex nonce previously issued by `connect.challenge`.
    pub nonce: String,
    /// `HMAC-SHA256(bearer, nonce + timestamp + device_id)` as hex.
    pub signature: String,
}

/// Transport-layer policy advertised to the client at handshake time so it
/// can self-tune timers (keep-alive, reconnect deadlines) instead of guessing.
///
/// Mirrors the `policy` block in the openclaw `hello-ok` envelope. Clients
/// that ignore it keep working with their own defaults; clients that honour
/// it converge with the server config without an extra round-trip.
#[derive(Debug, Clone, Serialize)]
pub struct TransportPolicy {
    /// How often the server sends a WS Ping frame to each peer. Clients
    /// should expect at least one inbound frame per `ping_interval_secs`
    /// when the socket is healthy.
    pub ping_interval_secs: u64,
    /// Server-side inbound-idle threshold. Once exceeded, the server closes
    /// the connection with WS code 1008 — clients planning their own
    /// liveness probe should fire before this point.
    pub idle_timeout_secs: u64,
}

impl TransportPolicy {
    /// Static defaults that mirror [`super::super::server::GatewayConfig`].
    pub fn defaults() -> Self {
        Self {
            ping_interval_secs: 30,
            idle_timeout_secs: 90,
        }
    }
}

/// Result of a successful connection
#[derive(Debug, Clone, Serialize)]
pub struct ConnectResult {
    /// Session token for this connection
    pub token: String,
    /// Device ID
    pub device_id: String,
    /// Permissions granted
    pub permissions: Vec<String>,
    /// Token expiry time (ISO 8601)
    pub expires_at: String,
    /// Snapshot of server state versions {presence, health, config} at
    /// handshake time. Clients capture this baseline to later detect
    /// server-side state bumps and skip redundant refreshes.
    pub state_version: crate::gateway::state_version::StateVersion,
    /// Transport keep-alive policy the server will enforce on this socket.
    /// Lets the client align its own reconnect/probe cadence with the
    /// server's ping/idle timers.
    pub transport: TransportPolicy,
    /// Full server-state snapshot mirroring the openclaw `hello` envelope:
    /// server identity, uptime, presence roster, connection limits,
    /// capabilities, and active workspace. Lets clients render the panel
    /// without follow-up RPCs (`gateway.identity.get`, `presence.list`,
    /// `config.get`, …) immediately after `connect`.
    pub hello: HelloSnapshot,
}

/// Pairing required notification
#[derive(Debug, Clone, Serialize)]
pub struct PairingRequiredParams {
    /// 8-character Base32 pairing code
    pub code: String,
    /// Seconds until code expires
    pub expires_in: u64,
    /// Instructions for user
    pub message: String,
}

/// Authentication context for handlers
pub struct AuthContext {
    pub token_manager: Arc<TokenManager>,
    pub pairing_manager: Arc<PairingManager>,
    pub device_store: Arc<DeviceStore>,
    pub security_store: Arc<SecurityStore>,
    pub invitation_manager: Arc<crate::gateway::security::InvitationManager>,
    pub guest_session_manager: Arc<crate::gateway::security::GuestSessionManager>,
    pub event_bus: Arc<crate::gateway::event_bus::GatewayEventBus>,
    pub auth_mode: AuthMode,
    pub shared_token_mgr: Arc<SharedTokenManager>,
    /// Monotonic state-version tracker, shared with `GatewayServer`.
    /// Surfaced in the `connect` success response so clients capture a
    /// baseline snapshot at handshake time.
    pub state_versions: Arc<crate::gateway::state_version::StateVersionTracker>,
    /// Transport keep-alive policy returned to clients at handshake time.
    /// Sourced from `GatewayConfig::{ping_interval_secs, idle_timeout_secs}`
    /// so client and server agree on the live cadence.
    pub transport_policy: TransportPolicy,
    /// Per-process instance id (UUID v4, regenerated on restart). Used as
    /// `HelloSnapshot::server_id` so clients can detect server restart vs
    /// same-server-reconnect across a network hiccup.
    pub instance_id: String,
    /// Unix epoch seconds at server start. Used to compute
    /// `HelloSnapshot::uptime_ms` without trusting the client clock.
    pub started_at_unix: i64,
    /// Live presence tracker, shared with `GatewayServer`. Read at
    /// handshake time to seed `HelloSnapshot::presence` so the panel can
    /// render the device roster without a follow-up RPC.
    pub presence: Arc<PresenceTracker>,
    /// Configured per-server connection cap, mirrored into
    /// `HelloSnapshot::limits.max_connections`. Sourced from
    /// `GatewayConfig::max_connections`.
    pub max_connections: u32,
    /// Challenge-response handshake manager. Issues nonces via
    /// `connect.challenge` and verifies them during `connect`. Always
    /// constructed (cheap); only consulted when the client opts in via
    /// `params.challenge` or when `require_challenge=true`.
    pub challenge_manager: Arc<crate::gateway::challenge::ChallengeManager>,
    /// When true, token-bearing `connect` calls MUST carry a
    /// `challenge: {nonce, signature}` payload or are rejected with
    /// `AUTH_FAILED`. Guest invitations are exempt. Default `false` —
    /// existing clients keep working until ops flips the knob.
    pub require_challenge: bool,
    /// One-shot bootstrap-nonce manager. Issues nonces via
    /// `gateway.bootstrap.issue`; the loopback `/auth/bootstrap` HTTP
    /// route consumes them and sets the session cookie. See
    /// [`crate::gateway::bootstrap::BootstrapNonceManager`].
    pub bootstrap_mgr: Arc<crate::gateway::bootstrap::BootstrapNonceManager>,
    /// The gateway's listening port — used to build the loopback URL
    /// returned by `gateway.bootstrap.issue` so callers (CLI, Tauri
    /// shell) don't need to know it independently.
    pub bind_port: u16,
}

/// Build a [`HelloSnapshot`] from the live [`AuthContext`].
///
/// `uptime_ms` uses wall-clock seconds (the same source as
/// `started_at_unix`) so the value is comparable across reconnects.
/// `current_connections` is taken from [`PresenceTracker::count`] — every
/// authenticated peer is registered there, so it's the right gauge.
///
/// `active_workspace` is intentionally `None` today: workspace state is
/// not yet a connect-time concern. Wire when the workspace concept lands
/// in `AuthContext`.
pub(crate) fn build_hello_snapshot(ctx: &AuthContext) -> HelloSnapshot {
    let now_unix = chrono::Utc::now().timestamp();
    let uptime_ms = now_unix
        .saturating_sub(ctx.started_at_unix)
        .max(0)
        .saturating_mul(1000) as u64;
    HelloSnapshot {
        server_id: ctx.instance_id.clone(),
        uptime_ms,
        state_version: ctx.state_versions.snapshot(),
        presence: ctx.presence.list(),
        limits: ConnectionLimits {
            max_connections: ctx.max_connections,
            current_connections: ctx.presence.count() as u32,
        },
        capabilities: SERVER_CAPABILITIES.iter().map(|s| s.to_string()).collect(),
        active_workspace: None,
    }
}

/// Create a "hello" notification to send to newly connected clients
pub fn create_hello_notification(auth_mode: &AuthMode) -> JsonRpcRequest {
    JsonRpcRequest::notification(
        "hello",
        Some(json!(HelloParams {
            version: "1".to_string(),
            server: format!("aleph-gateway/{}", env!("ALEPH_VERSION")),
            auth_required: auth_mode.is_auth_required(),
        })),
    )
}

#[cfg(test)]
pub(crate) mod tests {
    use super::*;
    use crate::gateway::security::store::DeviceUpsertData;

    pub(crate) fn create_test_context() -> Arc<AuthContext> {
        let store = Arc::new(SecurityStore::in_memory().unwrap());
        // Create a device for token tests
        store
            .upsert_device(&DeviceUpsertData {
                device_id: "test-dev",
                device_name: "Test",
                device_type: None,
                public_key: &[1u8; 32],
                fingerprint: "fp",
                role: "operator",
                scopes: &[],
            })
            .unwrap();

        let invitation_manager = Arc::new(crate::gateway::security::InvitationManager::new());
        let guest_session_manager = Arc::new(crate::gateway::security::GuestSessionManager::new());
        let event_bus = Arc::new(crate::gateway::event_bus::GatewayEventBus::new());
        let shared_token_mgr = Arc::new(SharedTokenManager::new(
            store.clone(),
            "/tmp/aleph_test.vault",
        ));

        Arc::new(AuthContext {
            token_manager: Arc::new(TokenManager::new(store.clone())),
            pairing_manager: Arc::new(PairingManager::new(store.clone())),
            device_store: Arc::new(DeviceStore::in_memory().unwrap()),
            security_store: store,
            invitation_manager,
            guest_session_manager,
            event_bus,
            auth_mode: AuthMode::Token,
            shared_token_mgr,
            state_versions: Arc::new(crate::gateway::state_version::StateVersionTracker::new()),
            transport_policy: TransportPolicy::defaults(),
            instance_id: "test-instance".to_string(),
            started_at_unix: 1_700_000_000,
            presence: Arc::new(PresenceTracker::new()),
            max_connections: 1000,
            challenge_manager: Arc::new(crate::gateway::challenge::ChallengeManager::new()),
            require_challenge: false,
            bootstrap_mgr: Arc::new(crate::gateway::bootstrap::BootstrapNonceManager::default()),
            bind_port: 18790,
        })
    }
}
