//! Wire vocabulary for session artifacts.
//!
//! An artifact is a byte blob a session produced or received. The bytes and
//! their metadata live in the core's `ArtifactStore`; what lives *here* is the
//! handful of strings that cross the wire, because those strings are matched
//! literally on both sides of the gateway and neither side fails loudly when
//! they drift.
//!
//! Two of them had already drifted into duplicates before this module existed:
//! the invalidation topic was spelled out once in the core emitter and once in
//! the Panel's subscriber, and the origin tokens were produced by a `serde`
//! rename on one side and matched as bare `&str` on the other. A mismatch in
//! either is silent — the pane simply stops refreshing, or every row falls
//! through to the default badge — so the only safe arrangement is one
//! declaration both crates read.
//!
//! # Why the origins are constants, not an enum
//!
//! The Panel deliberately keeps `origin` as a `String`. A core newer than the
//! Panel may name an origin the Panel has never heard of, and the row must
//! still render with a default badge rather than fail to deserialize. Sharing
//! an enum would force typed parsing and turn forward compatibility into a
//! parse error. Sharing the tokens gives both sides the same spelling without
//! taking that away; the core proves its `serde` output still matches them with
//! a drift-guard test next to the enum.

/// Topic every artifact invalidation ping is published on.
///
/// The frame is deliberately content-free beyond the session key — see the
/// core's `gateway::event_emitter::artifact_ping` for why a droppable event may
/// never be treated as the record.
pub const TOPIC: &str = "session.artifact";

/// Payload key naming the session whose artifact set changed.
pub const TOPIC_SESSION_KEY: &str = "session_key";

/// Received from the user or a channel: an upload, an attachment.
pub const ORIGIN_INBOUND: &str = "inbound";

/// Produced by a tool during a run: a generated image, a rendered chart.
pub const ORIGIN_OUTBOUND: &str = "outbound";

/// Generated by Aleph on demand: an exported conversation transcript.
pub const ORIGIN_EXPORT: &str = "export";

/// Published by the agent as the finished work product — the thing the user
/// actually asked for, as opposed to the conversation that produced it.
///
/// This is the origin the artifacts pane pins to the top and opens in a
/// browser; everything else is supporting material.
pub const ORIGIN_DELIVERABLE: &str = "deliverable";
