//! Durable, id-addressed artifact store.
//!
//! An "artifact" is a byte blob a session produced or received: an image a tool
//! generated, a file a user uploaded, an exported transcript. The store is the
//! **authoritative settlement** for those bytes — not any wire event.
//!
//! This matters because the `agent_trace` stream is deliberately lossy (bounded
//! `mpsc` + `try_send`, dropped rather than backpressuring the agent loop). A UI
//! that treated a live event as the record of truth would show permanent ghosts
//! whenever a frame is dropped. So live notifications are content-free
//! invalidation pings and every consumer re-reads [`ArtifactStore::list`].
//!
//! # Layout
//!
//! ```text
//! <root>/<encoded_session>/<id>.bin     raw bytes
//! <root>/<encoded_session>/<id>.json    the [`ArtifactRecord`] sidecar
//! ```
//!
//! There is no index file and no database table: [`ArtifactStore::list`] is a
//! `read_dir` over the sidecars. Records are immutable once written, and writes
//! go through a temp file + rename so a crash never publishes a half-written
//! blob.
//!
//! Sessions are isolated *structurally*: a session's artifacts only exist under
//! the directory its key encodes to, and [`encode_session_key`] is injective
//! (`%` is itself encoded), so no two distinct keys can collide on one
//! directory. A reader holding session A's key cannot name a path into session
//! B's directory.

mod store;

pub use store::{ArtifactStore, MAX_ARTIFACTS_PER_SESSION, MAX_ARTIFACT_BYTES};

use percent_encoding::{utf8_percent_encode, AsciiSet, NON_ALPHANUMERIC};
use serde::{Deserialize, Serialize};

/// Percent-encode set for turning a session key into one path component.
///
/// Keeps only `[A-Za-z0-9]`, `-` and `_`; everything else — including `:`,
/// `/`, `\`, `.` and `%` itself — is escaped. Three properties fall out:
///
/// * **Windows-safe.** Session keys look like `agent:main:main`, and `:` is
///   illegal in a Windows path component. Joining the raw key made
///   `create_dir_all` fail on Windows (the bug this set exists to prevent).
/// * **Traversal-safe.** `.` is encoded, so the result can never be `.` or
///   `..`, and no separator survives.
/// * **Injective.** `%` is encoded, so distinct keys always encode distinctly.
const SESSION_KEY_ENCODE_SET: &AsciiSet = &NON_ALPHANUMERIC.remove(b'-').remove(b'_');

/// Directory name used when a session key encodes to nothing (empty key).
const EMPTY_SESSION_DIR: &str = "_";

/// Encode a raw session key (e.g. `agent:main:main`) into a single, portable
/// path component.
///
/// Shared with the media cache so both agree on where a session's files live —
/// see [`SESSION_KEY_ENCODE_SET`] for the guarantees this provides.
#[must_use]
pub fn encode_session_key(session_key: &str) -> String {
    let encoded = utf8_percent_encode(session_key, SESSION_KEY_ENCODE_SET).to_string();
    if encoded.is_empty() {
        EMPTY_SESSION_DIR.to_string()
    } else {
        encoded
    }
}

/// Where an artifact came from.
///
/// Stamped by the call site, never sniffed from the bytes: only the caller
/// knows whether it is handling an upload, a tool result, or an export.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum ArtifactOrigin {
    /// Received from the user / channel (an upload, an attachment).
    Inbound,
    /// Produced by a tool during a run (a generated image, a rendered chart).
    Outbound,
    /// Generated by Aleph on demand (an exported session document).
    Export,
}

/// Immutable metadata for one stored artifact.
///
/// Persisted verbatim as the `<id>.json` sidecar and returned as-is over the
/// gateway, so the field names are wire-visible.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ArtifactRecord {
    /// UUID v4, lowercase hyphenated. Also the on-disk basename.
    pub id: String,
    /// Raw session key, e.g. `agent:main:main` (not the encoded directory).
    pub session_key: String,
    /// Run that produced it, when known.
    pub run_id: Option<String>,
    /// Who put it here.
    pub origin: ArtifactOrigin,
    /// Display name. Sanitized: never contains directory components.
    pub filename: String,
    /// MIME type as stamped by the call site, normalized.
    pub mime_type: String,
    /// Size of the blob in bytes.
    pub size: u64,
    /// Creation time, unix milliseconds.
    pub created_at: i64,
}

/// Errors from artifact store operations.
#[derive(Debug, thiserror::Error)]
pub enum ArtifactError {
    /// Payload is larger than [`MAX_ARTIFACT_BYTES`].
    #[error("artifact is {size} bytes, exceeding the {max} byte limit")]
    TooLarge { size: u64, max: u64 },

    /// The id is not a bare lowercase hyphenated UUID. Rejecting these is what
    /// keeps a client-supplied id from naming a path.
    #[error("invalid artifact id: {0}")]
    InvalidId(String),

    /// No artifact with that id under that session.
    #[error("artifact not found: {0}")]
    NotFound(String),

    /// Sidecar could not be encoded or decoded.
    #[error("artifact metadata error: {0}")]
    Metadata(#[from] serde_json::Error),

    /// Filesystem failure.
    #[error("artifact I/O error: {0}")]
    Io(#[from] std::io::Error),

    /// The Aleph data directory could not be resolved.
    #[error("cannot resolve artifact root: {0}")]
    Root(String),
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn encode_session_key_escapes_windows_illegal_chars() {
        let encoded = encode_session_key("agent:main:main");
        assert_eq!(encoded, "agent%3Amain%3Amain");
        assert!(!encoded.contains(':'), "colon is illegal on Windows");
    }

    #[test]
    fn encode_session_key_cannot_produce_traversal() {
        assert_eq!(encode_session_key(".."), "%2E%2E");
        assert_eq!(encode_session_key("."), "%2E");
        assert_eq!(encode_session_key("a/../b"), "a%2F%2E%2E%2Fb");
        assert_eq!(encode_session_key("a\\b"), "a%5Cb");
    }

    #[test]
    fn encode_session_key_is_injective() {
        // '%' is escaped, so a key that looks like an encoding of another key
        // does not collide with it.
        assert_ne!(encode_session_key("a:b"), encode_session_key("a%3Ab"));
        assert_eq!(encode_session_key("a%3Ab"), "a%253Ab");
    }

    #[test]
    fn encode_session_key_handles_empty_key() {
        assert_eq!(encode_session_key(""), EMPTY_SESSION_DIR);
    }

    #[test]
    fn origin_serializes_lowercase() {
        assert_eq!(
            serde_json::to_string(&ArtifactOrigin::Outbound).unwrap(),
            "\"outbound\""
        );
        assert_eq!(
            serde_json::from_str::<ArtifactOrigin>("\"export\"").unwrap(),
            ArtifactOrigin::Export
        );
    }
}
