import XCTest
@testable import AlephBridge

/// The `input.*` wire format, checked against the Rust contract snapshot
/// (`Fixtures/schema.json`, regenerated by `just bridge-schema`).
///
/// This is the ONLY guard on that wire. A Params struct that misspells a key, or
/// a Result that stops emitting one, compiles cleanly on BOTH sides and fails at
/// RUNTIME: the helper would answer `-32602` to a request Rust considers
/// well-formed, or Rust would silently drop a field the helper did send.
/// `GoldenFixturesTests` covers only the five JSON-RPC envelopes, and says so —
/// payload structs are validated "as their typed Swift structs are introduced".
/// The input rail's structs are those.
final class InputWireFormatTests: XCTestCase {

    // MARK: - The Rust contract

    private static let schema: [String: Any] = {
        guard let url = Bundle.module.url(forResource: "schema", withExtension: "json", subdirectory: "Fixtures")
            ?? Bundle.module.url(forResource: "schema", withExtension: "json"),
            let data = try? Data(contentsOf: url),
            let obj = try? JSONSerialization.jsonObject(with: data) as? [String: Any] else {
            fatalError("schema.json not found/parseable; run `just bridge-schema`")
        }
        return obj
    }()

    /// Keys Swift emits that the Rust struct does not (yet) declare.
    ///
    /// `input.click` / `input.double_click` also report WHICH rung ran: an AX
    /// action on a named element, or a synthesized event at a coordinate. serde
    /// ignores unknown fields, so sending them is wire-safe today and Rust's
    /// `ClickResult` just drops them until it declares them. Allowlisted by name
    /// rather than waved through: any OTHER excess key is a typo, and a typo must
    /// fail here instead of at runtime.
    private static let additiveResultKeys: [String: Set<String>] = [
        "ClickResult": ["path", "matched"],
    ]

    private func schemaProps(_ type: String) -> Set<String> {
        guard let t = Self.schema[type] as? [String: Any],
              let p = t["properties"] as? [String: Any] else {
            XCTFail("schema.json has no properties for '\(type)'")
            return []
        }
        return Set(p.keys)
    }

    private func schemaRequired(_ type: String) -> Set<String> {
        guard let t = Self.schema[type] as? [String: Any] else { return [] }
        return Set((t["required"] as? [String]) ?? [])
    }

    private func jsonKeys<T: Encodable>(_ value: T) throws -> Set<String> {
        let data = try JSONEncoder().encode(value)
        guard let obj = try JSONSerialization.jsonObject(with: data) as? [String: Any] else {
            XCTFail("encoded value is not a JSON object")
            return []
        }
        return Set(obj.keys)
    }

    /// Every key Rust requires is emitted, and every key emitted is one Rust
    /// declares (modulo the documented additive set).
    private func assertResultMatchesContract<T: Encodable>(
        _ typeName: String,
        _ sample: T,
        file: StaticString = #filePath,
        line: UInt = #line
    ) throws {
        let emitted = try jsonKeys(sample)
        let declared = schemaProps(typeName)
        let additive = Self.additiveResultKeys[typeName] ?? []

        let missing = schemaRequired(typeName).subtracting(emitted)
        XCTAssertTrue(
            missing.isEmpty,
            "[\(typeName)] Rust requires \(missing.sorted()) but Swift does not emit it — "
                + "the Rust decode fails at runtime",
            file: file, line: line
        )
        let stray = emitted.subtracting(declared).subtracting(additive)
        XCTAssertTrue(
            stray.isEmpty,
            "[\(typeName)] Swift emits \(stray.sorted()), which Rust does not declare — "
                + "Rust drops it silently",
            file: file, line: line
        )
    }

    // MARK: - Results

    func testEveryResultMatchesTheRustContract() throws {
        try assertResultMatchesContract(
            "ClickResult",
            ClickResult(ok: true, delivery: DELIVERY_TARGETED, path: "synthetic", matched: nil)
        )
        try assertResultMatchesContract("TypeTextResult", TypeTextResult(ok: true, delivery: DELIVERY_TARGETED))
        try assertResultMatchesContract("KeyComboResult", KeyComboResult(ok: true, delivery: DELIVERY_TARGETED))
        try assertResultMatchesContract("ScrollResult", ScrollResult(ok: true, delivery: DELIVERY_TARGETED))
        try assertResultMatchesContract("DragResult", DragResult(ok: true, delivery: DELIVERY_TARGETED))
        try assertResultMatchesContract("HoverResult", HoverResult(ok: true, delivery: DELIVERY_TARGETED))
        try assertResultMatchesContract("MouseButtonResult", MouseButtonResult(ok: true, delivery: DELIVERY_TARGETED))
        try assertResultMatchesContract("KeyButtonResult", KeyButtonResult(ok: true, delivery: DELIVERY_TARGETED))
        try assertResultMatchesContract("CursorPositionResult", CursorPositionResult(x: 1, y: 2))
    }

    /// An AX-satisfied click carries the element it pressed. The extra keys are
    /// the allowlisted ones and nothing else.
    func testAnAccessibilityClickReportsTheElementItPressed() throws {
        let element = AxElement(
            role: "AXButton", title: "Send", value: nil,
            bounds: Region(x: 10, y: 20, width: 80, height: 24),
            pid: 4242, secure: false, enabled: true, settable: nil,
            actions: ["AXPress"], url: nil, children: []
        )
        let result = ClickResult(
            ok: true, delivery: DELIVERY_TARGETED, path: "accessibility", matched: element
        )
        try assertResultMatchesContract("ClickResult", result)
        XCTAssertEqual(try jsonKeys(result), ["ok", "delivery", "path", "matched"])
    }

    /// `delivery` is what tells the model whether its cursor was dragged away.
    ///
    /// Rust reads an ABSENT `delivery` as `"global"` (the pessimistic reading),
    /// and `MacOSScreen::ensure_targeted` then rejects the call. So a Result that
    /// silently stopped emitting it would not misreport the rail — it would break
    /// the targeted rail outright, at runtime, everywhere.
    func testEveryResultNamesTheRailThatRan() throws {
        XCTAssertTrue(try jsonKeys(ClickResult(ok: true, delivery: DELIVERY_TARGETED, path: "synthetic", matched: nil)).contains("delivery"))
        XCTAssertTrue(try jsonKeys(TypeTextResult(ok: true, delivery: DELIVERY_TARGETED)).contains("delivery"))
        XCTAssertTrue(try jsonKeys(KeyComboResult(ok: true, delivery: DELIVERY_TARGETED)).contains("delivery"))
        XCTAssertTrue(try jsonKeys(ScrollResult(ok: true, delivery: DELIVERY_TARGETED)).contains("delivery"))
        XCTAssertTrue(try jsonKeys(DragResult(ok: true, delivery: DELIVERY_TARGETED)).contains("delivery"))
        XCTAssertTrue(try jsonKeys(HoverResult(ok: true, delivery: DELIVERY_TARGETED)).contains("delivery"))
        XCTAssertTrue(try jsonKeys(MouseButtonResult(ok: true, delivery: DELIVERY_TARGETED)).contains("delivery"))
        XCTAssertTrue(try jsonKeys(KeyButtonResult(ok: true, delivery: DELIVERY_TARGETED)).contains("delivery"))
        // The string itself is the contract (`input::DELIVERY_TARGETED`).
        XCTAssertEqual(DELIVERY_TARGETED, "targeted")
    }

    // MARK: - Params (decode exactly what Rust serialises)

    /// Rust omits a `None` field entirely (`skip_serializing_if`), so the minimal
    /// payload is what the global-rail caller and any older Rust build produce.
    func testClickParamsDecodeWhatRustSends() throws {
        let full = try JSONDecoder().decode(
            ClickParams.self,
            from: Data(#"{"x":1.5,"y":2.5,"button":"left","pid":4242,"click_count":2}"#.utf8)
        )
        XCTAssertEqual(full.x, 1.5)
        XCTAssertEqual(full.y, 2.5)
        XCTAssertEqual(full.button, .left)
        XCTAssertEqual(full.pid, 4242)
        XCTAssertEqual(full.click_count, 2)

        let minimal = try JSONDecoder().decode(
            ClickParams.self,
            from: Data(#"{"x":1.0,"y":2.0,"button":"middle"}"#.utf8)
        )
        XCTAssertNil(minimal.pid)
        XCTAssertNil(minimal.click_count)
        XCTAssertEqual(minimal.button, .middle)
    }

    func testMouseButtonParamsDecodeEveryPressAction() throws {
        for (wire, expected) in [("press", PressAction.press), ("release", .release), ("click", .click)] {
            let p = try JSONDecoder().decode(
                MouseButtonParams.self,
                from: Data(#"{"x":3.0,"y":4.0,"button":"right","action":"\#(wire)","pid":7}"#.utf8)
            )
            XCTAssertEqual(p.action, expected)
            XCTAssertEqual(p.button, .right)
            XCTAssertEqual(p.pid, 7)
        }
    }

    /// The point is optional on the wire (the global rail scrolls at the real
    /// cursor) and mandatory on this rail — `InputSession.scroll` rejects its
    /// absence rather than scrolling somewhere arbitrary. Both shapes must DECODE.
    func testScrollParamsDecodeWithAndWithoutThePoint() throws {
        let aimed = try JSONDecoder().decode(
            ScrollParams.self,
            from: Data(#"{"direction":"down","amount":3,"pid":99,"x":400.0,"y":300.0}"#.utf8)
        )
        XCTAssertEqual(aimed.x, 400)
        XCTAssertEqual(aimed.y, 300)
        XCTAssertEqual(aimed.amount, 3)

        let unaimed = try JSONDecoder().decode(
            ScrollParams.self,
            from: Data(#"{"direction":"up","amount":1}"#.utf8)
        )
        XCTAssertNil(unaimed.x)
        XCTAssertNil(unaimed.y)
        XCTAssertNil(unaimed.pid)
    }

    func testDragTypeTextHoverAndKeyComboParamsDecodeWhatRustSends() throws {
        let drag = try JSONDecoder().decode(
            DragParams.self,
            from: Data(#"{"start_x":1.0,"start_y":2.0,"end_x":3.0,"end_y":4.0,"duration_ms":250,"pid":5}"#.utf8)
        )
        XCTAssertEqual(drag.start_x, 1)
        XCTAssertEqual(drag.end_y, 4)
        XCTAssertEqual(drag.duration_ms, 250)

        let dragMinimal = try JSONDecoder().decode(
            DragParams.self,
            from: Data(#"{"start_x":0.0,"start_y":0.0,"end_x":9.0,"end_y":9.0}"#.utf8)
        )
        XCTAssertNil(dragMinimal.duration_ms)
        XCTAssertNil(dragMinimal.pid)

        let text = try JSONDecoder().decode(
            TypeTextParams.self, from: Data(#"{"text":"héllo 🌍","pid":11}"#.utf8)
        )
        XCTAssertEqual(text.text, "héllo 🌍")

        let hover = try JSONDecoder().decode(
            HoverParams.self, from: Data(#"{"x":8.0,"y":9.0,"pid":12}"#.utf8)
        )
        XCTAssertEqual(hover.pid, 12)

        let combo = try JSONDecoder().decode(
            KeyComboParams.self, from: Data(#"{"modifiers":["cmd","shift"],"key":"s","pid":13}"#.utf8)
        )
        XCTAssertEqual(combo.modifiers, ["cmd", "shift"])
        XCTAssertEqual(combo.key, "s")
    }

    /// `key_button` mixes modifiers and ordinary keys in ONE array — unlike
    /// `key_combo`, which splits them. That shape is the contract, because the
    /// whole chord goes down (or up) together.
    func testKeyButtonParamsDecodeAChordAndEveryPressAction() throws {
        for (wire, expected) in [("press", PressAction.press), ("release", .release), ("click", .click)] {
            let p = try JSONDecoder().decode(
                KeyButtonParams.self,
                from: Data(#"{"keys":["cmd","shift","a"],"action":"\#(wire)","pid":21}"#.utf8)
            )
            XCTAssertEqual(p.keys, ["cmd", "shift", "a"])
            XCTAssertEqual(p.action, expected)
            XCTAssertEqual(p.pid, 21)
        }

        // Rust omits a `None` pid; the helper must still decode, and then refuse
        // in `requirePid` rather than silently taking the global tap.
        let unaimed = try JSONDecoder().decode(
            KeyButtonParams.self, from: Data(#"{"keys":["escape"],"action":"click"}"#.utf8)
        )
        XCTAssertNil(unaimed.pid)
    }

    // MARK: - Pure helpers

    /// A key name must mean the same thing on both rails, or the model would have
    /// to know which rail it is on. These aliases are `key_parse.rs`'s, verbatim.
    func testKeyAndModifierVocabularyMatchesTheGlobalRail() {
        XCTAssertEqual(virtualKeyCode(for: "return"), virtualKeyCode(for: "enter"))
        XCTAssertEqual(virtualKeyCode(for: "escape"), virtualKeyCode(for: "esc"))
        XCTAssertEqual(virtualKeyCode(for: "delete"), virtualKeyCode(for: "del"))
        XCTAssertEqual(virtualKeyCode(for: "up"), virtualKeyCode(for: "uparrow"))
        XCTAssertEqual(virtualKeyCode(for: "down"), virtualKeyCode(for: "downarrow"))
        XCTAssertEqual(virtualKeyCode(for: "left"), virtualKeyCode(for: "leftarrow"))
        XCTAssertEqual(virtualKeyCode(for: "right"), virtualKeyCode(for: "rightarrow"))
        XCTAssertEqual(virtualKeyCode(for: "Z"), virtualKeyCode(for: "z"))
        XCTAssertNotNil(virtualKeyCode(for: "f12"))
        XCTAssertNotNil(virtualKeyCode(for: "space"))
        XCTAssertNil(virtualKeyCode(for: "nonexistent"))

        for alias in ["meta", "command", "cmd", "super", "win"] {
            XCTAssertEqual(modifierKey(for: alias)?.flag, .maskCommand, "alias '\(alias)'")
        }
        XCTAssertEqual(modifierKey(for: "ctrl")?.flag, modifierKey(for: "control")?.flag)
        XCTAssertEqual(modifierKey(for: "alt")?.flag, modifierKey(for: "option")?.flag)
        XCTAssertEqual(modifierKey(for: "SHIFT")?.flag, .maskShift)
        XCTAssertNil(modifierKey(for: "capslock"))
    }

    /// KNOWN DIVERGENCE, pinned so it is visible rather than surprising.
    ///
    /// The global rail's `parse_key` maps ANY single character to
    /// `Key::Unicode(ch)`, so `key_combo(["cmd"], "+")` works there. This rail
    /// looks the character up in a fixed ANSI table — a key combo is POSITIONAL,
    /// and a shifted or non-ANSI character has no unshifted key code — so it
    /// returns nil and the handler answers `-32602`. It fails CLOSED (a clear
    /// error the model can act on), never by pressing a different key. Widening
    /// the table would mean inferring a ⇧ on the model's behalf.
    func testTargetedRailRejectsShiftedAndNonAnsiKeysInsteadOfGuessing() {
        XCTAssertNil(virtualKeyCode(for: "+"), "'+' is ⇧= on ANSI; pressing '=' would be a different key")
        XCTAssertNil(virtualKeyCode(for: "?"))
        XCTAssertNil(virtualKeyCode(for: "中"))
        // The unshifted characters those are typed with ARE in the table.
        XCTAssertNotNil(virtualKeyCode(for: "="))
        XCTAssertNotNil(virtualKeyCode(for: "/"))
    }

    /// The AX rung may only stand in for the click the approval gate judged, so
    /// the element has to contain the literal point. Edges count as inside — a
    /// click on a button's border is a click on the button.
    func testBoundsContainIsInclusiveOfEdges() {
        let b = Region(x: 10, y: 20, width: 100, height: 50)
        XCTAssertTrue(boundsContain(b, x: 10, y: 20))
        XCTAssertTrue(boundsContain(b, x: 110, y: 70))
        XCTAssertTrue(boundsContain(b, x: 60, y: 45))
        XCTAssertFalse(boundsContain(b, x: 9.9, y: 45))
        XCTAssertFalse(boundsContain(b, x: 60, y: 70.1))
    }

    /// Smallest box containing the point is the most specific control there (the
    /// button, not the toolbar holding it). Ties break toward the shallower node
    /// so the choice does not depend on AX child order.
    func testRankClickCandidatesPrefersTheSmallestThenTheShallowest() {
        XCTAssertNil(rankClickCandidates([]))
        XCTAssertEqual(
            rankClickCandidates([
                (area: 10_000, depth: 0, index: 0), // the window
                (area: 2_000, depth: 1, index: 1),  // the toolbar
                (area: 240, depth: 2, index: 2),    // the button
            ]),
            2
        )
        XCTAssertEqual(
            rankClickCandidates([
                (area: 240, depth: 3, index: 0),
                (area: 240, depth: 1, index: 1),
            ]),
            1
        )
    }

    /// `keyboardSetUnicodeString` takes a UTF-16 buffer. Splitting mid-grapheme
    /// delivers mojibake, so a cluster is never cut — even one that alone exceeds
    /// the chunk budget.
    func testChunkForUnicodeEventsNeverSplitsAGrapheme() {
        XCTAssertEqual(chunkForUnicodeEvents("", maxUTF16: 4), [])
        XCTAssertEqual(chunkForUnicodeEvents("abc", maxUTF16: 64), ["abc"])
        XCTAssertEqual(chunkForUnicodeEvents("abcdef", maxUTF16: 2), ["ab", "cd", "ef"])

        // A family emoji is one grapheme of many UTF-16 units.
        let family = "👨‍👩‍👧‍👦"
        XCTAssertGreaterThan(family.utf16.count, 4)
        let chunks = chunkForUnicodeEvents(family, maxUTF16: 4)
        XCTAssertEqual(chunks, [family], "an oversized grapheme is kept whole, never halved")

        let mixed = chunkForUnicodeEvents("a\(family)b", maxUTF16: 4)
        XCTAssertEqual(mixed.joined(), "a\(family)b")
        for chunk in mixed {
            XCTAssertFalse(chunk.unicodeScalars.isEmpty)
        }
    }

    /// A fixed role/action table, never a read of the element's title (R7/P8).
    /// Middle-click has no AX equivalent, so it always synthesizes.
    func testAxStandInActionsAreAFixedTable() {
        XCTAssertEqual(axActionsStandingInForClick(.left), ["AXPress", "AXConfirm", "AXOpen"])
        XCTAssertEqual(axActionsStandingInForClick(.right), ["AXShowMenu"])
        XCTAssertTrue(axActionsStandingInForClick(.middle).isEmpty)
    }
}
