pub mod agent_identity;
pub mod composer;
pub mod context_gauge;
pub mod events;
pub mod list_scroll;
pub mod mention_palette;
pub mod messages;
pub mod plan;
pub mod project_menu;
pub mod reasoning;
pub mod state;
pub mod team_compose;
pub mod team_events;
pub mod team_task_logic;
pub mod timeline;
mod todo_panel;
pub mod transcript;
pub mod view;
pub mod voice_playback;

pub use state::ChatState;
pub use todo_panel::TodoPanel;
pub use view::ChatView;
