//! SkillGenerator - generates SKILL.md files from suggestions.
//!
//! Creates properly formatted skill files with frontmatter and instructions.

use std::fs;
use std::path::{Path, PathBuf};

use tracing::info;

use crate::error::{AetherError, Result};

use super::types::{GenerationResult, SolidificationSuggestion};

/// SKILL.md template
const SKILL_TEMPLATE: &str = r#"---
name: {name}
description: {description}
allowed-tools: []
triggers:
{triggers}
---

{instructions}

---

*Auto-generated by Aether Skill Evolution System*
*Pattern ID: {pattern_id}*
*Confidence: {confidence:.0}%*
"#;

/// Generator for skill files
pub struct SkillGenerator {
    /// Directory where skills are stored
    skills_dir: PathBuf,
}

impl SkillGenerator {
    /// Create a new generator with the given skills directory
    pub fn new(skills_dir: impl Into<PathBuf>) -> Self {
        Self {
            skills_dir: skills_dir.into(),
        }
    }

    /// Create with default skills directory (~/.aether/skills)
    pub fn with_default_dir() -> Result<Self> {
        let home = dirs::home_dir().ok_or_else(|| AetherError::Other {
            message: "Could not determine home directory".to_string(),
            suggestion: None,
        })?;
        let skills_dir = home.join(".aether").join("skills");
        Ok(Self::new(skills_dir))
    }

    /// Generate a skill from a suggestion
    pub fn generate(&self, suggestion: &SolidificationSuggestion) -> Result<GenerationResult> {
        let skill_dir = self.skills_dir.join(&suggestion.suggested_name);

        // Check if skill already exists
        if skill_dir.exists() {
            info!(skill_id = %suggestion.suggested_name, "Skill already exists");
            return Ok(GenerationResult::AlreadyExists {
                skill_id: suggestion.suggested_name.clone(),
            });
        }

        // Generate triggers from sample contexts
        let triggers = suggestion
            .sample_contexts
            .iter()
            .take(3)
            .map(|ctx| {
                // Extract first few words as trigger
                let words: Vec<&str> = ctx.split_whitespace().take(2).collect();
                format!("  - {}", words.join(" "))
            })
            .collect::<Vec<_>>()
            .join("\n");

        // Generate SKILL.md content
        let content = SKILL_TEMPLATE
            .replace("{name}", &suggestion.suggested_name)
            .replace("{description}", &suggestion.suggested_description)
            .replace("{triggers}", &triggers)
            .replace("{instructions}", &suggestion.instructions_preview)
            .replace("{pattern_id}", &suggestion.pattern_id)
            .replace(
                "{confidence:.0}",
                &format!("{:.0}", suggestion.confidence * 100.0),
            );

        // Create directory
        fs::create_dir_all(&skill_dir).map_err(|e| AetherError::Other {
            message: format!("Failed to create skill directory: {}", e),
            suggestion: None,
        })?;

        // Write SKILL.md
        let file_path = skill_dir.join("SKILL.md");
        fs::write(&file_path, &content).map_err(|e| AetherError::Other {
            message: format!("Failed to write SKILL.md: {}", e),
            suggestion: None,
        })?;

        info!(
            skill_id = %suggestion.suggested_name,
            path = %file_path.display(),
            "Generated skill"
        );

        // Generate diff preview
        let diff_preview = format!(
            "+++ {}\n@@ -0,0 +1,{} @@\n{}",
            file_path.display(),
            content.lines().count(),
            content
                .lines()
                .map(|l| format!("+{}", l))
                .collect::<Vec<_>>()
                .join("\n")
        );

        Ok(GenerationResult::Generated {
            skill_id: suggestion.suggested_name.clone(),
            file_path: file_path.to_string_lossy().to_string(),
            diff_preview,
        })
    }

    /// Preview what would be generated (without writing)
    pub fn preview(&self, suggestion: &SolidificationSuggestion) -> String {
        let triggers = suggestion
            .sample_contexts
            .iter()
            .take(3)
            .map(|ctx| {
                let words: Vec<&str> = ctx.split_whitespace().take(2).collect();
                format!("  - {}", words.join(" "))
            })
            .collect::<Vec<_>>()
            .join("\n");

        SKILL_TEMPLATE
            .replace("{name}", &suggestion.suggested_name)
            .replace("{description}", &suggestion.suggested_description)
            .replace("{triggers}", &triggers)
            .replace("{instructions}", &suggestion.instructions_preview)
            .replace("{pattern_id}", &suggestion.pattern_id)
            .replace(
                "{confidence:.0}",
                &format!("{:.0}", suggestion.confidence * 100.0),
            )
    }

    /// Get the path where a skill would be created
    pub fn get_skill_path(&self, name: &str) -> PathBuf {
        self.skills_dir.join(name).join("SKILL.md")
    }

    /// Get the skills directory
    pub fn skills_dir(&self) -> &Path {
        &self.skills_dir
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    fn test_suggestion() -> SolidificationSuggestion {
        SolidificationSuggestion {
            pattern_id: "pattern-123".to_string(),
            suggested_name: "test-skill".to_string(),
            suggested_description: "A test skill".to_string(),
            confidence: 0.9,
            metrics: super::super::SkillMetrics::new("test"),
            sample_contexts: vec!["refactor code".to_string(), "improve tests".to_string()],
            instructions_preview: "# Test Skill\n\nDo the thing.".to_string(),
        }
    }

    #[test]
    fn test_generate_skill() {
        let dir = TempDir::new().unwrap();
        let generator = SkillGenerator::new(dir.path());
        let suggestion = test_suggestion();

        let result = generator.generate(&suggestion).unwrap();
        match result {
            GenerationResult::Generated {
                skill_id,
                file_path,
                ..
            } => {
                assert_eq!(skill_id, "test-skill");
                assert!(Path::new(&file_path).exists());
            }
            _ => panic!("Expected Generated result"),
        }
    }

    #[test]
    fn test_generate_existing() {
        let dir = TempDir::new().unwrap();
        let generator = SkillGenerator::new(dir.path());
        let suggestion = test_suggestion();

        // Generate first time
        generator.generate(&suggestion).unwrap();

        // Try to generate again
        let result = generator.generate(&suggestion).unwrap();
        match result {
            GenerationResult::AlreadyExists { skill_id } => {
                assert_eq!(skill_id, "test-skill");
            }
            _ => panic!("Expected AlreadyExists result"),
        }
    }

    #[test]
    fn test_preview() {
        let dir = TempDir::new().unwrap();
        let generator = SkillGenerator::new(dir.path());
        let suggestion = test_suggestion();

        let preview = generator.preview(&suggestion);
        assert!(preview.contains("name: test-skill"));
        assert!(preview.contains("A test skill"));
        assert!(preview.contains("# Test Skill"));
    }
}
