//! GitCommitter - auto-commits generated skills to git.
//!
//! Handles staging, committing, and optionally pushing skill changes.

use std::path::Path;
use std::process::Command;

use tracing::{debug, info, warn};

use crate::error::{AetherError, Result};

use super::types::CommitResult;

/// Git operations for skill evolution
pub struct GitCommitter {
    /// Repository root directory
    repo_root: String,
    /// Whether to auto-push after commit
    auto_push: bool,
    /// Remote name for push (default: origin)
    remote: String,
    /// Branch name for push (default: main)
    branch: String,
}

impl GitCommitter {
    /// Create a new committer for the given repository
    pub fn new(repo_root: impl Into<String>) -> Self {
        Self {
            repo_root: repo_root.into(),
            auto_push: false,
            remote: "origin".to_string(),
            branch: "main".to_string(),
        }
    }

    /// Enable auto-push after commit
    pub fn with_auto_push(mut self, enabled: bool) -> Self {
        self.auto_push = enabled;
        self
    }

    /// Set remote for push
    pub fn with_remote(mut self, remote: impl Into<String>) -> Self {
        self.remote = remote.into();
        self
    }

    /// Set branch for push
    pub fn with_branch(mut self, branch: impl Into<String>) -> Self {
        self.branch = branch.into();
        self
    }

    /// Commit a generated skill
    pub fn commit_skill(&self, skill_path: &str, skill_name: &str) -> Result<CommitResult> {
        // Check if path exists
        if !Path::new(skill_path).exists() {
            return Ok(CommitResult::Failed {
                reason: format!("Skill path does not exist: {}", skill_path),
            });
        }

        // Check if we're in a git repo
        if !self.is_git_repo() {
            return Ok(CommitResult::Failed {
                reason: "Not a git repository".to_string(),
            });
        }

        // Stage the skill directory
        let skill_dir = Path::new(skill_path)
            .parent()
            .unwrap_or(Path::new(skill_path));
        let stage_result = self.run_git(&["add", &skill_dir.to_string_lossy()]);
        if let Err(e) = stage_result {
            return Ok(CommitResult::Failed {
                reason: format!("Failed to stage: {}", e),
            });
        }

        // Check if there are changes to commit
        let status = self.run_git(&["status", "--porcelain"]);
        match status {
            Ok(output) if output.trim().is_empty() => {
                debug!("No changes to commit");
                return Ok(CommitResult::NothingToCommit);
            }
            Err(e) => {
                return Ok(CommitResult::Failed {
                    reason: format!("Failed to check status: {}", e),
                });
            }
            _ => {}
        }

        // Commit
        let message = format!(
            "feat(skills): auto-generate {} skill\n\nGenerated by Aether Skill Evolution System",
            skill_name
        );
        let commit_result = self.run_git(&["commit", "-m", &message]);
        match commit_result {
            Ok(_) => {}
            Err(e) => {
                return Ok(CommitResult::Failed {
                    reason: format!("Failed to commit: {}", e),
                });
            }
        }

        // Get commit hash
        let hash = self
            .run_git(&["rev-parse", "HEAD"])
            .unwrap_or_else(|_| "unknown".to_string())
            .trim()
            .to_string();

        info!(
            skill = %skill_name,
            commit = %hash,
            "Committed skill"
        );

        // Auto-push if enabled
        if self.auto_push {
            match self.push() {
                Ok(_) => info!("Pushed to {}/{}", self.remote, self.branch),
                Err(e) => warn!("Failed to push: {}", e),
            }
        }

        Ok(CommitResult::Committed {
            commit_hash: hash,
            files_changed: vec![skill_path.to_string()],
        })
    }

    /// Push to remote
    pub fn push(&self) -> Result<()> {
        self.run_git(&["push", &self.remote, &self.branch])?;
        Ok(())
    }

    /// Check if current directory is a git repo
    fn is_git_repo(&self) -> bool {
        self.run_git(&["rev-parse", "--git-dir"]).is_ok()
    }

    /// Run a git command
    fn run_git(&self, args: &[&str]) -> Result<String> {
        let output = Command::new("git")
            .args(args)
            .current_dir(&self.repo_root)
            .output()
            .map_err(|e| AetherError::Other {
                message: format!("Failed to run git: {}", e),
                suggestion: Some("Ensure git is installed".to_string()),
            })?;

        if output.status.success() {
            Ok(String::from_utf8_lossy(&output.stdout).to_string())
        } else {
            Err(AetherError::Other {
                message: format!(
                    "Git command failed: {}",
                    String::from_utf8_lossy(&output.stderr)
                ),
                suggestion: None,
            })
        }
    }

    /// Get the repo root
    pub fn repo_root(&self) -> &str {
        &self.repo_root
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use tempfile::TempDir;

    fn setup_git_repo() -> TempDir {
        let dir = TempDir::new().unwrap();

        // Initialize git repo
        Command::new("git")
            .args(["init"])
            .current_dir(dir.path())
            .output()
            .unwrap();

        // Configure git user (required for commits)
        Command::new("git")
            .args(["config", "user.email", "test@test.com"])
            .current_dir(dir.path())
            .output()
            .unwrap();
        Command::new("git")
            .args(["config", "user.name", "Test"])
            .current_dir(dir.path())
            .output()
            .unwrap();

        // Create initial commit
        fs::write(dir.path().join("README.md"), "# Test").unwrap();
        Command::new("git")
            .args(["add", "."])
            .current_dir(dir.path())
            .output()
            .unwrap();
        Command::new("git")
            .args(["commit", "-m", "Initial"])
            .current_dir(dir.path())
            .output()
            .unwrap();

        dir
    }

    #[test]
    fn test_commit_skill() {
        let dir = setup_git_repo();
        let committer = GitCommitter::new(dir.path().to_string_lossy().to_string());

        // Create a skill file
        let skill_dir = dir.path().join("skills").join("test-skill");
        fs::create_dir_all(&skill_dir).unwrap();
        let skill_path = skill_dir.join("SKILL.md");
        fs::write(&skill_path, "# Test Skill").unwrap();

        let result = committer
            .commit_skill(&skill_path.to_string_lossy(), "test-skill")
            .unwrap();

        match result {
            CommitResult::Committed {
                commit_hash,
                files_changed,
            } => {
                assert!(!commit_hash.is_empty());
                assert_eq!(files_changed.len(), 1);
            }
            _ => panic!("Expected Committed result"),
        }
    }

    #[test]
    fn test_nothing_to_commit() {
        let dir = setup_git_repo();
        let committer = GitCommitter::new(dir.path().to_string_lossy().to_string());

        // Use existing committed file
        let readme_path = dir.path().join("README.md");

        let result = committer
            .commit_skill(&readme_path.to_string_lossy(), "readme")
            .unwrap();

        match result {
            CommitResult::NothingToCommit => {}
            _ => panic!("Expected NothingToCommit"),
        }
    }

    #[test]
    fn test_not_a_repo() {
        let dir = TempDir::new().unwrap();
        let committer = GitCommitter::new(dir.path().to_string_lossy().to_string());

        // Create a file (not in git repo)
        let file_path = dir.path().join("test.txt");
        fs::write(&file_path, "test").unwrap();

        let result = committer
            .commit_skill(&file_path.to_string_lossy(), "test")
            .unwrap();

        match result {
            CommitResult::Failed { reason } => {
                assert!(reason.contains("Not a git repository"));
            }
            _ => panic!("Expected Failed result"),
        }
    }
}
