//! Sub-manifest generator for recursive POE decomposition.
//!
//! Generates child `SuccessManifest` instances from a parent manifest
//! and a set of sub-objectives, either via simple splitting or LLM-assisted
//! constraint distribution.

use crate::sync_primitives::Arc;

use crate::agents::thinking::ThinkLevel;
use crate::error::Result;
use crate::poe::types::SuccessManifest;
use crate::providers::AiProvider;
use crate::utils::json_extract::extract_json_robust;
use tracing::warn;

/// System prompt for LLM-based sub-manifest generation.
const SUB_MANIFEST_SYSTEM_PROMPT: &str = r#"You are splitting a parent task into sub-tasks.

Given a parent SuccessManifest and a list of sub-objectives, distribute the parent's
hard_constraints among the sub-objectives. Each constraint should go to the sub-objective
it most logically belongs to. Constraints that don't clearly belong to any sub-objective
should be placed in the last sub-task.

## Output Format

Output ONLY valid JSON — an array of objects:

```json
[
  {
    "task_id": "parent-id-sub-0",
    "objective": "sub-objective text",
    "hard_constraints": [ ... subset of parent constraints ... ],
    "soft_metrics": [],
    "max_attempts": 5
  }
]
```

Each element must be a valid SuccessManifest. Output ONLY the JSON array, no markdown."#;

/// Generator for creating sub-manifests from a parent manifest.
pub struct SubManifestGenerator;

impl SubManifestGenerator {
    /// Generate sub-manifests from sub-objectives using LLM to distribute constraints.
    ///
    /// Falls back to `generate_simple` if LLM call or parsing fails.
    pub async fn generate(
        parent: &SuccessManifest,
        sub_objectives: &[String],
        provider: &Arc<dyn AiProvider>,
    ) -> Result<Vec<SuccessManifest>> {
        if sub_objectives.is_empty() {
            return Ok(Vec::new());
        }

        // Build prompt with parent manifest and sub-objectives
        let parent_json = serde_json::to_string_pretty(parent).unwrap_or_default();
        let objectives_list = sub_objectives
            .iter()
            .enumerate()
            .map(|(i, o)| format!("{}. {}", i, o))
            .collect::<Vec<_>>()
            .join("\n");

        let prompt = format!(
            "## Parent Manifest\n\n```json\n{}\n```\n\n## Sub-Objectives\n\n{}\n\n\
             Split the parent's constraints among these sub-objectives. \
             Use task_id format: \"{}-sub-{{index}}\".",
            parent_json, objectives_list, parent.task_id
        );

        let response = match provider
            .process_with_thinking(&prompt, Some(SUB_MANIFEST_SYSTEM_PROMPT), ThinkLevel::Low)
            .await
        {
            Ok(r) => r,
            Err(e) => {
                warn!(
                    "LLM call failed for sub-manifest generation: {}, falling back to simple",
                    e
                );
                return Ok(Self::generate_simple(parent, sub_objectives));
            }
        };

        // Try to parse the LLM response as an array of manifests
        match Self::parse_sub_manifests(&response) {
            Some(manifests) if manifests.len() == sub_objectives.len() => Ok(manifests),
            Some(manifests) => {
                warn!(
                    "LLM returned {} manifests but expected {}, falling back to simple",
                    manifests.len(),
                    sub_objectives.len()
                );
                // If count doesn't match, fall back
                Ok(Self::generate_simple(parent, sub_objectives))
            }
            None => {
                warn!("Failed to parse LLM sub-manifest response, falling back to simple");
                Ok(Self::generate_simple(parent, sub_objectives))
            }
        }
    }

    /// Create sub-manifests from explicit sub-objectives without LLM.
    ///
    /// Each sub-manifest gets:
    /// - `task_id`: `{parent.task_id}-sub-{index}`
    /// - `objective`: the sub-objective text
    /// - `max_attempts`: inherited from parent
    /// - No hard_constraints (to be generated by ManifestBuilder later)
    pub fn generate_simple(
        parent: &SuccessManifest,
        sub_objectives: &[String],
    ) -> Vec<SuccessManifest> {
        sub_objectives
            .iter()
            .enumerate()
            .map(|(i, objective)| {
                SuccessManifest::new(
                    format!("{}-sub-{}", parent.task_id, i),
                    objective.as_str(),
                )
                .with_max_attempts(parent.max_attempts)
            })
            .collect()
    }

    /// Parse the LLM response into a vector of SuccessManifests.
    fn parse_sub_manifests(response: &str) -> Option<Vec<SuccessManifest>> {
        let json_value = extract_json_robust(response)?;

        // Handle both array and single-object responses
        if json_value.is_array() {
            serde_json::from_value(json_value).ok()
        } else {
            // Single manifest wrapped in array
            let manifest: SuccessManifest = serde_json::from_value(json_value).ok()?;
            Some(vec![manifest])
        }
    }
}

// ============================================================================
// Tests
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generate_simple_creates_correct_count() {
        let parent = SuccessManifest::new("parent-1", "Parent objective");
        let subs = vec![
            "Sub task A".to_string(),
            "Sub task B".to_string(),
            "Sub task C".to_string(),
        ];

        let result = SubManifestGenerator::generate_simple(&parent, &subs);
        assert_eq!(result.len(), 3);
    }

    #[test]
    fn sub_manifest_task_ids_inherit_parent_prefix() {
        let parent = SuccessManifest::new("my-task", "Parent objective");
        let subs = vec!["First".to_string(), "Second".to_string()];

        let result = SubManifestGenerator::generate_simple(&parent, &subs);
        assert_eq!(result[0].task_id, "my-task-sub-0");
        assert_eq!(result[1].task_id, "my-task-sub-1");
    }

    #[test]
    fn generate_simple_preserves_max_attempts() {
        let parent = SuccessManifest::new("p", "Parent").with_max_attempts(10);
        let subs = vec!["Child".to_string()];

        let result = SubManifestGenerator::generate_simple(&parent, &subs);
        assert_eq!(result[0].max_attempts, 10);
    }

    #[test]
    fn empty_sub_objectives_returns_empty() {
        let parent = SuccessManifest::new("p", "Parent");
        let subs: Vec<String> = vec![];

        let result = SubManifestGenerator::generate_simple(&parent, &subs);
        assert!(result.is_empty());
    }

    #[test]
    fn generate_simple_has_no_constraints() {
        let parent = SuccessManifest::new("p", "Parent")
            .with_hard_constraint(crate::poe::types::ValidationRule::FileExists {
                path: std::path::PathBuf::from("test.txt"),
            });

        let subs = vec!["Child task".to_string()];
        let result = SubManifestGenerator::generate_simple(&parent, &subs);

        assert!(result[0].hard_constraints.is_empty());
        assert!(result[0].soft_metrics.is_empty());
    }

    #[test]
    fn sub_manifest_objectives_match_input() {
        let parent = SuccessManifest::new("p", "Parent");
        let subs = vec![
            "Implement authentication".to_string(),
            "Write unit tests".to_string(),
        ];

        let result = SubManifestGenerator::generate_simple(&parent, &subs);
        assert_eq!(result[0].objective, "Implement authentication");
        assert_eq!(result[1].objective, "Write unit tests");
    }
}
