//! Authentication Handlers
//!
//! Handles device authentication, pairing, and connection management.

use serde::{Deserialize, Serialize};
use serde_json::{json, Value};
use std::sync::Arc;
use tracing::{debug, info, warn};

use crate::gateway::device_store::{ApprovedDevice, DeviceStore};
use crate::gateway::protocol::{JsonRpcRequest, JsonRpcResponse, AUTH_FAILED, INVALID_PARAMS};
use crate::gateway::security::{DeviceRole, DeviceType, PairingManager, PairingRequest, TokenManager};
use crate::gateway::ClientManifest;

use crate::gateway::security::SecurityStore;

/// Parameters for the "hello" method (server -> client notification)
#[derive(Debug, Clone, Serialize)]
pub struct HelloParams {
    /// Protocol version
    pub version: String,
    /// Server name
    pub server: String,
    /// Whether authentication is required
    pub auth_required: bool,
}

/// Parameters for the "connect" method
#[derive(Debug, Clone, Deserialize)]
pub struct ConnectParams {
    /// Device token (for returning devices)
    pub token: Option<String>,
    /// Device name (for new devices)
    pub device_name: Option<String>,
    /// Device type (macos, ios, android, cli, web)
    pub device_type: Option<String>,
    /// Unique device identifier (generated by client)
    pub device_id: Option<String>,
    /// Client capability manifest for Server-Client mode
    pub manifest: Option<ClientManifest>,
}

/// Result of a successful connection
#[derive(Debug, Clone, Serialize)]
pub struct ConnectResult {
    /// Session token for this connection
    pub token: String,
    /// Device ID
    pub device_id: String,
    /// Permissions granted
    pub permissions: Vec<String>,
    /// Token expiry time (ISO 8601)
    pub expires_at: String,
    /// Server acknowledges manifest was received
    pub manifest_accepted: bool,
}

/// Pairing required notification
#[derive(Debug, Clone, Serialize)]
pub struct PairingRequiredParams {
    /// 8-character Base32 pairing code
    pub code: String,
    /// Seconds until code expires
    pub expires_in: u64,
    /// Instructions for user
    pub message: String,
}

/// Authentication context for handlers
pub struct AuthContext {
    pub token_manager: Arc<TokenManager>,
    pub pairing_manager: Arc<PairingManager>,
    pub device_store: Arc<DeviceStore>,
    pub security_store: Arc<SecurityStore>,
    pub require_auth: bool,
}

impl AuthContext {
    /// Create a new authentication context
    pub fn new(
        token_manager: Arc<TokenManager>,
        pairing_manager: Arc<PairingManager>,
        device_store: Arc<DeviceStore>,
        security_store: Arc<SecurityStore>,
        require_auth: bool,
    ) -> Self {
        Self {
            token_manager,
            pairing_manager,
            device_store,
            security_store,
            require_auth,
        }
    }
}

/// Handle "connect" request
///
/// This is the main authentication endpoint. Clients must call this
/// before any other methods when auth is required.
pub async fn handle_connect(
    request: JsonRpcRequest,
    ctx: Arc<AuthContext>,
) -> JsonRpcResponse {
    // Parse parameters
    let params: ConnectParams = match &request.params {
        Some(Value::Object(map)) => match serde_json::from_value(Value::Object(map.clone())) {
            Ok(p) => p,
            Err(e) => {
                return JsonRpcResponse::error(
                    request.id,
                    INVALID_PARAMS,
                    format!("Invalid connect params: {}", e),
                );
            }
        },
        _ => ConnectParams {
            token: None,
            device_name: None,
            device_type: None,
            device_id: None,
            manifest: None,
        },
    };

    // If authentication is not required, allow any connection
    if !ctx.require_auth {
        let device_id = params
            .device_id
            .unwrap_or_else(|| uuid::Uuid::new_v4().to_string());

        // Register device in SecurityStore first (required for FK constraint on tokens)
        let device_name = params.device_name.as_deref().unwrap_or("Auto-Device");
        if let Err(e) = ctx.security_store.upsert_device(
            &device_id,
            device_name,
            None,
            &[0u8; 32], // Placeholder public key
            &device_id[..16.min(device_id.len())], // Use prefix as fingerprint
            DeviceRole::Operator.as_str(),
            &["*".to_string()],
        ) {
            warn!(error = %e, "Failed to register device");
            return JsonRpcResponse::error(request.id, -32603, format!("Failed to register device: {}", e));
        }

        let signed_token = match ctx
            .token_manager
            .issue_token(&device_id, DeviceRole::Operator, vec!["*".to_string()])
        {
            Ok(t) => t,
            Err(e) => {
                warn!(error = %e, "Failed to issue token");
                return JsonRpcResponse::error(request.id, -32603, format!("Failed to issue token: {}", e));
            }
        };

        info!(device_id = %device_id, "Connection accepted (auth not required)");

        // Check if manifest was provided
        let manifest_accepted = params.manifest.is_some();
        if let Some(ref manifest) = params.manifest {
            tracing::info!(
                client_type = %manifest.client_type,
                client_version = %manifest.client_version,
                tool_categories = ?manifest.capabilities.tool_categories,
                "Client manifest received"
            );
        }

        return JsonRpcResponse::success(
            request.id,
            json!(ConnectResult {
                token: format!("{}:{}", signed_token.token, signed_token.signature),
                device_id,
                permissions: vec!["*".to_string()],
                expires_at: chrono::DateTime::from_timestamp_millis(signed_token.expires_at)
                    .map(|dt| dt.to_rfc3339())
                    .unwrap_or_else(|| (chrono::Utc::now() + chrono::Duration::hours(24)).to_rfc3339()),
                manifest_accepted,
            }),
        );
    }

    // Case 1: Client has a token - validate it
    if let Some(token_str) = &params.token {
        // Token format: "{token}:{signature}"
        if let Some((token, signature)) = token_str.split_once(':') {
            match ctx.token_manager.validate_token(token, signature) {
                Ok(validation) => {
                    let device_id = params
                        .device_id
                        .unwrap_or_else(|| validation.device_id.clone());

                    // Update last seen time if device is in store
                    let _ = ctx.device_store.update_last_seen(&device_id);

                    info!(device_id = %device_id, "Connection authenticated via token");

                    // Check if manifest was provided
                    let manifest_accepted = params.manifest.is_some();
                    if let Some(ref manifest) = params.manifest {
                        tracing::info!(
                            client_type = %manifest.client_type,
                            client_version = %manifest.client_version,
                            tool_categories = ?manifest.capabilities.tool_categories,
                            "Client manifest received"
                        );
                    }

                    return JsonRpcResponse::success(
                        request.id,
                        json!(ConnectResult {
                            token: token_str.clone(),
                            device_id,
                            permissions: validation.scopes,
                            expires_at: chrono::DateTime::from_timestamp_millis(
                                chrono::Utc::now().timestamp_millis() + validation.remaining_ms
                            )
                            .map(|dt| dt.to_rfc3339())
                            .unwrap_or_else(|| (chrono::Utc::now() + chrono::Duration::hours(24)).to_rfc3339()),
                            manifest_accepted,
                        }),
                    );
                }
                Err(e) => {
                    debug!(error = %e, "Invalid token provided");
                    // Token invalid, fall through to pairing
                }
            }
        } else {
            debug!("Invalid token format (expected token:signature)");
            // Token invalid, fall through to pairing
        }
    }

    // Case 2: Check if device_id is already approved
    if let Some(device_id) = &params.device_id {
        if ctx.device_store.is_approved(device_id) {
            // Device is approved, generate new token
            let device = ctx.device_store.get_device(device_id);
            let permissions = device
                .as_ref()
                .map(|d| d.permissions.clone())
                .unwrap_or_else(|| vec!["*".to_string()]);

            let signed_token = match ctx
                .token_manager
                .issue_token(device_id, DeviceRole::Operator, permissions.clone())
            {
                Ok(t) => t,
                Err(e) => {
                    warn!(error = %e, "Failed to issue token");
                    return JsonRpcResponse::error(request.id, -32603, format!("Failed to issue token: {}", e));
                }
            };

            // Update last seen
            let _ = ctx.device_store.update_last_seen(device_id);

            info!(device_id = %device_id, "Connection authenticated via approved device");

            // Check if manifest was provided
            let manifest_accepted = params.manifest.is_some();
            if let Some(ref manifest) = params.manifest {
                tracing::info!(
                    client_type = %manifest.client_type,
                    client_version = %manifest.client_version,
                    tool_categories = ?manifest.capabilities.tool_categories,
                    "Client manifest received"
                );
            }

            return JsonRpcResponse::success(
                request.id,
                json!(ConnectResult {
                    token: format!("{}:{}", signed_token.token, signed_token.signature),
                    device_id: device_id.clone(),
                    permissions,
                    expires_at: chrono::DateTime::from_timestamp_millis(signed_token.expires_at)
                        .map(|dt| dt.to_rfc3339())
                        .unwrap_or_else(|| (chrono::Utc::now() + chrono::Duration::hours(24)).to_rfc3339()),
                    manifest_accepted,
                }),
            );
        }
    }

    // Case 3: New device - initiate pairing
    let device_name = params
        .device_name
        .unwrap_or_else(|| "Unknown Device".to_string());
    let _device_type = params.device_type;
    let _device_id = params
        .device_id
        .unwrap_or_else(|| uuid::Uuid::new_v4().to_string());

    // Check if there's already a pending pairing for this device
    // (to prevent spamming pairing requests)
    let pending = match ctx.pairing_manager.list_pending() {
        Ok(p) => p,
        Err(e) => {
            warn!(error = %e, "Failed to list pending pairings");
            return JsonRpcResponse::error(request.id, -32603, format!("Failed to list pending pairings: {}", e));
        }
    };

    // Find existing device pairing by name
    if let Some(existing) = pending.iter().find(|req| {
        matches!(req, PairingRequest::Device { device_name: name, .. } if name == &device_name)
    }) {
        let code = existing.code();
        let remaining = existing.remaining_secs();
        info!(
            device_name = %device_name,
            code = %code,
            "Returning existing pairing code"
        );

        return JsonRpcResponse::error_with_data(
            request.id,
            AUTH_FAILED,
            "pairing_required",
            json!(PairingRequiredParams {
                code: code.to_string(),
                expires_in: remaining,
                message: format!(
                    "Enter code {} to approve this device, or run: aleph-gateway pairing approve {}",
                    code, code
                ),
            }),
        );
    }

    // Initiate new pairing (device pairing without public key for now - legacy compatibility)
    // In a full Ed25519 implementation, the client would provide a public key
    let pairing_request = match ctx.pairing_manager.request_device_pairing(
        device_name.clone(),
        None, // device_type parsed as DeviceType
        vec![0u8; 32], // placeholder public key for legacy API
        None, // remote_addr
    ) {
        Ok(req) => req,
        Err(e) => {
            warn!(error = %e, "Failed to initiate pairing");
            return JsonRpcResponse::error(request.id, -32603, format!("Failed to initiate pairing: {}", e));
        }
    };

    let code = pairing_request.code().to_string();
    let expires_in = pairing_request.remaining_secs();

    info!(
        device_name = %device_name,
        code = %code,
        "Pairing initiated"
    );

    JsonRpcResponse::error_with_data(
        request.id,
        AUTH_FAILED,
        "pairing_required",
        json!(PairingRequiredParams {
            code: code.clone(),
            expires_in,
            message: format!(
                "Enter code {} to approve this device, or run: aleph-gateway pairing approve {}",
                code, code
            ),
        }),
    )
}

/// Handle "pairing.approve" request (from authorized client or CLI)
pub async fn handle_pairing_approve(
    request: JsonRpcRequest,
    ctx: Arc<AuthContext>,
) -> JsonRpcResponse {
    #[derive(Debug, Deserialize)]
    struct ApproveParams {
        code: String,
    }

    let params: ApproveParams = match &request.params {
        Some(Value::Object(map)) => match serde_json::from_value(Value::Object(map.clone())) {
            Ok(p) => p,
            Err(e) => {
                return JsonRpcResponse::error(
                    request.id,
                    INVALID_PARAMS,
                    format!("Invalid params: {}", e),
                );
            }
        },
        _ => {
            return JsonRpcResponse::error(request.id, INVALID_PARAMS, "Missing params");
        }
    };

    // Confirm pairing (removes from pending and returns the request)
    let pairing_request = match ctx.pairing_manager.confirm_pairing(&params.code) {
        Ok(req) => req,
        Err(e) => {
            warn!(code = %params.code, error = %e, "Invalid or expired pairing code");
            return JsonRpcResponse::error(request.id, AUTH_FAILED, "Invalid or expired pairing code");
        }
    };

    // Extract device info from pairing request
    let (device_name, device_type): (String, Option<String>) = match &pairing_request {
        PairingRequest::Device { device_name, device_type, .. } => {
            (device_name.clone(), device_type.map(|t: DeviceType| t.as_str().to_string()))
        }
        PairingRequest::Channel { channel, sender_id, .. } => {
            // Channel pairing approved - approve the sender via SecurityStore
            if let Err(e) = ctx.security_store.approve_sender(channel, sender_id) {
                warn!(error = %e, "Failed to approve sender");
                return JsonRpcResponse::error(request.id, -32603, format!("Failed to approve sender: {}", e));
            }
            info!(channel = %channel, sender_id = %sender_id, "Channel sender approved");
            return JsonRpcResponse::success(request.id, json!({
                "channel": channel,
                "sender_id": sender_id,
                "approved": true,
            }));
        }
    };

    // Generate device ID and create approved device
    let device_id = uuid::Uuid::new_v4().to_string();
    let device = ApprovedDevice::new(
        device_id.clone(),
        device_name.clone(),
        device_type,
    );

    // Store in device store
    if let Err(e) = ctx.device_store.approve_device(&device) {
        warn!(error = %e, "Failed to store approved device");
        return JsonRpcResponse::error(
            request.id,
            -32603,
            format!("Failed to store device: {}", e),
        );
    }

    // Register device in SecurityStore for token FK constraint
    if let Err(e) = ctx.security_store.upsert_device(
        &device_id,
        &device_name,
        None,
        &[0u8; 32], // placeholder public key
        &device_id[..16], // use device_id prefix as fingerprint
        "operator",
        &["*".to_string()],
    ) {
        warn!(error = %e, "Failed to register device in security store");
        return JsonRpcResponse::error(
            request.id,
            -32603,
            format!("Failed to register device: {}", e),
        );
    }

    // Generate token for the new device
    let signed_token = match ctx
        .token_manager
        .issue_token(&device_id, DeviceRole::Operator, vec!["*".to_string()])
    {
        Ok(t) => t,
        Err(e) => {
            warn!(error = %e, "Failed to issue token");
            return JsonRpcResponse::error(request.id, -32603, format!("Failed to issue token: {}", e));
        }
    };

    info!(
        device_id = %device_id,
        device_name = %device_name,
        "Device pairing approved"
    );

    JsonRpcResponse::success(
        request.id,
        json!({
            "device_id": device_id,
            "device_name": device_name,
            "token": format!("{}:{}", signed_token.token, signed_token.signature),
            "approved_at": device.approved_at,
        }),
    )
}

/// Handle "pairing.reject" request
pub async fn handle_pairing_reject(
    request: JsonRpcRequest,
    ctx: Arc<AuthContext>,
) -> JsonRpcResponse {
    #[derive(Debug, Deserialize)]
    struct RejectParams {
        code: String,
    }

    let params: RejectParams = match &request.params {
        Some(Value::Object(map)) => match serde_json::from_value(Value::Object(map.clone())) {
            Ok(p) => p,
            Err(e) => {
                return JsonRpcResponse::error(
                    request.id,
                    INVALID_PARAMS,
                    format!("Invalid params: {}", e),
                );
            }
        },
        _ => {
            return JsonRpcResponse::error(request.id, INVALID_PARAMS, "Missing params");
        }
    };

    match ctx.pairing_manager.cancel_pairing(&params.code) {
        Ok(true) => {
            info!(code = %params.code, "Pairing rejected");
            JsonRpcResponse::success(request.id, json!({"rejected": true}))
        }
        Ok(false) => {
            JsonRpcResponse::error(request.id, AUTH_FAILED, "Invalid or expired pairing code")
        }
        Err(e) => {
            warn!(error = %e, "Failed to cancel pairing");
            JsonRpcResponse::error(request.id, -32603, format!("Failed to cancel pairing: {}", e))
        }
    }
}

/// Handle "pairing.list" request
pub async fn handle_pairing_list(
    request: JsonRpcRequest,
    ctx: Arc<AuthContext>,
) -> JsonRpcResponse {
    let pending = match ctx.pairing_manager.list_pending() {
        Ok(p) => p,
        Err(e) => {
            warn!(error = %e, "Failed to list pending pairings");
            return JsonRpcResponse::error(request.id, -32603, format!("Failed to list pending pairings: {}", e));
        }
    };

    let items: Vec<Value> = pending
        .into_iter()
        .map(|req| {
            match req {
                PairingRequest::Device { code, device_name, device_type, expires_at, created_at, .. } => {
                    let remaining = if expires_at > created_at {
                        let now = std::time::SystemTime::now()
                            .duration_since(std::time::UNIX_EPOCH)
                            .unwrap()
                            .as_millis() as i64;
                        if expires_at > now {
                            ((expires_at - now) / 1000) as u64
                        } else {
                            0
                        }
                    } else {
                        0
                    };
                    json!({
                        "type": "device",
                        "code": code,
                        "device_name": device_name,
                        "device_type": device_type.map(|t: DeviceType| t.as_str()),
                        "expires_in": remaining,
                    })
                }
                PairingRequest::Channel { code, channel, sender_id, expires_at, created_at, .. } => {
                    let remaining = if expires_at > created_at {
                        let now = std::time::SystemTime::now()
                            .duration_since(std::time::UNIX_EPOCH)
                            .unwrap()
                            .as_millis() as i64;
                        if expires_at > now {
                            ((expires_at - now) / 1000) as u64
                        } else {
                            0
                        }
                    } else {
                        0
                    };
                    json!({
                        "type": "channel",
                        "code": code,
                        "channel": channel,
                        "sender_id": sender_id,
                        "expires_in": remaining,
                    })
                }
            }
        })
        .collect();

    JsonRpcResponse::success(request.id, json!({"pending": items}))
}

/// Handle "devices.list" request
pub async fn handle_devices_list(
    request: JsonRpcRequest,
    ctx: Arc<AuthContext>,
) -> JsonRpcResponse {
    let devices = ctx.device_store.list_devices();

    let items: Vec<Value> = devices
        .into_iter()
        .map(|d| {
            json!({
                "device_id": d.device_id,
                "device_name": d.device_name,
                "device_type": d.device_type,
                "approved_at": d.approved_at,
                "last_seen_at": d.last_seen_at,
                "permissions": d.permissions,
            })
        })
        .collect();

    JsonRpcResponse::success(request.id, json!({"devices": items}))
}

/// Handle "devices.revoke" request
pub async fn handle_devices_revoke(
    request: JsonRpcRequest,
    ctx: Arc<AuthContext>,
) -> JsonRpcResponse {
    #[derive(Debug, Deserialize)]
    struct RevokeParams {
        device_id: String,
    }

    let params: RevokeParams = match &request.params {
        Some(Value::Object(map)) => match serde_json::from_value(Value::Object(map.clone())) {
            Ok(p) => p,
            Err(e) => {
                return JsonRpcResponse::error(
                    request.id,
                    INVALID_PARAMS,
                    format!("Invalid params: {}", e),
                );
            }
        },
        _ => {
            return JsonRpcResponse::error(request.id, INVALID_PARAMS, "Missing params");
        }
    };

    // Revoke device from store
    match ctx.device_store.revoke_device(&params.device_id) {
        Ok(true) => {
            // Also revoke any tokens for this device
            if let Err(e) = ctx.token_manager.revoke_device_tokens(&params.device_id) {
                warn!(error = %e, "Failed to revoke device tokens");
            }

            info!(device_id = %params.device_id, "Device revoked");
            JsonRpcResponse::success(request.id, json!({"revoked": true}))
        }
        Ok(false) => {
            JsonRpcResponse::error(request.id, -32004, "Device not found")
        }
        Err(e) => {
            JsonRpcResponse::error(request.id, -32603, format!("Failed to revoke: {}", e))
        }
    }
}

/// Create a "hello" notification to send to newly connected clients
pub fn create_hello_notification(require_auth: bool) -> JsonRpcRequest {
    JsonRpcRequest::notification(
        "hello",
        Some(json!(HelloParams {
            version: "1".to_string(),
            server: format!("aleph-gateway/{}", env!("CARGO_PKG_VERSION")),
            auth_required: require_auth,
        })),
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    fn create_test_context() -> Arc<AuthContext> {
        let store = Arc::new(SecurityStore::in_memory().unwrap());
        // Create a device for token tests
        store
            .upsert_device("test-dev", "Test", None, &[1u8; 32], "fp", "operator", &[])
            .unwrap();
        Arc::new(AuthContext::new(
            Arc::new(TokenManager::new(store.clone())),
            Arc::new(PairingManager::new(store.clone())),
            Arc::new(DeviceStore::in_memory().unwrap()),
            store,
            true,
        ))
    }

    #[tokio::test]
    async fn test_connect_no_auth_required() {
        let store = Arc::new(SecurityStore::in_memory().unwrap());
        // Create a device for token tests
        store
            .upsert_device("test-dev", "Test", None, &[1u8; 32], "fp", "operator", &[])
            .unwrap();
        let ctx = Arc::new(AuthContext::new(
            Arc::new(TokenManager::new(store.clone())),
            Arc::new(PairingManager::new(store.clone())),
            Arc::new(DeviceStore::in_memory().unwrap()),
            store,
            false, // Auth not required
        ));

        let request = JsonRpcRequest::new(
            "connect",
            Some(json!({"device_name": "Test Device"})),
            Some(json!(1)),
        );

        let response = handle_connect(request, ctx).await;
        assert!(response.is_success());

        let result = response.result.unwrap();
        assert!(result.get("token").is_some());
        assert!(result.get("device_id").is_some());
    }

    #[tokio::test]
    async fn test_connect_requires_pairing() {
        let ctx = create_test_context();

        let request = JsonRpcRequest::new(
            "connect",
            Some(json!({
                "device_name": "New Device",
                "device_type": "macos"
            })),
            Some(json!(1)),
        );

        let response = handle_connect(request, ctx).await;
        assert!(response.is_error());

        let error = response.error.unwrap();
        assert_eq!(error.message, "pairing_required");
        assert!(error.data.is_some());

        let data = error.data.unwrap();
        assert!(data.get("code").is_some());
    }

    #[tokio::test]
    async fn test_pairing_flow() {
        let ctx = create_test_context();

        // Step 1: Try to connect (should get pairing code)
        let connect_req = JsonRpcRequest::new(
            "connect",
            Some(json!({"device_name": "Test Device"})),
            Some(json!(1)),
        );
        let connect_resp = handle_connect(connect_req, ctx.clone()).await;
        let code = connect_resp
            .error
            .unwrap()
            .data
            .unwrap()
            .get("code")
            .unwrap()
            .as_str()
            .unwrap()
            .to_string();

        // Step 2: Approve pairing
        let approve_req = JsonRpcRequest::new(
            "pairing.approve",
            Some(json!({"code": code})),
            Some(json!(2)),
        );
        let approve_resp = handle_pairing_approve(approve_req, ctx.clone()).await;
        assert!(approve_resp.is_success());

        let result = approve_resp.result.unwrap();
        let device_id = result.get("device_id").unwrap().as_str().unwrap();

        // Step 3: Connect with approved device_id
        let reconnect_req = JsonRpcRequest::new(
            "connect",
            Some(json!({"device_id": device_id})),
            Some(json!(3)),
        );
        let reconnect_resp = handle_connect(reconnect_req, ctx).await;
        assert!(reconnect_resp.is_success());
    }

    #[tokio::test]
    async fn test_devices_list() {
        let ctx = create_test_context();

        // Add a device
        ctx.device_store
            .approve_device(&ApprovedDevice::new(
                "test-device".to_string(),
                "Test Device".to_string(),
                Some("macos".to_string()),
            ))
            .unwrap();

        let request = JsonRpcRequest::with_id("devices.list", None, json!(1));
        let response = handle_devices_list(request, ctx).await;

        assert!(response.is_success());
        let result = response.result.unwrap();
        let devices = result.get("devices").unwrap().as_array().unwrap();
        assert_eq!(devices.len(), 1);
    }
}
