//! Authentication Handlers
//!
//! Handles device authentication, pairing, and connection management.

use serde::{Deserialize, Serialize};
use serde_json::{json, Value};
use std::sync::Arc;
use tracing::{debug, info, warn};

use crate::gateway::device_store::{ApprovedDevice, DeviceStore};
use crate::gateway::protocol::{JsonRpcRequest, JsonRpcResponse, AUTH_FAILED, INVALID_PARAMS};
use crate::gateway::security::{DeviceRole, PairingManager, TokenManager};

#[cfg(test)]
use crate::gateway::security::SecurityStore;

/// Parameters for the "hello" method (server -> client notification)
#[derive(Debug, Clone, Serialize)]
pub struct HelloParams {
    /// Protocol version
    pub version: String,
    /// Server name
    pub server: String,
    /// Whether authentication is required
    pub auth_required: bool,
}

/// Parameters for the "connect" method
#[derive(Debug, Clone, Deserialize)]
pub struct ConnectParams {
    /// Device token (for returning devices)
    pub token: Option<String>,
    /// Device name (for new devices)
    pub device_name: Option<String>,
    /// Device type (macos, ios, android, cli, web)
    pub device_type: Option<String>,
    /// Unique device identifier (generated by client)
    pub device_id: Option<String>,
}

/// Result of a successful connection
#[derive(Debug, Clone, Serialize)]
pub struct ConnectResult {
    /// Session token for this connection
    pub token: String,
    /// Device ID
    pub device_id: String,
    /// Permissions granted
    pub permissions: Vec<String>,
    /// Token expiry time (ISO 8601)
    pub expires_at: String,
}

/// Pairing required notification
#[derive(Debug, Clone, Serialize)]
pub struct PairingRequiredParams {
    /// 6-digit pairing code
    pub code: String,
    /// Seconds until code expires
    pub expires_in: u64,
    /// Instructions for user
    pub message: String,
}

/// Authentication context for handlers
pub struct AuthContext {
    pub token_manager: Arc<TokenManager>,
    pub pairing_manager: Arc<PairingManager>,
    pub device_store: Arc<DeviceStore>,
    pub require_auth: bool,
}

impl AuthContext {
    /// Create a new authentication context
    pub fn new(
        token_manager: Arc<TokenManager>,
        pairing_manager: Arc<PairingManager>,
        device_store: Arc<DeviceStore>,
        require_auth: bool,
    ) -> Self {
        Self {
            token_manager,
            pairing_manager,
            device_store,
            require_auth,
        }
    }
}

/// Handle "connect" request
///
/// This is the main authentication endpoint. Clients must call this
/// before any other methods when auth is required.
pub async fn handle_connect(
    request: JsonRpcRequest,
    ctx: Arc<AuthContext>,
) -> JsonRpcResponse {
    // Parse parameters
    let params: ConnectParams = match &request.params {
        Some(Value::Object(map)) => match serde_json::from_value(Value::Object(map.clone())) {
            Ok(p) => p,
            Err(e) => {
                return JsonRpcResponse::error(
                    request.id,
                    INVALID_PARAMS,
                    format!("Invalid connect params: {}", e),
                );
            }
        },
        _ => ConnectParams {
            token: None,
            device_name: None,
            device_type: None,
            device_id: None,
        },
    };

    // If authentication is not required, allow any connection
    if !ctx.require_auth {
        let device_id = params
            .device_id
            .unwrap_or_else(|| uuid::Uuid::new_v4().to_string());

        let signed_token = match ctx
            .token_manager
            .issue_token(&device_id, DeviceRole::Operator, vec!["*".to_string()])
        {
            Ok(t) => t,
            Err(e) => {
                warn!(error = %e, "Failed to issue token");
                return JsonRpcResponse::error(request.id, -32603, format!("Failed to issue token: {}", e));
            }
        };

        info!(device_id = %device_id, "Connection accepted (auth not required)");

        return JsonRpcResponse::success(
            request.id,
            json!(ConnectResult {
                token: format!("{}:{}", signed_token.token, signed_token.signature),
                device_id,
                permissions: vec!["*".to_string()],
                expires_at: chrono::DateTime::from_timestamp_millis(signed_token.expires_at)
                    .map(|dt| dt.to_rfc3339())
                    .unwrap_or_else(|| (chrono::Utc::now() + chrono::Duration::hours(24)).to_rfc3339()),
            }),
        );
    }

    // Case 1: Client has a token - validate it
    if let Some(token_str) = &params.token {
        // Token format: "{token}:{signature}"
        if let Some((token, signature)) = token_str.split_once(':') {
            match ctx.token_manager.validate_token(token, signature) {
                Ok(validation) => {
                    let device_id = params
                        .device_id
                        .unwrap_or_else(|| validation.device_id.clone());

                    // Update last seen time if device is in store
                    let _ = ctx.device_store.update_last_seen(&device_id);

                    info!(device_id = %device_id, "Connection authenticated via token");

                    return JsonRpcResponse::success(
                        request.id,
                        json!(ConnectResult {
                            token: token_str.clone(),
                            device_id,
                            permissions: validation.scopes,
                            expires_at: chrono::DateTime::from_timestamp_millis(
                                chrono::Utc::now().timestamp_millis() + validation.remaining_ms
                            )
                            .map(|dt| dt.to_rfc3339())
                            .unwrap_or_else(|| (chrono::Utc::now() + chrono::Duration::hours(24)).to_rfc3339()),
                        }),
                    );
                }
                Err(e) => {
                    debug!(error = %e, "Invalid token provided");
                    // Token invalid, fall through to pairing
                }
            }
        } else {
            debug!("Invalid token format (expected token:signature)");
            // Token invalid, fall through to pairing
        }
    }

    // Case 2: Check if device_id is already approved
    if let Some(device_id) = &params.device_id {
        if ctx.device_store.is_approved(device_id) {
            // Device is approved, generate new token
            let device = ctx.device_store.get_device(device_id);
            let permissions = device
                .as_ref()
                .map(|d| d.permissions.clone())
                .unwrap_or_else(|| vec!["*".to_string()]);

            let signed_token = match ctx
                .token_manager
                .issue_token(device_id, DeviceRole::Operator, permissions.clone())
            {
                Ok(t) => t,
                Err(e) => {
                    warn!(error = %e, "Failed to issue token");
                    return JsonRpcResponse::error(request.id, -32603, format!("Failed to issue token: {}", e));
                }
            };

            // Update last seen
            let _ = ctx.device_store.update_last_seen(device_id);

            info!(device_id = %device_id, "Connection authenticated via approved device");

            return JsonRpcResponse::success(
                request.id,
                json!(ConnectResult {
                    token: format!("{}:{}", signed_token.token, signed_token.signature),
                    device_id: device_id.clone(),
                    permissions,
                    expires_at: chrono::DateTime::from_timestamp_millis(signed_token.expires_at)
                        .map(|dt| dt.to_rfc3339())
                        .unwrap_or_else(|| (chrono::Utc::now() + chrono::Duration::hours(24)).to_rfc3339()),
                }),
            );
        }
    }

    // Case 3: New device - initiate pairing
    let device_name = params
        .device_name
        .unwrap_or_else(|| "Unknown Device".to_string());
    let device_type = params.device_type;
    let device_id = params
        .device_id
        .unwrap_or_else(|| uuid::Uuid::new_v4().to_string());

    // Check if there's already a pending pairing for this device
    // (to prevent spamming pairing requests)
    let pending = ctx.pairing_manager.list_pending().await;
    if let Some(existing) = pending.iter().find(|(_, name, _)| name == &device_name) {
        info!(
            device_name = %device_name,
            code = %existing.0,
            "Returning existing pairing code"
        );

        return JsonRpcResponse::error_with_data(
            request.id,
            AUTH_FAILED,
            "pairing_required",
            json!(PairingRequiredParams {
                code: existing.0.clone(),
                expires_in: existing.2,
                message: format!(
                    "Enter code {} to approve this device, or run: aether-gateway pairing approve {}",
                    existing.0, existing.0
                ),
            }),
        );
    }

    // Initiate new pairing
    let code = ctx
        .pairing_manager
        .initiate_pairing_with_info(device_name.clone(), device_type.clone(), Some(device_id.clone()))
        .await;

    info!(
        device_name = %device_name,
        device_id = %device_id,
        code = %code,
        "Pairing initiated"
    );

    JsonRpcResponse::error_with_data(
        request.id,
        AUTH_FAILED,
        "pairing_required",
        json!(PairingRequiredParams {
            code: code.clone(),
            expires_in: 300, // 5 minutes
            message: format!(
                "Enter code {} to approve this device, or run: aether-gateway pairing approve {}",
                code, code
            ),
        }),
    )
}

/// Handle "pairing.approve" request (from authorized client or CLI)
pub async fn handle_pairing_approve(
    request: JsonRpcRequest,
    ctx: Arc<AuthContext>,
) -> JsonRpcResponse {
    #[derive(Debug, Deserialize)]
    struct ApproveParams {
        code: String,
    }

    let params: ApproveParams = match &request.params {
        Some(Value::Object(map)) => match serde_json::from_value(Value::Object(map.clone())) {
            Ok(p) => p,
            Err(e) => {
                return JsonRpcResponse::error(
                    request.id,
                    INVALID_PARAMS,
                    format!("Invalid params: {}", e),
                );
            }
        },
        _ => {
            return JsonRpcResponse::error(request.id, INVALID_PARAMS, "Missing params");
        }
    };

    // Get pairing info
    let pairing_info = match ctx.pairing_manager.get_pairing_info(&params.code).await {
        Some(info) => info,
        None => {
            warn!(code = %params.code, "Invalid or expired pairing code");
            return JsonRpcResponse::error(request.id, AUTH_FAILED, "Invalid or expired pairing code");
        }
    };

    // Confirm pairing (removes from pending)
    let device_name = match ctx.pairing_manager.confirm_pairing(&params.code).await {
        Some(name) => name,
        None => {
            return JsonRpcResponse::error(request.id, AUTH_FAILED, "Failed to confirm pairing");
        }
    };

    // Generate device ID and create approved device
    let device_id = uuid::Uuid::new_v4().to_string();
    let device = ApprovedDevice::new(
        device_id.clone(),
        device_name.clone(),
        pairing_info.device_type,
    );

    // Store in device store
    if let Err(e) = ctx.device_store.approve_device(&device) {
        warn!(error = %e, "Failed to store approved device");
        return JsonRpcResponse::error(
            request.id,
            -32603,
            format!("Failed to store device: {}", e),
        );
    }

    // Generate token for the new device
    let signed_token = match ctx
        .token_manager
        .issue_token(&device_id, DeviceRole::Operator, vec!["*".to_string()])
    {
        Ok(t) => t,
        Err(e) => {
            warn!(error = %e, "Failed to issue token");
            return JsonRpcResponse::error(request.id, -32603, format!("Failed to issue token: {}", e));
        }
    };

    info!(
        device_id = %device_id,
        device_name = %device_name,
        "Device pairing approved"
    );

    JsonRpcResponse::success(
        request.id,
        json!({
            "device_id": device_id,
            "device_name": device_name,
            "token": format!("{}:{}", signed_token.token, signed_token.signature),
            "approved_at": device.approved_at,
        }),
    )
}

/// Handle "pairing.reject" request
pub async fn handle_pairing_reject(
    request: JsonRpcRequest,
    ctx: Arc<AuthContext>,
) -> JsonRpcResponse {
    #[derive(Debug, Deserialize)]
    struct RejectParams {
        code: String,
    }

    let params: RejectParams = match &request.params {
        Some(Value::Object(map)) => match serde_json::from_value(Value::Object(map.clone())) {
            Ok(p) => p,
            Err(e) => {
                return JsonRpcResponse::error(
                    request.id,
                    INVALID_PARAMS,
                    format!("Invalid params: {}", e),
                );
            }
        },
        _ => {
            return JsonRpcResponse::error(request.id, INVALID_PARAMS, "Missing params");
        }
    };

    let cancelled = ctx.pairing_manager.cancel_pairing(&params.code).await;

    if cancelled {
        info!(code = %params.code, "Pairing rejected");
        JsonRpcResponse::success(request.id, json!({"rejected": true}))
    } else {
        JsonRpcResponse::error(request.id, AUTH_FAILED, "Invalid or expired pairing code")
    }
}

/// Handle "pairing.list" request
pub async fn handle_pairing_list(
    request: JsonRpcRequest,
    ctx: Arc<AuthContext>,
) -> JsonRpcResponse {
    let pending = ctx.pairing_manager.list_pending().await;

    let items: Vec<Value> = pending
        .into_iter()
        .map(|(code, device_name, remaining_secs)| {
            json!({
                "code": code,
                "device_name": device_name,
                "expires_in": remaining_secs,
            })
        })
        .collect();

    JsonRpcResponse::success(request.id, json!({"pending": items}))
}

/// Handle "devices.list" request
pub async fn handle_devices_list(
    request: JsonRpcRequest,
    ctx: Arc<AuthContext>,
) -> JsonRpcResponse {
    let devices = ctx.device_store.list_devices();

    let items: Vec<Value> = devices
        .into_iter()
        .map(|d| {
            json!({
                "device_id": d.device_id,
                "device_name": d.device_name,
                "device_type": d.device_type,
                "approved_at": d.approved_at,
                "last_seen_at": d.last_seen_at,
                "permissions": d.permissions,
            })
        })
        .collect();

    JsonRpcResponse::success(request.id, json!({"devices": items}))
}

/// Handle "devices.revoke" request
pub async fn handle_devices_revoke(
    request: JsonRpcRequest,
    ctx: Arc<AuthContext>,
) -> JsonRpcResponse {
    #[derive(Debug, Deserialize)]
    struct RevokeParams {
        device_id: String,
    }

    let params: RevokeParams = match &request.params {
        Some(Value::Object(map)) => match serde_json::from_value(Value::Object(map.clone())) {
            Ok(p) => p,
            Err(e) => {
                return JsonRpcResponse::error(
                    request.id,
                    INVALID_PARAMS,
                    format!("Invalid params: {}", e),
                );
            }
        },
        _ => {
            return JsonRpcResponse::error(request.id, INVALID_PARAMS, "Missing params");
        }
    };

    // Revoke device from store
    match ctx.device_store.revoke_device(&params.device_id) {
        Ok(true) => {
            // Also revoke any tokens for this device
            if let Err(e) = ctx.token_manager.revoke_device_tokens(&params.device_id) {
                warn!(error = %e, "Failed to revoke device tokens");
            }

            info!(device_id = %params.device_id, "Device revoked");
            JsonRpcResponse::success(request.id, json!({"revoked": true}))
        }
        Ok(false) => {
            JsonRpcResponse::error(request.id, -32004, "Device not found")
        }
        Err(e) => {
            JsonRpcResponse::error(request.id, -32603, format!("Failed to revoke: {}", e))
        }
    }
}

/// Create a "hello" notification to send to newly connected clients
pub fn create_hello_notification(require_auth: bool) -> JsonRpcRequest {
    JsonRpcRequest::notification(
        "hello",
        Some(json!(HelloParams {
            version: "1".to_string(),
            server: format!("aether-gateway/{}", env!("CARGO_PKG_VERSION")),
            auth_required: require_auth,
        })),
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    fn create_test_context() -> Arc<AuthContext> {
        let store = Arc::new(SecurityStore::in_memory().unwrap());
        // Create a device for token tests
        store
            .upsert_device("test-dev", "Test", None, &[1u8; 32], "fp", "operator", &[])
            .unwrap();
        Arc::new(AuthContext::new(
            Arc::new(TokenManager::new(store)),
            Arc::new(PairingManager::new()),
            Arc::new(DeviceStore::in_memory().unwrap()),
            true,
        ))
    }

    #[tokio::test]
    async fn test_connect_no_auth_required() {
        let store = Arc::new(SecurityStore::in_memory().unwrap());
        // Create a device for token tests
        store
            .upsert_device("test-dev", "Test", None, &[1u8; 32], "fp", "operator", &[])
            .unwrap();
        let ctx = Arc::new(AuthContext::new(
            Arc::new(TokenManager::new(store)),
            Arc::new(PairingManager::new()),
            Arc::new(DeviceStore::in_memory().unwrap()),
            false, // Auth not required
        ));

        let request = JsonRpcRequest::new(
            "connect",
            Some(json!({"device_name": "Test Device"})),
            Some(json!(1)),
        );

        let response = handle_connect(request, ctx).await;
        assert!(response.is_success());

        let result = response.result.unwrap();
        assert!(result.get("token").is_some());
        assert!(result.get("device_id").is_some());
    }

    #[tokio::test]
    async fn test_connect_requires_pairing() {
        let ctx = create_test_context();

        let request = JsonRpcRequest::new(
            "connect",
            Some(json!({
                "device_name": "New Device",
                "device_type": "macos"
            })),
            Some(json!(1)),
        );

        let response = handle_connect(request, ctx).await;
        assert!(response.is_error());

        let error = response.error.unwrap();
        assert_eq!(error.message, "pairing_required");
        assert!(error.data.is_some());

        let data = error.data.unwrap();
        assert!(data.get("code").is_some());
    }

    #[tokio::test]
    async fn test_pairing_flow() {
        let ctx = create_test_context();

        // Step 1: Try to connect (should get pairing code)
        let connect_req = JsonRpcRequest::new(
            "connect",
            Some(json!({"device_name": "Test Device"})),
            Some(json!(1)),
        );
        let connect_resp = handle_connect(connect_req, ctx.clone()).await;
        let code = connect_resp
            .error
            .unwrap()
            .data
            .unwrap()
            .get("code")
            .unwrap()
            .as_str()
            .unwrap()
            .to_string();

        // Step 2: Approve pairing
        let approve_req = JsonRpcRequest::new(
            "pairing.approve",
            Some(json!({"code": code})),
            Some(json!(2)),
        );
        let approve_resp = handle_pairing_approve(approve_req, ctx.clone()).await;
        assert!(approve_resp.is_success());

        let result = approve_resp.result.unwrap();
        let device_id = result.get("device_id").unwrap().as_str().unwrap();

        // Step 3: Connect with approved device_id
        let reconnect_req = JsonRpcRequest::new(
            "connect",
            Some(json!({"device_id": device_id})),
            Some(json!(3)),
        );
        let reconnect_resp = handle_connect(reconnect_req, ctx).await;
        assert!(reconnect_resp.is_success());
    }

    #[tokio::test]
    async fn test_devices_list() {
        let ctx = create_test_context();

        // Add a device
        ctx.device_store
            .approve_device(&ApprovedDevice::new(
                "test-device".to_string(),
                "Test Device".to_string(),
                Some("macos".to_string()),
            ))
            .unwrap();

        let request = JsonRpcRequest::new("devices.list", None, Some(json!(1)));
        let response = handle_devices_list(request, ctx).await;

        assert!(response.is_success());
        let result = response.result.unwrap();
        let devices = result.get("devices").unwrap().as_array().unwrap();
        assert_eq!(devices.len(), 1);
    }
}
