[package]
name = "aleph-desktop-macos"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
aleph-desktop = { path = "../desktop" }
async-trait = "0.1"
tokio = { version = "1", features = ["process"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tracing = "0.1"
