//! `DreamReport` for the dream pipeline.

use serde::{Deserialize, Serialize};

use crate::memory::dreaming::distill_action::DistillActionRecord;
use crate::memory::dreaming::evolution::EvolutionOutcome;

/// Status of a completed dream pipeline run.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
#[derive(Default)]
pub enum DreamReportStatus {
    #[default]
    Completed,
    Interrupted,
    Failed,
}

/// Report generated by dream pipeline execution.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct DreamReport {
    pub pipeline_type: String,
    pub started_at: i64,
    pub finished_at: i64,
    pub duration_ms: u64,
    pub notes_consolidated: u32,
    pub contradictions_found: u32,
    pub notes_marked_stale: u32,
    pub synthesis_count: u32,
    pub format_fixed: u32,
    pub broken_links_found: u32,
    pub links_repaired: u32,
    pub links_purged: u32,
    pub notes_archived: u32,
    pub notes_protected: u32,
    /// Orphan notes successfully woven into the link graph by `NoteWeave`.
    #[serde(default)]
    pub notes_woven: u32,
    /// Goal lessons promoted into long-term notes by `GoalLessonsPromoteStage`.
    #[serde(default)]
    pub goal_lessons_promoted: u32,
    pub errors: Option<String>,
    /// Per-action provenance produced by the `SkillDistill` and
    /// `FeedbackDistill` stages. Preserves which `DistillAction` variant
    /// fired, against which candidate, and the apply outcome — the layer
    /// previously collapsed into a single `*_distill_count` counter.
    ///
    /// `#[serde(default)]` keeps the existing `dream_events.jsonl` (which
    /// pre-dates this field) deserializable without a migration.
    #[serde(default)]
    pub distill_actions: Vec<DistillActionRecord>,
    /// Note pairs merged this cycle (keeper, absorbed). Drained into
    /// `MutationGate::record_merge_pair` after the pipeline runs so the
    /// churn-detection subsystem actually receives data (it previously never
    /// did — the recorders had no callers).
    #[serde(default)]
    pub merged_pairs: Vec<(String, String)>,
    /// Synthesis assertions written this cycle. Drained into
    /// `MutationGate::record_synthesis_assertion` for oscillation detection.
    #[serde(default)]
    pub synthesis_assertions: Vec<String>,
    /// Mature skill-note cohort size (created more than `MATURE_SKILL_DAYS`
    /// ago) — the denominator of MutationGate's wasted-distillation ratio. Same
    /// cohort as `distill_recalled`, so the ratio is a recall rate rather than
    /// the old flow-vs-stock mismatch.
    #[serde(default)]
    pub distill_produced: u32,
    /// How many of that mature cohort have been recalled — the numerator.
    #[serde(default)]
    pub distill_recalled: u32,
    /// Merges the evolution gate rejected this cycle (would fuse distinct
    /// knowledge). Surfaced via the `note_manage(action="evolution")` tool.
    #[serde(default)]
    pub merges_rejected: u32,
    /// Cycle-level evolution-gate outcome (memory-health before/after). `None`
    /// when the gate did not run (e.g. conserve cycles, missing provider).
    #[serde(default)]
    pub evolution: Option<EvolutionOutcome>,
    /// Stages that were executed during this run.
    #[serde(skip)]
    pub stages_executed: Vec<String>,
    /// Stage at which the pipeline was interrupted (if any).
    #[serde(skip)]
    pub interrupted_at_stage: Option<String>,
    /// Overall run status.
    #[serde(skip)]
    pub status: DreamReportStatus,
    /// Flexible key-value extras populated by individual stages (not serialised).
    #[serde(skip)]
    pub extra: std::collections::BTreeMap<String, String>,
}
