//! `DreamReport` for the dream pipeline.

use serde::{Deserialize, Serialize};

use crate::memory::dreaming::distill_action::DistillActionRecord;
use crate::memory::dreaming::evolution::EvolutionOutcome;
use crate::memory::dreaming::selector::GateDecision;
use crate::memory::dreaming::strategy::DreamStrategy;

/// Status of a completed dream pipeline run.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
#[derive(Default)]
pub enum DreamReportStatus {
    #[default]
    Completed,
    Interrupted,
    Failed,
}

/// Why a dream cycle did what it did.
///
/// The counters live on [`DreamReport`]; this is the other half — which
/// strategy was chosen, on what rationale, whether the churn gate forced a
/// Conserve, which stages actually ran, and whether validation passed.
///
/// It is persisted next to the run's counters (`dream_reports.decision_json`)
/// specifically so the human-facing surface can answer the operator's first
/// question — *"why is dreaming always conserving?"* — from the same read that
/// produces the run list. Before this existed the answer lived only in
/// `dream_events.jsonl` and was therefore visible to the *model*
/// (`note_manage(action="evolution")`) but not to the operator.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CycleDecision {
    /// Pipeline the selector chose.
    pub strategy: DreamStrategy,
    /// Human-readable justification (signal scores vs threshold, or the gate's
    /// conserve reason).
    pub rationale: String,
    /// Sliding-window personality nudge applied to the synthesize threshold.
    pub personality_adjustment: f64,
    /// Churn-gate verdict that constrained the selection.
    pub gate: GateDecision,
    /// Stages the pipeline actually executed. Empty when the pipeline was
    /// skipped (no AI provider / embedder).
    #[serde(default)]
    pub stages: Vec<String>,
    /// Whether deterministic validation (L1 format + L2 duplicate-hash) passed.
    /// This is the same verdict that feeds the selector's personality window.
    pub validation_passed: bool,
}

/// Report generated by dream pipeline execution.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct DreamReport {
    pub pipeline_type: String,
    pub started_at: i64,
    pub finished_at: i64,
    pub duration_ms: u64,
    pub notes_consolidated: u32,
    pub contradictions_found: u32,
    pub notes_marked_stale: u32,
    pub synthesis_count: u32,
    pub format_fixed: u32,
    pub broken_links_found: u32,
    pub links_repaired: u32,
    pub links_purged: u32,
    pub notes_archived: u32,
    pub notes_protected: u32,
    /// Orphan notes successfully woven into the link graph by `NoteWeave`.
    #[serde(default)]
    pub notes_woven: u32,
    /// Goal lessons promoted into long-term notes by `GoalLessonsPromoteStage`.
    #[serde(default)]
    pub goal_lessons_promoted: u32,
    pub errors: Option<String>,
    /// Per-action provenance produced by the `SkillDistill` and
    /// `FeedbackDistill` stages. Preserves which `DistillAction` variant
    /// fired, against which candidate, and the apply outcome — the layer
    /// previously collapsed into a single `*_distill_count` counter.
    ///
    /// `#[serde(default)]` keeps the existing `dream_events.jsonl` (which
    /// pre-dates this field) deserializable without a migration.
    #[serde(default)]
    pub distill_actions: Vec<DistillActionRecord>,
    /// Note pairs merged this cycle (keeper, absorbed). Folded into
    /// `MutationGate`'s merge-cycle detector on the *next* cycle, via the
    /// persisted event log — this field is the durable input, not a hint.
    #[serde(default)]
    pub merged_pairs: Vec<(String, String)>,
    /// Synthesis notes written this cycle as `(path, body digest)`. Folded into
    /// `MutationGate`'s synthesis-churn detector.
    ///
    /// The digest covers the synthesis **body only**, deliberately not the
    /// rendered markdown: frontmatter carries an `updated` date that changes on
    /// every write, so a whole-file hash would report churn every single night.
    ///
    /// This replaced a `Vec<String>` of full synthesis bodies that fed a
    /// regex-negation "oscillation" detector. That detector was both dead (see
    /// `mutation_gate`'s module docs) and, had it been live, a rule-based
    /// re-judgement of a semantic question the `note_drift` LLM stage already
    /// answers (R7/P8) — plus it duplicated every synthesis essay into the
    /// event log.
    #[serde(default)]
    pub synthesis_rewrites: Vec<(String, String)>,
    /// Mature skill-note cohort size (created more than `MATURE_SKILL_DAYS`
    /// ago) — the denominator of MutationGate's wasted-distillation ratio. Same
    /// cohort as `distill_recalled`, so the ratio is a recall rate rather than
    /// the old flow-vs-stock mismatch.
    #[serde(default)]
    pub distill_produced: u32,
    /// How many of that mature cohort have been recalled — the numerator.
    #[serde(default)]
    pub distill_recalled: u32,
    /// Merges the evolution gate rejected this cycle (would fuse distinct
    /// knowledge). Surfaced via the `note_manage(action="evolution")` tool.
    #[serde(default)]
    pub merges_rejected: u32,
    /// Cycle-level evolution-gate outcome (memory-health before/after). `None`
    /// when the gate did not run (e.g. conserve cycles, missing provider).
    #[serde(default)]
    pub evolution: Option<EvolutionOutcome>,
    /// Stages that were executed during this run.
    #[serde(skip)]
    pub stages_executed: Vec<String>,
    /// Stage at which the pipeline was interrupted (if any).
    #[serde(skip)]
    pub interrupted_at_stage: Option<String>,
    /// Overall run status.
    #[serde(skip)]
    pub status: DreamReportStatus,
    /// Flexible key-value extras populated by individual stages (not serialised).
    #[serde(skip)]
    pub extra: std::collections::BTreeMap<String, String>,
}

impl DreamReport {
    /// A cycle that yielded to returning user activity before executing a
    /// single stage.
    ///
    /// Nothing happened, so there is nothing to account for, and both durable
    /// records skip it for reasons that point the same way:
    ///
    /// - the **event log**, because the churn gate's window is only a few
    ///   cycles deep — an empty night would push real churn out of range and
    ///   disarm the detectors exactly when the corpus is being touched most;
    /// - the **`dream_reports` audit table**, because the governance probe reads
    ///   run counts as a reality signal, and no-op runs inflate it.
    ///
    /// A *partially* executed cycle IS recorded in both: its merges are real,
    /// and unrecorded merges are what the per-namespace history exists to stop.
    /// One predicate rather than two copies — they have to agree, and the way
    /// they would disagree (a row with no matching event, or the reverse) is
    /// silent.
    #[must_use]
    pub fn is_vacuous_interruption(&self) -> bool {
        self.status == DreamReportStatus::Interrupted && self.stages_executed.is_empty()
    }
}
