//! DreamReport for the dream pipeline.

use serde::{Deserialize, Serialize};

/// Status of a completed dream pipeline run.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
#[derive(Default)]
pub enum DreamReportStatus {
    #[default]
    Completed,
    Interrupted,
    Failed,
}

/// Report generated by dream pipeline execution.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct DreamReport {
    pub pipeline_type: String,
    pub started_at: i64,
    pub finished_at: i64,
    pub duration_ms: u64,
    pub notes_consolidated: u32,
    pub contradictions_found: u32,
    pub notes_marked_stale: u32,
    pub synthesis_count: u32,
    pub format_fixed: u32,
    pub broken_links_found: u32,
    pub links_repaired: u32,
    pub links_purged: u32,
    pub notes_archived: u32,
    pub notes_protected: u32,
    pub errors: Option<String>,
    /// Stages that were executed during this run.
    #[serde(skip)]
    pub stages_executed: Vec<String>,
    /// Stage at which the pipeline was interrupted (if any).
    #[serde(skip)]
    pub interrupted_at_stage: Option<String>,
    /// Overall run status.
    #[serde(skip)]
    pub status: DreamReportStatus,
    /// Flexible key-value extras populated by individual stages (not serialised).
    #[serde(skip)]
    pub extra: std::collections::BTreeMap<String, String>,
}
