//! `overview.md` — LLM-maintained global synthesis of the note corpus.
//! The generator only does idempotent disk I/O (header + body); the synthesis
//! text is produced by `CorpusNarrativeStage`.

use crate::error::AlephError;
use std::path::PathBuf;

pub const OVERVIEW_FILENAME: &str = "overview.md";

pub struct OverviewMd {
    agent_dir: PathBuf,
}

impl OverviewMd {
    pub fn new(agent_dir: impl Into<PathBuf>) -> Self {
        Self {
            agent_dir: agent_dir.into(),
        }
    }
    fn path(&self) -> PathBuf {
        self.agent_dir.join(OVERVIEW_FILENAME)
    }

    /// Write the synthesis body with an auto-generated header banner.
    pub async fn write(&self, body: &str) -> Result<(), AlephError> {
        tokio::fs::create_dir_all(&self.agent_dir)
            .await
            .map_err(|e| AlephError::other(format!("create overview dir: {e}")))?;
        let now = chrono::Utc::now().format("%Y-%m-%dT%H:%M:%SZ");
        let text = format!("<!-- auto-generated by CorpusNarrativeStage | updated: {now} -->\n\n# Overview\n\n{}\n", body.trim());
        tokio::fs::write(self.path(), text)
            .await
            .map_err(|e| AlephError::other(format!("write overview: {e}")))
    }

    /// Read current overview body (empty string if absent).
    pub async fn read(&self) -> String {
        tokio::fs::read_to_string(self.path())
            .await
            .unwrap_or_default()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    #[tokio::test]
    async fn write_then_read_roundtrip() {
        let d = tempfile::tempdir().unwrap();
        let g = OverviewMd::new(d.path());
        g.write("The corpus centres on Rust async and the user's editor setup.")
            .await
            .unwrap();
        let got = g.read().await;
        assert!(got.contains("# Overview"));
        assert!(got.contains("Rust async"));
    }
}
