//! `purpose.md` — seeded + maintained by CorpusNarrativeStage; user-editable.
//! The generator only does idempotent disk I/O (header + body); the synthesis
//! text is produced by `CorpusNarrativeStage`.

use std::path::PathBuf;
use crate::error::AlephError;

pub const PURPOSE_FILENAME: &str = "purpose.md";

pub struct PurposeMd { agent_dir: PathBuf }

impl PurposeMd {
    pub fn new(agent_dir: impl Into<PathBuf>) -> Self { Self { agent_dir: agent_dir.into() } }
    fn path(&self) -> PathBuf { self.agent_dir.join(PURPOSE_FILENAME) }

    /// Write the purpose body with an auto-generated header banner.
    pub async fn write(&self, body: &str) -> Result<(), AlephError> {
        tokio::fs::create_dir_all(&self.agent_dir).await
            .map_err(|e| AlephError::other(format!("create purpose dir: {e}")))?;
        let now = chrono::Utc::now().format("%Y-%m-%dT%H:%M:%SZ");
        let text = format!("<!-- auto-generated by CorpusNarrativeStage | updated: {now} -->\n\n# Purpose\n\n{}\n", body.trim());
        tokio::fs::write(self.path(), text).await
            .map_err(|e| AlephError::other(format!("write purpose: {e}")))
    }

    /// Read current purpose body (empty string if absent).
    pub async fn read(&self) -> String {
        tokio::fs::read_to_string(self.path()).await.unwrap_or_default()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    #[tokio::test]
    async fn write_then_read_roundtrip() {
        let d = tempfile::tempdir().unwrap();
        let g = PurposeMd::new(d.path());
        g.write("Capture learnings about Rust and distributed systems.").await.unwrap();
        let got = g.read().await;
        assert!(got.contains("# Purpose"));
        assert!(got.contains("Rust"));
    }
}
