// <auto-generated>
// This file is auto-generated by csbindgen during Rust build.
// Do not edit manually.
// </auto-generated>

#pragma warning disable CS8981

using System;
using System.Runtime.InteropServices;

namespace Aether.Interop
{
    /// <summary>
    /// P/Invoke bindings for the Aether Rust core library.
    /// Generated by csbindgen from ffi_cabi.rs exports.
    /// </summary>
    public static unsafe partial class NativeMethods
    {
        private const string DllName = "aethecore";

        /// <summary>
        /// Initialize the Aether core library.
        /// </summary>
        /// <param name="config_path">Path to the configuration file (UTF-8 encoded, null-terminated)</param>
        /// <returns>0 on success, non-zero error code on failure</returns>
        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int aether_init(byte* config_path);

        /// <summary>
        /// Free resources allocated by the Aether core library.
        /// </summary>
        /// <returns>0 on success</returns>
        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int aether_free();

        /// <summary>
        /// Get the version string of the Aether core library.
        /// </summary>
        /// <returns>Pointer to a null-terminated UTF-8 string containing the version</returns>
        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* aether_version();

        /// <summary>
        /// Callback function type for state changes.
        /// </summary>
        /// <param name="state">The new state value</param>
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate void StateChangeCallback(int state);

        /// <summary>
        /// Callback function type for streaming text.
        /// </summary>
        /// <param name="text">Pointer to the text chunk (UTF-8 encoded, null-terminated)</param>
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate void StreamTextCallback(byte* text);

        /// <summary>
        /// Callback function type for errors.
        /// </summary>
        /// <param name="message">Pointer to the error message (UTF-8 encoded, null-terminated)</param>
        /// <param name="code">Error code</param>
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate void ErrorCallback(byte* message, int code);

        /// <summary>
        /// Register a callback for state changes.
        /// </summary>
        /// <param name="callback">Function pointer to call when state changes</param>
        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void aether_register_state_callback(StateChangeCallback callback);

        /// <summary>
        /// Register a callback for streaming text.
        /// </summary>
        /// <param name="callback">Function pointer to call when streaming text is received</param>
        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void aether_register_stream_callback(StreamTextCallback callback);

        /// <summary>
        /// Register a callback for errors.
        /// </summary>
        /// <param name="callback">Function pointer to call when an error occurs</param>
        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void aether_register_error_callback(ErrorCallback callback);
    }
}

#pragma warning restore CS8981
