// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace Aether.Interop
{
    public static unsafe partial class NativeMethods
    {
        const string __DllName = "aethecore";





        /// <summary>
        ///  Initialize the Aether core library
        ///
        ///  # Arguments
        ///  * `config_path` - Path to the configuration file (UTF-8 encoded, null-terminated)
        ///
        ///  # Returns
        ///  * `0` on success
        ///  * `-1` if config_path is null
        ///  * `-2` if config_path is not valid UTF-8
        ///  * `-4` if already initialized
        ///  * `-5` if config error
        ///
        ///  # Safety
        ///  The `config_path` must be a valid null-terminated UTF-8 string
        /// </summary>
        [DllImport(__DllName, EntryPoint = "aether_init", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int aether_init(byte* config_path);

        /// <summary>
        ///  Check if the core is initialized
        ///
        ///  # Returns
        ///  * `1` if initialized
        ///  * `0` if not initialized
        /// </summary>
        [DllImport(__DllName, EntryPoint = "aether_is_initialized", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int aether_is_initialized();

        /// <summary>
        ///  Free resources allocated by the Aether core library
        ///
        ///  Should be called when the application is shutting down.
        ///
        ///  # Returns
        ///  * `0` on success
        /// </summary>
        [DllImport(__DllName, EntryPoint = "aether_free", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int aether_free();

        /// <summary>
        ///  Get the version string of the Aether core library
        ///
        ///  # Returns
        ///  A pointer to a null-terminated UTF-8 string containing the version.
        ///  The returned string is statically allocated and should not be freed.
        ///
        ///  # Safety
        ///  The returned pointer is valid for the lifetime of the library.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "aether_version", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* aether_version();

        /// <summary>
        ///  Register a callback for state changes
        ///
        ///  # Arguments
        ///  * `callback` - Function pointer to call when state changes
        ///
        ///  # Safety
        ///  The callback must be valid for the lifetime of the library usage.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "aether_register_state_callback", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void aether_register_state_callback(delegate* unmanaged[Cdecl]<int, void> callback);

        /// <summary>
        ///  Register a callback for streaming text
        ///
        ///  # Arguments
        ///  * `callback` - Function pointer to call when streaming text is received
        ///
        ///  # Safety
        ///  The callback must be valid for the lifetime of the library usage.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "aether_register_stream_callback", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void aether_register_stream_callback(delegate* unmanaged[Cdecl]<byte*, void> callback);

        /// <summary>
        ///  Register a callback for completion
        ///
        ///  # Arguments
        ///  * `callback` - Function pointer to call when processing completes
        ///
        ///  # Safety
        ///  The callback must be valid for the lifetime of the library usage.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "aether_register_complete_callback", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void aether_register_complete_callback(delegate* unmanaged[Cdecl]<byte*, void> callback);

        /// <summary>
        ///  Register a callback for errors
        ///
        ///  # Arguments
        ///  * `callback` - Function pointer to call when an error occurs
        ///
        ///  # Safety
        ///  The callback must be valid for the lifetime of the library usage.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "aether_register_error_callback", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void aether_register_error_callback(delegate* unmanaged[Cdecl]<byte*, int, void> callback);

        /// <summary>
        ///  Register a callback for tool execution
        ///
        ///  # Arguments
        ///  * `callback` - Function pointer to call when a tool is executed
        ///
        ///  # Safety
        ///  The callback must be valid for the lifetime of the library usage.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "aether_register_tool_callback", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void aether_register_tool_callback(delegate* unmanaged[Cdecl]<byte*, int, byte*, void> callback);

        /// <summary>
        ///  Register a callback for memory stored notification
        ///
        ///  # Arguments
        ///  * `callback` - Function pointer to call when memory is stored
        ///
        ///  # Safety
        ///  The callback must be valid for the lifetime of the library usage.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "aether_register_memory_stored_callback", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void aether_register_memory_stored_callback(delegate* unmanaged[Cdecl]<void> callback);

        /// <summary>
        ///  Clear all registered callbacks
        /// </summary>
        [DllImport(__DllName, EntryPoint = "aether_clear_callbacks", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void aether_clear_callbacks();

        /// <summary>
        ///  Process user input
        ///
        ///  # Arguments
        ///  * `input` - User input text (UTF-8 encoded, null-terminated)
        ///  * `app_context` - Optional app context/bundle ID (UTF-8 encoded, null-terminated, can be null)
        ///  * `window_title` - Optional window title (UTF-8 encoded, null-terminated, can be null)
        ///  * `topic_id` - Optional topic ID for multi-turn conversation (can be null)
        ///  * `stream` - Whether to stream the response (1 = stream, 0 = wait for complete)
        ///
        ///  # Returns
        ///  * `0` on success (processing started)
        ///  * Error code on failure
        ///
        ///  # Safety
        ///  All string parameters must be valid null-terminated UTF-8 strings or null.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "aether_process", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int aether_process(byte* input, byte* app_context, byte* window_title, byte* topic_id, int stream);

        /// <summary>
        ///  Cancel the current processing operation
        ///
        ///  # Returns
        ///  * `0` on success
        ///  * `-3` if not initialized
        /// </summary>
        [DllImport(__DllName, EntryPoint = "aether_cancel", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int aether_cancel();

        /// <summary>
        ///  Check if the current operation is cancelled
        ///
        ///  # Returns
        ///  * `1` if cancelled
        ///  * `0` if not cancelled
        /// </summary>
        [DllImport(__DllName, EntryPoint = "aether_is_cancelled", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int aether_is_cancelled();

        /// <summary>
        ///  Load configuration and return as JSON string
        ///
        ///  # Arguments
        ///  * `out_json` - Pointer to receive the JSON string pointer
        ///  * `out_len` - Pointer to receive the JSON string length
        ///
        ///  # Returns
        ///  * `0` on success
        ///  * Error code on failure
        ///
        ///  # Safety
        ///  The caller must free the returned string using `aether_free_string`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "aether_load_config", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int aether_load_config(byte** out_json, nuint* out_len);

        /// <summary>
        ///  Get the default provider name
        ///
        ///  # Arguments
        ///  * `out_provider` - Pointer to receive the provider name pointer
        ///
        ///  # Returns
        ///  * `0` on success
        ///  * Error code on failure
        ///
        ///  # Safety
        ///  The caller must free the returned string using `aether_free_string`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "aether_get_default_provider", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int aether_get_default_provider(byte** out_provider);

        /// <summary>
        ///  Set the default provider
        ///
        ///  # Arguments
        ///  * `provider_name` - The provider name (UTF-8 encoded, null-terminated)
        ///
        ///  # Returns
        ///  * `0` on success
        ///  * Error code on failure
        /// </summary>
        [DllImport(__DllName, EntryPoint = "aether_set_default_provider", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int aether_set_default_provider(byte* provider_name);

        /// <summary>
        ///  Update provider configuration
        ///
        ///  # Arguments
        ///  * `name` - Provider name (UTF-8 encoded, null-terminated)
        ///  * `config_json` - Provider config as JSON (UTF-8 encoded, null-terminated)
        ///
        ///  # Returns
        ///  * `0` on success
        ///  * Error code on failure
        /// </summary>
        [DllImport(__DllName, EntryPoint = "aether_update_provider", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int aether_update_provider(byte* name, byte* config_json);

        /// <summary>
        ///  Delete a provider
        ///
        ///  # Arguments
        ///  * `name` - Provider name (UTF-8 encoded, null-terminated)
        ///
        ///  # Returns
        ///  * `0` on success
        ///  * Error code on failure
        /// </summary>
        [DllImport(__DllName, EntryPoint = "aether_delete_provider", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int aether_delete_provider(byte* name);

        /// <summary>
        ///  Test provider connection
        ///
        ///  # Arguments
        ///  * `provider_name` - Provider name (UTF-8 encoded, null-terminated)
        ///  * `config_json` - Provider config as JSON (UTF-8 encoded, null-terminated)
        ///  * `out_success` - Pointer to receive success flag (1 = success, 0 = failure)
        ///  * `out_message` - Pointer to receive result message
        ///
        ///  # Returns
        ///  * `0` on success
        ///  * Error code on failure
        /// </summary>
        [DllImport(__DllName, EntryPoint = "aether_test_provider_connection", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int aether_test_provider_connection(byte* provider_name, byte* config_json, int* out_success, byte** out_message);

        /// <summary>
        ///  Search memory
        ///
        ///  # Arguments
        ///  * `query` - Search query (UTF-8 encoded, null-terminated)
        ///  * `limit` - Maximum number of results
        ///  * `out_json` - Pointer to receive results as JSON
        ///  * `out_len` - Pointer to receive JSON length
        ///
        ///  # Returns
        ///  * `0` on success
        ///  * Error code on failure
        /// </summary>
        [DllImport(__DllName, EntryPoint = "aether_search_memory", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int aether_search_memory(byte* query, int limit, byte** out_json, nuint* out_len);

        /// <summary>
        ///  Clear all memory
        ///
        ///  # Returns
        ///  * `0` on success
        ///  * Error code on failure
        /// </summary>
        [DllImport(__DllName, EntryPoint = "aether_clear_memory", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int aether_clear_memory();

        /// <summary>
        ///  Get memory statistics
        ///
        ///  # Arguments
        ///  * `out_json` - Pointer to receive stats as JSON
        ///  * `out_len` - Pointer to receive JSON length
        ///
        ///  # Returns
        ///  * `0` on success
        ///  * Error code on failure
        /// </summary>
        [DllImport(__DllName, EntryPoint = "aether_get_memory_stats", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int aether_get_memory_stats(byte** out_json, nuint* out_len);

        /// <summary>
        ///  Free a string allocated by the library
        ///
        ///  # Arguments
        ///  * `ptr` - Pointer to the string to free
        ///
        ///  # Safety
        ///  Only pass pointers returned by other aether_* functions.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "aether_free_string", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void aether_free_string(byte* ptr);

        /// <summary>
        ///  Get the last error message
        ///
        ///  # Arguments
        ///  * `out_message` - Pointer to receive error message
        ///
        ///  # Returns
        ///  * `0` on success
        ///  * `-1` if no error available
        /// </summary>
        [DllImport(__DllName, EntryPoint = "aether_get_last_error", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int aether_get_last_error(byte** out_message);

        /// <summary>
        ///  Reload configuration from disk
        ///
        ///  # Returns
        ///  * `0` on success
        ///  * Error code on failure
        /// </summary>
        [DllImport(__DllName, EntryPoint = "aether_reload_config", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int aether_reload_config();

        /// <summary>
        ///  Get list of available tools as JSON
        ///
        ///  # Arguments
        ///  * `out_json` - Pointer to receive tools list as JSON
        ///  * `out_len` - Pointer to receive JSON length
        ///
        ///  # Returns
        ///  * `0` on success
        ///  * Error code on failure
        /// </summary>
        [DllImport(__DllName, EntryPoint = "aether_list_tools", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int aether_list_tools(byte** out_json, nuint* out_len);

        /// <summary>
        ///  Get root commands for command completion
        ///
        ///  # Arguments
        ///  * `out_json` - Pointer to receive commands as JSON
        ///  * `out_len` - Pointer to receive JSON length
        ///
        ///  # Returns
        ///  * `0` on success
        ///  * Error code on failure
        /// </summary>
        [DllImport(__DllName, EntryPoint = "aether_get_root_commands", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int aether_get_root_commands(byte** out_json, nuint* out_len);

        /// <summary>
        ///  Set log level
        ///
        ///  # Arguments
        ///  * `level` - Log level (0=Error, 1=Warn, 2=Info, 3=Debug, 4=Trace)
        ///
        ///  # Returns
        ///  * `0` on success
        /// </summary>
        [DllImport(__DllName, EntryPoint = "aether_set_log_level", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int aether_set_log_level(int level);

        /// <summary>
        ///  Get log directory path
        ///
        ///  # Arguments
        ///  * `out_path` - Pointer to receive path
        ///
        ///  # Returns
        ///  * `0` on success
        ///  * Error code on failure
        /// </summary>
        [DllImport(__DllName, EntryPoint = "aether_get_log_directory", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int aether_get_log_directory(byte** out_path);

        /// <summary>
        ///  List all MCP servers as JSON
        ///
        ///  # Arguments
        ///  * `out_json` - Pointer to receive servers list as JSON
        ///  * `out_len` - Pointer to receive JSON length
        ///
        ///  # Returns
        ///  * `0` on success
        ///  * Error code on failure
        ///
        ///  # Safety
        ///  The caller must free the returned string using `aether_free_string`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "aether_list_mcp_servers", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int aether_list_mcp_servers(byte** out_json, nuint* out_len);

        /// <summary>
        ///  Add an MCP server
        ///
        ///  # Arguments
        ///  * `config_json` - Server configuration as JSON (UTF-8 encoded, null-terminated)
        ///
        ///  # Returns
        ///  * `0` on success
        ///  * Error code on failure
        /// </summary>
        [DllImport(__DllName, EntryPoint = "aether_add_mcp_server", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int aether_add_mcp_server(byte* config_json);

        /// <summary>
        ///  Update an MCP server configuration
        ///
        ///  # Arguments
        ///  * `config_json` - Server configuration as JSON (UTF-8 encoded, null-terminated)
        ///
        ///  # Returns
        ///  * `0` on success
        ///  * Error code on failure
        /// </summary>
        [DllImport(__DllName, EntryPoint = "aether_update_mcp_server", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int aether_update_mcp_server(byte* config_json);

        /// <summary>
        ///  Delete an MCP server
        ///
        ///  # Arguments
        ///  * `server_id` - Server ID (UTF-8 encoded, null-terminated)
        ///
        ///  # Returns
        ///  * `0` on success
        ///  * Error code on failure
        /// </summary>
        [DllImport(__DllName, EntryPoint = "aether_delete_mcp_server", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int aether_delete_mcp_server(byte* server_id);

        /// <summary>
        ///  Get MCP server status
        ///
        ///  # Arguments
        ///  * `server_id` - Server ID (UTF-8 encoded, null-terminated)
        ///  * `out_json` - Pointer to receive status as JSON
        ///  * `out_len` - Pointer to receive JSON length
        ///
        ///  # Returns
        ///  * `0` on success
        ///  * Error code on failure
        /// </summary>
        [DllImport(__DllName, EntryPoint = "aether_get_mcp_server_status", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int aether_get_mcp_server_status(byte* server_id, byte** out_json, nuint* out_len);

        /// <summary>
        ///  Export MCP configuration as claude_desktop_config.json format
        ///
        ///  # Arguments
        ///  * `out_json` - Pointer to receive JSON
        ///  * `out_len` - Pointer to receive JSON length
        ///
        ///  # Returns
        ///  * `0` on success
        ///  * Error code on failure
        /// </summary>
        [DllImport(__DllName, EntryPoint = "aether_export_mcp_config", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int aether_export_mcp_config(byte** out_json, nuint* out_len);

        /// <summary>
        ///  Import MCP configuration from claude_desktop_config.json format
        ///
        ///  # Arguments
        ///  * `json` - JSON configuration (UTF-8 encoded, null-terminated)
        ///
        ///  # Returns
        ///  * `0` on success
        ///  * Error code on failure
        /// </summary>
        [DllImport(__DllName, EntryPoint = "aether_import_mcp_config", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int aether_import_mcp_config(byte* json);

        /// <summary>
        ///  List all installed skills as JSON
        ///
        ///  # Arguments
        ///  * `out_json` - Pointer to receive skills list as JSON
        ///  * `out_len` - Pointer to receive JSON length
        ///
        ///  # Returns
        ///  * `0` on success
        ///  * Error code on failure
        ///
        ///  # Safety
        ///  The caller must free the returned string using `aether_free_string`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "aether_list_skills", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int aether_list_skills(byte** out_json, nuint* out_len);

        /// <summary>
        ///  Install a skill from URL
        ///
        ///  # Arguments
        ///  * `url` - GitHub URL or direct download URL (UTF-8 encoded, null-terminated)
        ///  * `out_json` - Pointer to receive installed skill info as JSON
        ///  * `out_len` - Pointer to receive JSON length
        ///
        ///  # Returns
        ///  * `0` on success
        ///  * Error code on failure
        /// </summary>
        [DllImport(__DllName, EntryPoint = "aether_install_skill", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int aether_install_skill(byte* url, byte** out_json, nuint* out_len);

        /// <summary>
        ///  Install skills from ZIP file
        ///
        ///  # Arguments
        ///  * `zip_path` - Path to ZIP file (UTF-8 encoded, null-terminated)
        ///  * `out_json` - Pointer to receive installed skill IDs as JSON array
        ///  * `out_len` - Pointer to receive JSON length
        ///
        ///  # Returns
        ///  * `0` on success
        ///  * Error code on failure
        /// </summary>
        [DllImport(__DllName, EntryPoint = "aether_install_skills_from_zip", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int aether_install_skills_from_zip(byte* zip_path, byte** out_json, nuint* out_len);

        /// <summary>
        ///  Delete a skill
        ///
        ///  # Arguments
        ///  * `skill_id` - Skill ID (UTF-8 encoded, null-terminated)
        ///
        ///  # Returns
        ///  * `0` on success
        ///  * Error code on failure
        /// </summary>
        [DllImport(__DllName, EntryPoint = "aether_delete_skill", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int aether_delete_skill(byte* skill_id);

        /// <summary>
        ///  Get skills directory path
        ///
        ///  # Arguments
        ///  * `out_path` - Pointer to receive path
        ///
        ///  # Returns
        ///  * `0` on success
        ///  * Error code on failure
        /// </summary>
        [DllImport(__DllName, EntryPoint = "aether_get_skills_dir", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int aether_get_skills_dir(byte** out_path);

        /// <summary>
        ///  Refresh skills registry
        ///
        ///  # Returns
        ///  * `0` on success
        ///  * Error code on failure
        /// </summary>
        [DllImport(__DllName, EntryPoint = "aether_refresh_skills", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int aether_refresh_skills();

        /// <summary>
        ///  List all generation providers as JSON
        ///
        ///  # Arguments
        ///  * `out_json` - Pointer to receive providers list as JSON
        ///  * `out_len` - Pointer to receive JSON length
        ///
        ///  # Returns
        ///  * `0` on success
        ///  * Error code on failure
        /// </summary>
        [DllImport(__DllName, EntryPoint = "aether_list_generation_providers", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int aether_list_generation_providers(byte** out_json, nuint* out_len);

        /// <summary>
        ///  Get generation provider configuration
        ///
        ///  # Arguments
        ///  * `provider_id` - Provider ID (UTF-8 encoded, null-terminated)
        ///  * `out_json` - Pointer to receive config as JSON
        ///  * `out_len` - Pointer to receive JSON length
        ///
        ///  # Returns
        ///  * `0` on success
        ///  * Error code on failure
        /// </summary>
        [DllImport(__DllName, EntryPoint = "aether_get_generation_provider_config", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int aether_get_generation_provider_config(byte* provider_id, byte** out_json, nuint* out_len);

        /// <summary>
        ///  Update generation provider configuration
        ///
        ///  # Arguments
        ///  * `provider_id` - Provider ID (UTF-8 encoded, null-terminated)
        ///  * `config_json` - Configuration as JSON (UTF-8 encoded, null-terminated)
        ///
        ///  # Returns
        ///  * `0` on success
        ///  * Error code on failure
        /// </summary>
        [DllImport(__DllName, EntryPoint = "aether_update_generation_provider", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int aether_update_generation_provider(byte* provider_id, byte* config_json);

        /// <summary>
        ///  Test generation provider connection
        ///
        ///  # Arguments
        ///  * `provider_id` - Provider ID (UTF-8 encoded, null-terminated)
        ///  * `api_key` - API key to test (UTF-8 encoded, null-terminated)
        ///  * `out_success` - Pointer to receive success flag (1 = success, 0 = failure)
        ///  * `out_message` - Pointer to receive result message
        ///
        ///  # Returns
        ///  * `0` on success
        ///  * Error code on failure
        /// </summary>
        [DllImport(__DllName, EntryPoint = "aether_test_generation_provider", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int aether_test_generation_provider(byte* provider_id, byte* api_key, int* out_success, byte** out_message);

        /// <summary>
        ///  Get routing configuration as JSON
        ///
        ///  # Arguments
        ///  * `out_json` - Pointer to receive config as JSON
        ///  * `out_len` - Pointer to receive JSON length
        ///
        ///  # Returns
        ///  * `0` on success
        ///  * Error code on failure
        /// </summary>
        [DllImport(__DllName, EntryPoint = "aether_get_routing_config", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int aether_get_routing_config(byte** out_json, nuint* out_len);

        /// <summary>
        ///  Update routing configuration
        ///
        ///  # Arguments
        ///  * `config_json` - Configuration as JSON (UTF-8 encoded, null-terminated)
        ///
        ///  # Returns
        ///  * `0` on success
        ///  * Error code on failure
        /// </summary>
        [DllImport(__DllName, EntryPoint = "aether_update_routing_config", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int aether_update_routing_config(byte* config_json);

        /// <summary>
        ///  Get behavior configuration as JSON
        ///
        ///  # Arguments
        ///  * `out_json` - Pointer to receive config as JSON
        ///  * `out_len` - Pointer to receive JSON length
        ///
        ///  # Returns
        ///  * `0` on success
        ///  * Error code on failure
        /// </summary>
        [DllImport(__DllName, EntryPoint = "aether_get_behavior_config", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int aether_get_behavior_config(byte** out_json, nuint* out_len);

        /// <summary>
        ///  Update behavior configuration
        ///
        ///  # Arguments
        ///  * `config_json` - Configuration as JSON (UTF-8 encoded, null-terminated)
        ///
        ///  # Returns
        ///  * `0` on success
        ///  * Error code on failure
        /// </summary>
        [DllImport(__DllName, EntryPoint = "aether_update_behavior_config", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int aether_update_behavior_config(byte* config_json);

        /// <summary>
        ///  List all search providers as JSON
        ///
        ///  # Arguments
        ///  * `out_json` - Pointer to receive providers list as JSON
        ///  * `out_len` - Pointer to receive JSON length
        ///
        ///  # Returns
        ///  * `0` on success
        ///  * Error code on failure
        /// </summary>
        [DllImport(__DllName, EntryPoint = "aether_list_search_providers", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int aether_list_search_providers(byte** out_json, nuint* out_len);

        /// <summary>
        ///  Get search provider configuration
        ///
        ///  # Arguments
        ///  * `provider_id` - Provider ID (UTF-8 encoded, null-terminated)
        ///  * `out_json` - Pointer to receive config as JSON
        ///  * `out_len` - Pointer to receive JSON length
        ///
        ///  # Returns
        ///  * `0` on success
        ///  * Error code on failure
        /// </summary>
        [DllImport(__DllName, EntryPoint = "aether_get_search_provider_config", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int aether_get_search_provider_config(byte* provider_id, byte** out_json, nuint* out_len);

        /// <summary>
        ///  Update search provider configuration
        ///
        ///  # Arguments
        ///  * `provider_id` - Provider ID (UTF-8 encoded, null-terminated)
        ///  * `config_json` - Configuration as JSON (UTF-8 encoded, null-terminated)
        ///
        ///  # Returns
        ///  * `0` on success
        ///  * Error code on failure
        /// </summary>
        [DllImport(__DllName, EntryPoint = "aether_update_search_provider", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int aether_update_search_provider(byte* provider_id, byte* config_json);

        /// <summary>
        ///  Test search provider connection
        ///
        ///  # Arguments
        ///  * `provider_id` - Provider ID (UTF-8 encoded, null-terminated)
        ///  * `api_key` - API key to test (UTF-8 encoded, null-terminated)
        ///  * `out_success` - Pointer to receive success flag (1 = success, 0 = failure)
        ///  * `out_message` - Pointer to receive result message
        ///
        ///  # Returns
        ///  * `0` on success
        ///  * Error code on failure
        /// </summary>
        [DllImport(__DllName, EntryPoint = "aether_test_search_provider", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int aether_test_search_provider(byte* provider_id, byte* api_key, int* out_success, byte** out_message);

        /// <summary>
        ///  Get cowork configuration as JSON
        ///
        ///  # Arguments
        ///  * `out_json` - Pointer to receive config as JSON
        ///  * `out_len` - Pointer to receive JSON length
        ///
        ///  # Returns
        ///  * `0` on success
        ///  * Error code on failure
        /// </summary>
        [DllImport(__DllName, EntryPoint = "aether_get_cowork_config", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int aether_get_cowork_config(byte** out_json, nuint* out_len);

        /// <summary>
        ///  Update cowork configuration
        ///
        ///  # Arguments
        ///  * `config_json` - Configuration as JSON (UTF-8 encoded, null-terminated)
        ///
        ///  # Returns
        ///  * `0` on success
        ///  * Error code on failure
        /// </summary>
        [DllImport(__DllName, EntryPoint = "aether_update_cowork_config", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int aether_update_cowork_config(byte* config_json);

        /// <summary>
        ///  Get policies configuration as JSON (read-only)
        ///
        ///  # Arguments
        ///  * `out_json` - Pointer to receive policies as JSON
        ///  * `out_len` - Pointer to receive JSON length
        ///
        ///  # Returns
        ///  * `0` on success
        ///  * Error code on failure
        /// </summary>
        [DllImport(__DllName, EntryPoint = "aether_get_policies", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int aether_get_policies(byte** out_json, nuint* out_len);

        /// <summary>
        ///  List all runtimes and their status as JSON
        ///
        ///  # Arguments
        ///  * `out_json` - Pointer to receive runtimes list as JSON
        ///  * `out_len` - Pointer to receive JSON length
        ///
        ///  # Returns
        ///  * `0` on success
        ///  * Error code on failure
        /// </summary>
        [DllImport(__DllName, EntryPoint = "aether_list_runtimes", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int aether_list_runtimes(byte** out_json, nuint* out_len);

        /// <summary>
        ///  Check if a runtime is installed
        ///
        ///  # Arguments
        ///  * `runtime_id` - Runtime ID (UTF-8 encoded, null-terminated)
        ///
        ///  # Returns
        ///  * `1` if installed
        ///  * `0` if not installed
        ///  * Error code on failure
        /// </summary>
        [DllImport(__DllName, EntryPoint = "aether_is_runtime_installed", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int aether_is_runtime_installed(byte* runtime_id);

        /// <summary>
        ///  Install a runtime
        ///
        ///  # Arguments
        ///  * `runtime_id` - Runtime ID (UTF-8 encoded, null-terminated)
        ///  * `out_message` - Pointer to receive status message
        ///
        ///  # Returns
        ///  * `0` on success
        ///  * Error code on failure
        /// </summary>
        [DllImport(__DllName, EntryPoint = "aether_install_runtime", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int aether_install_runtime(byte* runtime_id, byte** out_message);

        /// <summary>
        ///  Check for runtime updates
        ///
        ///  # Arguments
        ///  * `out_json` - Pointer to receive updates info as JSON
        ///  * `out_len` - Pointer to receive JSON length
        ///
        ///  # Returns
        ///  * `0` on success
        ///  * Error code on failure
        /// </summary>
        [DllImport(__DllName, EntryPoint = "aether_check_runtime_updates", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int aether_check_runtime_updates(byte** out_json, nuint* out_len);

        /// <summary>
        ///  Update a runtime
        ///
        ///  # Arguments
        ///  * `runtime_id` - Runtime ID (UTF-8 encoded, null-terminated)
        ///  * `out_message` - Pointer to receive status message
        ///
        ///  # Returns
        ///  * `0` on success
        ///  * Error code on failure
        /// </summary>
        [DllImport(__DllName, EntryPoint = "aether_update_runtime", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int aether_update_runtime(byte* runtime_id, byte** out_message);

        /// <summary>
        ///  Set auto-update preference for runtimes
        ///
        ///  # Arguments
        ///  * `enabled` - 1 to enable, 0 to disable
        ///
        ///  # Returns
        ///  * `0` on success
        ///  * Error code on failure
        /// </summary>
        [DllImport(__DllName, EntryPoint = "aether_set_runtime_auto_update", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int aether_set_runtime_auto_update(int enabled);

        /// <summary>
        ///  Check if first-time initialization is needed
        ///
        ///  Returns:
        ///  * `1` if initialization is needed
        ///  * `0` if already initialized
        /// </summary>
        [DllImport(__DllName, EntryPoint = "aether_needs_first_time_init", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int aether_needs_first_time_init();

        /// <summary>
        ///  Check if the embedding model is installed
        ///
        ///  Returns:
        ///  * `1` if model exists
        ///  * `0` if model does not exist
        /// </summary>
        [DllImport(__DllName, EntryPoint = "aether_check_embedding_model_exists", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int aether_check_embedding_model_exists();

        /// <summary>
        ///  Register initialization progress callbacks
        ///
        ///  # Safety
        ///  All callback function pointers must be valid for the duration of initialization.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "aether_register_init_callbacks", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int aether_register_init_callbacks(delegate* unmanaged[Cdecl]<byte*, uint, uint, void> on_phase_started, delegate* unmanaged[Cdecl]<byte*, double, byte*, void> on_phase_progress, delegate* unmanaged[Cdecl]<byte*, void> on_phase_completed, delegate* unmanaged[Cdecl]<byte*, ulong, ulong, void> on_download_progress, delegate* unmanaged[Cdecl]<byte*, byte*, int, void> on_error);

        /// <summary>
        ///  Clear initialization callbacks
        /// </summary>
        [DllImport(__DllName, EntryPoint = "aether_clear_init_callbacks", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void aether_clear_init_callbacks();

        /// <summary>
        ///  Run first-time initialization
        ///
        ///  This is a blocking function that runs the full 6-phase initialization.
        ///  Progress is reported via registered callbacks.
        ///
        ///  Returns:
        ///  * `0` on success
        ///  * Negative error code on failure
        /// </summary>
        [DllImport(__DllName, EntryPoint = "aether_run_first_time_init", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int aether_run_first_time_init();


    }



}
